- tools/serverpod_cli/bin/analytics/analytics.dart
- tools/serverpod_cli/bin/serverpod_cli.dart
> Updates documentation

- README.md
add markers to make dart code part more clear and easy to read
> (update) readme:

- modules/serverpod_auth/serverpod_auth_client/lib/src/protocol/authentication_fail_reason.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/generated/authentication_fail_reason.dart
- packages/serverpod/lib/src/generated/log_level.dart
- packages/serverpod_serialization/lib/src/serialization.dart
- packages/serverpod_service_client/lib/src/protocol/log_level.dart
- tests/serverpod_test_client/lib/src/protocol/client.dart
- tests/serverpod_test_client/lib/src/protocol/object_with_enum.dart
- tests/serverpod_test_client/lib/src/protocol/protocol.dart
- tests/serverpod_test_client/lib/src/protocol/test_enum.dart
- tests/serverpod_test_server/generated/protocol.yaml
- tests/serverpod_test_server/generated/tables.pgsql
- tests/serverpod_test_server/lib/src/endpoints/database_basic.dart
- tests/serverpod_test_server/lib/src/generated/endpoints.dart
- tests/serverpod_test_server/lib/src/generated/object_with_enum.dart
- tests/serverpod_test_server/lib/src/generated/protocol.dart
- tests/serverpod_test_server/lib/src/generated/test_enum.dart
- tests/serverpod_test_server/lib/src/protocol/object_with_enum.yaml
- tests/serverpod_test_server/lib/src/protocol/test_enum.yaml
- tests/serverpod_test_server/test/connection_test.dart
- tests/serverpod_test_server/test/serialization_test.dart
- tools/serverpod_cli/bin/generator/class_generator_dart.dart
> fix: Serialized enums now use proper enums rather than custom enum-like class.

- tools/serverpod_cli/bin/generator/pgsql_generator.dart
> Possibly fix psql code gen

- .github/workflows/dart-tests.yaml
- modules/serverpod_auth/serverpod_auth_server/generated/tables.pgsql
- templates/serverpod_templates/projectname_server/generated/tables-serverpod.pgsql
- util/ensure_no_changes
- util/run_tests
- util/run_tests_serverpod_generate
- util/run_tests_update_pubspecs
- util/update_pubspecs
> test: Adds test to see that pubspecs are updated using util/update_pubspecs

- tests/serverpod_test_client/pubspec.yaml
- tests/serverpod_test_module/serverpod_test_module_client/pubspec.yaml
- tests/serverpod_test_module/serverpod_test_module_server/pubspec.yaml
- tests/serverpod_test_server/pubspec.yaml
- tests/serverpod_test_shared/pubspec.yaml
> chore: Cleans up the pubspecs of the test packages.

- packages/serverpod/lib/src/cache/local_cache.dart
> fix: The local cache now supports complex serializable objects.

- packages/serverpod_serialization/lib/src/serialization.dart
> chore: Removes fixed TODOs.

- modules/serverpod_auth/serverpod_auth_shared_flutter/lib/src/session_manager.dart
> Updates preferences version in auth module

- packages/serverpod/lib/src/database/value_encoder.dart
- tests/serverpod_test_client/lib/src/protocol/client.dart
- tests/serverpod_test_client/lib/src/protocol/object_with_bytedata.dart
- tests/serverpod_test_client/lib/src/protocol/protocol.dart
- tests/serverpod_test_server/generated/protocol.yaml
- tests/serverpod_test_server/generated/tables.pgsql
- tests/serverpod_test_server/lib/src/endpoints/database_basic.dart
- tests/serverpod_test_server/lib/src/generated/endpoints.dart
- tests/serverpod_test_server/lib/src/generated/object_with_bytedata.dart
- tests/serverpod_test_server/lib/src/generated/protocol.dart
- tests/serverpod_test_server/lib/src/protocol/object_with_bytedata.yaml
- tests/serverpod_test_server/test/connection_test.dart
> fix: Correctly inserts ByteData into the database. Fixes #466.

- tools/serverpod_cli/bin/util/string_validators.dart
> feat: add support snack case for fields

- packages/serverpod/lib/src/database/expressions.dart
- packages/serverpod/lib/src/database/value_encoder.dart
- packages/serverpod_serialization/lib/src/serialization.dart
- tests/serverpod_test_client/lib/src/protocol/client.dart
- tests/serverpod_test_client/lib/src/protocol/nullability.dart
- tests/serverpod_test_client/lib/src/protocol/object_with_duration.dart
- tests/serverpod_test_client/lib/src/protocol/object_with_maps.dart
- tests/serverpod_test_client/lib/src/protocol/protocol.dart
- tests/serverpod_test_client/lib/src/protocol/types.dart
- tests/serverpod_test_server/generated/protocol.yaml
- tests/serverpod_test_server/generated/tables.pgsql
- tests/serverpod_test_server/lib/src/endpoints/basic_types.dart
- tests/serverpod_test_server/lib/src/endpoints/database_basic.dart
- tests/serverpod_test_server/lib/src/endpoints/list_parameters.dart
- tests/serverpod_test_server/lib/src/endpoints/map_parameters.dart
- tests/serverpod_test_server/lib/src/generated/endpoints.dart
- tests/serverpod_test_server/lib/src/generated/nullability.dart
- tests/serverpod_test_server/lib/src/generated/object_with_duration.dart
- tests/serverpod_test_server/lib/src/generated/object_with_maps.dart
- tests/serverpod_test_server/lib/src/generated/protocol.dart
- tests/serverpod_test_server/lib/src/generated/types.dart
- tests/serverpod_test_server/lib/src/protocol/nullability.yaml
- tests/serverpod_test_server/lib/src/protocol/object_with_duration.yaml
- tests/serverpod_test_server/lib/src/protocol/object_with_maps.yaml
- tests/serverpod_test_server/lib/src/protocol/types.yaml
- tests/serverpod_test_server/test/connection_test.dart
- tests/serverpod_test_server/test/serialization_test.dart
- tools/serverpod_cli/bin/generator/types.dart
> feat: add duration support (inMiliseconds)

- tools/serverpod_cli/bin/generator/class_analyzer.dart
- tools/serverpod_cli/bin/generator/class_generator.dart
- tools/serverpod_cli/bin/generator/class_generator_dart.dart
- tools/serverpod_cli/bin/generator/code_cleaner.dart
- tools/serverpod_cli/bin/generator/protocol_definition.dart
- tools/serverpod_cli/bin/generator/types.dart
- tools/serverpod_cli/bin/util/extensions.dart
The imports and exports of generated files in sub directories are not correct.
Also fixes deletion of previously generated files.
#545
> fix: exports and imports of generated files defined in subdirectories

- .github/pull_request_template.md
> chore: Typo in pull_request_template.md

- modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/signin_button.dart
<hr>
**_I have read the CLA Document and I hereby sign the CLA_**
<hr>
> Update signin_button.dart, fixed a couple of comments

- packages/serverpod/generated/tables.pgsql
- packages/serverpod/lib/src/protocol/server_health_metric.yaml
- templates/serverpod_templates/projectname_server/generated/tables-serverpod.pgsql
> fix: Fixes incorrectly set database index.

- .github/workflows/dart-tests.yaml
- packages/serverpod/lib/src/database/value_encoder.dart
- tests/docker/tests_single_server/Dockerfile-server
- tests/docker/tests_single_server/Dockerfile-tests
> chore: Updates Flutter version in tests

- modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/email_endpoint.dart
> fix: Masks out password in email module logging. Fixes #629.

- examples/auth_example/auth_example_server/README.md
- examples/chat/README.md
- templates/serverpod_templates/projectname_server/README.md
- templates/serverpod_templates/projectname_server/setup-tables
- templates/serverpod_templates/projectname_server/setup-tables.cmd
- tests/serverpod_test_server/docker-local/setup-tables
- tools/serverpod_cli/bin/create/create.dart
- tools/serverpod_cli/bin/run/runner.dart
- tools/serverpod_cli/bin/serverpod_cli.dart
- util/run_tests_single_server
> fix: Replace docker-compose with docker compose. Fixes #560

- tests/serverpod_test_client/lib/src/protocol/client.dart
- tests/serverpod_test_server/generated/protocol.yaml
- tests/serverpod_test_server/lib/src/endpoints/subDir/subSubDir/subsubdir_test_endpoint.dart
- tests/serverpod_test_server/lib/src/endpoints/subDir/subdir_test_endpoint.dart
- tests/serverpod_test_server/lib/src/generated/endpoints.dart
- tests/serverpod_test_server/test/connection_test.dart
- tools/serverpod_cli/bin/generator/class_analyzer.dart
- tools/serverpod_cli/bin/generator/protocol_analyzer.dart
- tools/serverpod_cli/bin/generator/protocol_definition.dart
- tools/serverpod_cli/bin/generator/protocol_generator.dart
- tools/serverpod_cli/bin/util/subdirectory_extraction.dart
Allows endpoints to be placed in sub folders.
Close #675 
*none*
> feat: Allow endpoints in sub folders

- PUBLISHABLE_PACKAGES
- integrations/serverpod_cloud_storage_gcp/.gitignore
- integrations/serverpod_cloud_storage_gcp/CHANGELOG.md
- integrations/serverpod_cloud_storage_gcp/LICENSE
- integrations/serverpod_cloud_storage_gcp/README.md
- integrations/serverpod_cloud_storage_gcp/analysis_options.yaml
- integrations/serverpod_cloud_storage_gcp/lib/serverpod_cloud_storage_gcp.dart
- integrations/serverpod_cloud_storage_gcp/lib/src/aws_s3_client/LICENSE
- integrations/serverpod_cloud_storage_gcp/lib/src/aws_s3_client/client/client.dart
- integrations/serverpod_cloud_storage_gcp/lib/src/aws_s3_client/client/exceptions.dart
- integrations/serverpod_cloud_storage_gcp/lib/src/aws_s3_client/model/list_bucket_result.dart
- integrations/serverpod_cloud_storage_gcp/lib/src/aws_s3_client/model/list_bucket_result.g.dart
- integrations/serverpod_cloud_storage_gcp/lib/src/aws_s3_client/model/list_bucket_result_contents.dart
- integrations/serverpod_cloud_storage_gcp/lib/src/aws_s3_client/model/list_bucket_result_contents.g.dart
- integrations/serverpod_cloud_storage_gcp/lib/src/aws_s3_client/model/list_bucket_result_parker.dart
- integrations/serverpod_cloud_storage_gcp/lib/src/aws_s3_client/model/list_bucket_result_parker.g.dart
- integrations/serverpod_cloud_storage_gcp/lib/src/aws_s3_client/model/serializers.dart
- integrations/serverpod_cloud_storage_gcp/lib/src/aws_s3_client/model/serializers.g.dart
- integrations/serverpod_cloud_storage_gcp/lib/src/aws_s3_upload/LICENSE
- integrations/serverpod_cloud_storage_gcp/lib/src/aws_s3_upload/aws_s3_upload.dart
- integrations/serverpod_cloud_storage_gcp/lib/src/aws_s3_upload/policy.dart
- integrations/serverpod_cloud_storage_gcp/lib/src/cloud_storage/google_cloud_storage.dart
- integrations/serverpod_cloud_storage_gcp/pubspec.yaml
- templates/pubspecs/integrations/serverpod_cloud_storage_gcp/pubspec.yaml
- util/pub_get_all
- util/run_tests_analyze
- util/update_pubspecs
> feat: Adds support for Google Cloud Storage.

- packages/serverpod/lib/src/database/database_pool_manager.dart
- packages/serverpod_shared/lib/src/config.dart
> feat: Adds option to use unix socket to connect to database.

- modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/firebase_endpoint.dart
- [ x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [ x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [ x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [ x] I listed at least one issue that this PR fixes in the description above.
- [x ] I updated/added relevant documentation (doc comments with `///`), and made …
> Add email from Firebase to UserInfo. Fixes #718

- modules/serverpod_auth/serverpod_auth_apple_flutter/pubspec.yaml
- modules/serverpod_auth/serverpod_auth_server/lib/src/business/user_images.dart
- modules/serverpod_auth/serverpod_auth_server/pubspec.yaml
- modules/serverpod_auth/serverpod_auth_shared_flutter/lib/src/image_uploader.dart
- modules/serverpod_auth/serverpod_auth_shared_flutter/pubspec.yaml
- modules/serverpod_chat/serverpod_chat_server/pubspec.yaml
- templates/pubspecs/modules/serverpod_auth/serverpod_auth_apple_flutter/pubspec.yaml
- templates/pubspecs/modules/serverpod_auth/serverpod_auth_server/pubspec.yaml
- templates/pubspecs/modules/serverpod_auth/serverpod_auth_shared_flutter/pubspec.yaml
- templates/pubspecs/modules/serverpod_chat/serverpod_chat_server/pubspec.yaml
> Update serverpod_auth dependency versions

- packages/serverpod/lib/src/database/database_pool_manager.dart
> feat: Allows connecting to Postgres through UNIX socket.

- packages/serverpod/lib/src/server/serverpod.dart
> feat: Print error message on startup if passwords.yaml file is missing.

- templates/serverpod_templates/projectname_server/deploy/gcp/console_gcr/cloud-run-deploy.sh
- templates/serverpod_templates/projectname_server/gcloudignore
- tools/serverpod_cli/lib/src/create/create.dart
> feat: Adds deployment script for Google Cloud Run.

- .github/workflows/dart-tests.yaml
- tools/serverpod_cli/lib/src/internal_tools/analyze_pubspecs.dart
- util/run_tests_update_pubspecs
> test: Adds test for consistency of dependency versions.

- tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart
- tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart
- tools/serverpod_cli/lib/src/generator/types.dart
- util/pub_get_all
- util/run_tests_analyze
> chore: Fixes deprecated methods and adds tests for serverpod_cli

- modules/serverpod_auth/serverpod_auth_server/config/generator.yaml
- modules/serverpod_chat/serverpod_chat_server/config/generator.yaml
- templates/pubspecs/tools/serverpod_cli/pubspec.yaml
- templates/serverpod_templates/modulename_server/config/generator.yaml
- tests/serverpod_test_module/serverpod_test_module_server/config/generator.yaml
- tests/serverpod_test_server/config/generator.yaml
- tools/serverpod_cli/bin/serverpod_cli.dart
- tools/serverpod_cli/lib/src/config/config.dart
- tools/serverpod_cli/lib/src/util/locate_modules.dart
- tools/serverpod_cli/pubspec.yaml
> feat: CLI automatically detects modules without the need to modify the generator config file.

- examples/chat/chat_client/lib/src/protocol/client.dart
- modules/serverpod_auth/serverpod_auth_client/dartdoc_options.yaml
- modules/serverpod_auth/serverpod_auth_client/doc/endpoint.md
- modules/serverpod_auth/serverpod_auth_client/lib/src/protocol/client.dart
- modules/serverpod_chat/serverpod_chat_client/dartdoc_options.yaml
- modules/serverpod_chat/serverpod_chat_client/doc/endpoint.md
- modules/serverpod_chat/serverpod_chat_client/lib/src/protocol/client.dart
- packages/serverpod_service_client/lib/src/protocol/client.dart
- templates/serverpod_templates/modulename_client/dartdoc_options.yaml
- templates/serverpod_templates/modulename_client/doc/endpoint.md
- templates/serverpod_templates/modulename_client/lib/src/protocol/client.dart
- templates/serverpod_templates/projectname_client/dartdoc_options.yaml
- templates/serverpod_templates/projectname_client/doc/endpoint.md
- templates/serverpod_templates/projectname_client/lib/src/protocol/client.dart
- tests/serverpod_test_client/lib/src/protocol/client.dart
- tests/serverpod_test_module/serverpod_test_module_client/lib/src/protocol/client.dart
- tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart
- tools/serverpod_cli/lib/src/generator/dart/library_generator.dart
- Internal EndpointClass in the generated client made public to let dartdoc generate documentation
- Add {@category Endpoint} for endpoint classes
- Add dartdoc config files to all modules and templates to enable Topics in dart doc
> Dart doc code gen

- examples/auth_example/auth_example_flutter/lib/main.dart
- examples/auth_example/auth_example_flutter/lib/src/serverpod_client.dart
- examples/auth_example/auth_example_flutter/lib/src/widgets/account_page.dart
- examples/auth_example/auth_example_flutter/lib/src/widgets/sign_in_page.dart
- examples/auth_example/auth_example_server/lib/server.dart
- examples/auth_example/auth_example_server/pubspec.yaml
- Removes cyclic imports from the auth example flutter app and restructures the widgets in a folder
- Server side implementation of gmail with the help of mailer to show an example of sending an email
> Auth example improvement

- modules/serverpod_auth/serverpod_auth_apple_flutter/lib/src/signin_button.dart
- modules/serverpod_auth/serverpod_auth_google_flutter/lib/src/signin_button.dart
> Properly close sign in barrier when sign in is complete

- packages/serverpod/pubspec.yaml
- templates/pubspecs/packages/serverpod/pubspec.yaml
> fix: Removes screenshots from pubspec.

- packages/serverpod/lib/src/endpoints/insights.dart
- packages/serverpod/lib/src/generated/protocol.dart
- packages/serverpod/lib/src/generated/serverpod_sql_exception.dart
- packages/serverpod/lib/src/protocol/serverpod_sql_exception.yaml
- packages/serverpod_service_client/lib/src/protocol/protocol.dart
- packages/serverpod_service_client/lib/src/protocol/serverpod_sql_exception.dart
- tests/serverpod_test_server/test/migration_test_files/6/migrated_table.yaml
- tests/serverpod_test_server/test/migration_test_files/6/migrated_table_2.yaml
- tests/serverpod_test_server/test/migration_test_files/6/migrated_table_3.yaml
- tests/serverpod_test_server/test/migrations_test.dart
- tools/serverpod_cli/lib/src/database/extensions.dart
- Fixes broken SQL code on dropping parent relationships.
- Adds a couple of new database migration tests. 
- Adds ServerdpodSqlException for use in the Insights API.
> test: Fixes issues in migration and adds tests.

- .github/workflows/dart-tests.yaml
- util/run_tests_unit
> ci: run unit tests in actions

- util/pub_get_all
Updates the pub_get_all bash script to include all current tests and projects.
> chore: Add missing project to pub_get_all script

- tests/serverpod_test_client/lib/src/protocol/client.dart
- tests/serverpod_test_client/lib/src/protocol/module_datatype.dart
- tests/serverpod_test_client/lib/src/protocol/protocol.dart
- tests/serverpod_test_server/lib/src/endpoints/module_serialization.dart
- tests/serverpod_test_server/lib/src/generated/endpoints.dart
- tests/serverpod_test_server/lib/src/generated/module_datatype.dart
- tests/serverpod_test_server/lib/src/generated/protocol.dart
- tests/serverpod_test_server/lib/src/protocol/module_datatype.yaml
- tests/serverpod_test_server/test/module_test.dart
- Test to verify that using a module class in a protocol works to serialize and de-serialize.
> Testing module types

- tools/serverpod_cli/lib/src/analyzer/code_analysis_collector.dart
- tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart
- tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart
- tools/serverpod_cli/lib/src/analyzer/entities/validation/protocol_validator.dart
- tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart
- tools/serverpod_cli/lib/src/generator/code_generation_collector.dart
- tools/serverpod_cli/lib/src/language_server/language_server.dart
- tools/serverpod_cli/test/analyzer/entities/entity_analyzer/entity_types_test.dart
Severity level setting possibility to reported errors from the analyzer.
Closes: https://github.com/serverpod/serverpod/issues/1149
> fix: Add severity levels to reported errors in the analyzer.

- tools/serverpod_cli/bin/serverpod_cli.dart
- tools/serverpod_cli/lib/src/analyzer/code_analysis_collector.dart
- tools/serverpod_cli/lib/src/generator/generator.dart
- tools/serverpod_cli/lib/src/generator/generator_continuous.dart
Set a none 0 exit code if analyzer detected any errors during the code generation.
Closes: https://github.com/serverpod/serverpod/issues/1137
> fix: Set exit code to none 0 if generator found issues

- tools/serverpod_cli/bin/serverpod_cli.dart
- tools/serverpod_cli/lib/src/analyzer/code_analysis_collector.dart
- tools/serverpod_cli/lib/src/generator/code_generation_collector.dart
- tools/serverpod_cli/lib/src/logger/logger.dart
- tools/serverpod_cli/lib/src/logger/loggers/std_out_logger.dart
- tools/serverpod_cli/lib/src/serverpod_packages_version_check/serverpod_packages_version_check.dart
Report the severity level on found issues in protocol / endpoint files when printing them in the terminal.
Colorize the highlight to match the severity level.
With this PR the output now looks like this.
Note: this is an example, these errors are all reported as errors in the production code.
> feat: Report severity level of analyze errors in the terminal output.

- tests/serverpod_test_server/test/migrations_test.dart
- tools/serverpod_cli/bin/serverpod_cli.dart
- tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart
- tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart
- tools/serverpod_cli/lib/src/commands/create.dart
- tools/serverpod_cli/lib/src/commands/generate.dart
- tools/serverpod_cli/lib/src/commands/migrate.dart
- tools/serverpod_cli/lib/src/create/copier.dart
- tools/serverpod_cli/lib/src/create/create.dart
- tools/serverpod_cli/lib/src/generator/code_generator.dart
- tools/serverpod_cli/lib/src/generator/dart/code_generator_dart.dart
- tools/serverpod_cli/lib/src/generator/dart/entities_library_generator.dart
- tools/serverpod_cli/lib/src/generator/dart/library_generator.dart
- tools/serverpod_cli/lib/src/generator/generator.dart
- tools/serverpod_cli/lib/src/generator/generator_continuous.dart
- tools/serverpod_cli/lib/src/generator/generator_database_definition.dart
- tools/serverpod_cli/lib/src/generator/psql/legacy_pgsql_generator.dart
- tools/serverpod_cli/lib/src/logger/logger.dart
- tools/serverpod_cli/lib/src/logger/loggers/std_out_logger.dart
- tools/serverpod_cli/lib/src/migrations/generator.dart
- tools/serverpod_cli/lib/src/run/file_watcher.dart
- tools/serverpod_cli/lib/src/runner/serverpod_command_runner.dart
- tools/serverpod_cli/test/runner/serverpod_command_runner_test.dart
- tools/serverpod_vscode_extension/src/extension.ts
Issue: https://github.com/serverpod/serverpod/issues/1042
Now that we have a centralised logger that all logging is passed through we can control the verbosity of the CLI app through a simple configuration in the logger.
This PR adds two new global flags to determine log level:
- `-q`, `--quiet` is used to suppress all logging output.
- `-v`, `--verbose` is used to display additional logging information that can be good for debug purposes.
With this change we could now remove all explicit passing of a `verbose` flag and verbose checks spread across libraries in the project. Now we can always call `log.<log-level->(....)` and let the logger handle what should be logged.
We now let the args parsing take place before we do any actual work in the CLI. This allows us apply log level for all …
> feat: Add global --verbose and --quiet flags to control log level.

- .github/workflows/dart-tests.yaml
- tools/serverpod_cli/test/util/protocol_helper_test.dart
issue: https://github.com/serverpod/serverpod/issues/1205
Modifies our GitHub actions so that the unit test step is run on both Windows and Ubuntu.
Also fixes a platform related test issue.
> test: Run unit tests on windows

- packages/serverpod/lib/src/generated/message_log_entry.dart
- packages/serverpod/lib/src/generated/query_log_entry.dart
- packages/serverpod/lib/src/protocol/log_entry.yaml
- packages/serverpod/lib/src/protocol/message_log_entry.yaml
- packages/serverpod/lib/src/protocol/query_log_entry.yaml
- packages/serverpod_service_client/lib/src/protocol/message_log_entry.dart
- packages/serverpod_service_client/lib/src/protocol/query_log_entry.dart
- tests/serverpod_test_server/lib/src/protocol/object_with_parent.yaml
- tests/serverpod_test_server/lib/src/protocol/object_with_self_parent.yaml
- tests/serverpod_test_server/test/migration_test_files/4/migrated_table.yaml
- tests/serverpod_test_server/test/migration_test_files/6/migrated_table_3.yaml
Resolve deprecated warnings from protocol files.
> refactor: Fix deprecated usage in protocol files.

- tools/serverpod_cli/lib/src/analyzer/entities/definitions.dart
- tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart
- tools/serverpod_cli/lib/src/analyzer/entities/entity_parser/entity_parser.dart
- tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart
- tools/serverpod_cli/lib/src/database/create_definition.dart
- tools/serverpod_cli/lib/src/generator/psql/legacy_pgsql_generator.dart
- tools/serverpod_cli/lib/src/test_util/builders/serializable_entity_field_definition_builder.dart
- tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_validation_test.dart
- tools/serverpod_cli/test/analyzer/entities/entity_analyzer/relation_keyword_test.dart
- tools/serverpod_cli/test/analyzer/entities/entity_analyzer/relation_one_to_many_test.dart
Modify relation information to be contained in typed objects that can then be used in code generation and validation of protocol files.
> refactor: Relations managed with typed objects for entity definitions.

- tools/serverpod_cli/lib/src/analyzer/entities/entity_parser/entity_parser.dart
- tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart
- tools/serverpod_cli/test/analyzer/entities/entity_analyzer/relation_keyword_test.dart
Fixes a bug where we reported errors on json column as if they where used in a realtion.
> fix: Do not report errors on json columns without relations.

- tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart
- tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_validation_test.dart
Catches any errors reported by the yaml parser and reports them without crashing the validator.
Closes: https://github.com/serverpod/serverpod/issues/1263
> fix: Handle invalid yaml errors and report them to user.

- tests/serverpod_test_server/lib/src/generated/entities_with_relations/address.dart
- tests/serverpod_test_server/lib/src/generated/entities_with_relations/citizen.dart
- tests/serverpod_test_server/lib/src/generated/entities_with_relations/company.dart
- tests/serverpod_test_server/lib/src/generated/entities_with_relations/post.dart
- tests/serverpod_test_server/lib/src/generated/entities_with_relations/town.dart
- tools/serverpod_cli/lib/src/generator/dart/library_generators/entities_library_generator.dart
- tools/serverpod_cli/test/generator/dart/server_code_generator/class_field_test.dart
Makes all fields of the include class private.
Changes a variable in the generated class.
> fix: Make include class fields private.

- tests/docker/tests_cli/run-tests.sh
- tools/serverpod_cli/lib/src/commands/create.dart
- tools/serverpod_cli/lib/src/create/create.dart
In this PR:
- feat: Developer version of create command now creates a project referring to the local version of Serverpod.
- test: Runs dart analyzer when testing `serverpod create`.
> feat: Developer version of create command now creates a project referring to the local version of Serverpod.

- packages/serverpod/lib/src/database/migration_manager.dart
- packages/serverpod/lib/src/endpoints/insights.dart
- packages/serverpod/lib/src/generated/database/database_definition.dart
- packages/serverpod/lib/src/generated/protocol.dart
- packages/serverpod/lib/src/protocol/database/database_definition.yaml
- packages/serverpod/lib/src/server/serverpod.dart
- packages/serverpod_service_client/lib/src/protocol/database/database_definition.dart
- packages/serverpod_service_client/lib/src/protocol/protocol.dart
- tools/serverpod_cli/lib/src/create/create.dart
- tools/serverpod_cli/lib/src/create/database_setup.dart
- tools/serverpod_cli/lib/src/create/port_checker.dart
- tools/serverpod_cli/lib/src/migrations/generator.dart
- tools/serverpod_cli/lib/src/util/command_line_tools.dart
- Removes old code for setting up database.
- Creates an empty migration on `serverpod create`
- Runs Serverpod in maintenance mode to setup the initial database migration on `serverpod create`.
> feat: Installs default database migrations on serverpod create.

- modules/serverpod_auth/serverpod_auth_server/lib/src/business/users.dart
- packages/serverpod/lib/src/database/analyze.dart
- packages/serverpod/lib/src/database/bulk_data.dart
- packages/serverpod/lib/src/database/database.dart
- packages/serverpod/lib/src/database/database_connection.dart
- packages/serverpod/lib/src/database/migration_manager.dart
- packages/serverpod/lib/src/endpoints/insights.dart
- packages/serverpod/lib/src/server/health_check_manager.dart
- tests/serverpod_test_server/lib/src/endpoints/failed_calls.dart
Exposes the mappedResultQuery method for public consumption.
Closes: https://github.com/serverpod/serverpod/issues/1410
> feat: Expose mapped results query for public use.

- tools/serverpod_cli/lib/src/generator/dart/library_generators/entities_library_generator.dart
Misc cleanup task to separate the generation of fields and getters for the Table class.
This is to improve the readability of the code.
This PR depends on: https://github.com/serverpod/serverpod/pull/1425
> refactor: Separate fields and getters.

- packages/serverpod/lib/src/server/server.dart
- packages/serverpod/lib/src/server/serverpod.dart
- tests/serverpod_test_server/test_e2e/headers_test.dart
> docs: Cleans up dart doc comments regarding HTTP response headers.

- README.md
- packages/serverpod/LICENSE
- packages/serverpod/README.md
> chore: Updates the license to SSPL and updates the readme file.

- tools/serverpod_cli/test/generator/dart/server_code_generator/entity_class_test.dart
Makes the test case conditions more explicit.
https://github.com/serverpod/serverpod/issues/1257 was already covered by this test, the test just wasn't explicit about the pre-conditions.
Closes: https://github.com/serverpod/serverpod/issues/1257
None - pure test changes.
> test: Make test case conditions more explicit.

- packages/serverpod_shared/lib/src/service_key_manager.dart
Small update needed for Serverpod Insights.
> feat: Adds fromYaml constructor to ServerpodConfig.

- modules/serverpod_chat/serverpod_chat_server/lib/src/endpoints/chat_endpoint.dart
Kind of an important fix...
No tests, since this one-liner is a no-brainer.
> Add missing return statement to require authentication (fixes #1421)

- tools/serverpod_cli/lib/src/analyzer/entities/stateful_analyzer.dart
- tools/serverpod_cli/lib/src/generator/generator.dart
- Makes the interface of the analyzer a bit clearer by only returning valid entries.
> fix: Only return valid entries from analyzer.

- tests/docker/tests_e2e_migrations/Dockerfile-tests
- tools/serverpod_cli/lib/src/create/create.dart
- tools/serverpod_cli/lib/src/runner/serverpod_command_runner.dart
- tools/serverpod_cli/lib/src/util/command_line_tools.dart
- Uses version together with the command to check if the command exists.
This provides a more useful output if debug mode is turned on and reduces the prints in our CI tests.
> fix: Use version command to check if a command exists.

- packages/serverpod/lib/src/database/many_relation.dart
- Makes some field private that clutter the user interface of the method.
> fix: make fields private to clean up user interface.

- modules/serverpod_auth/serverpod_auth_client/lib/src/protocol/authentication_fail_reason.dart
- modules/serverpod_auth/serverpod_auth_client/lib/src/protocol/client.dart
- modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/auth.dart
- modules/serverpod_auth/serverpod_auth_firebase_flutter/lib/src/auth.dart
- modules/serverpod_auth/serverpod_auth_google_flutter/lib/src/auth.dart
- modules/serverpod_auth/serverpod_auth_server/generated/protocol.yaml
- modules/serverpod_auth/serverpod_auth_server/lib/src/business/users.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/admin_endpoint.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/apple_endpoint.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/email_endpoint.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/firebase_endpoint.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/google_endpoint.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/generated/authentication_fail_reason.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/generated/endpoints.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/generated/protocol.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/protocol/authentication_fail_reason.spy.yaml
Enforce blocking of users (fixes #746).
> Enforce user blocked status on login

- examples/chat/README.md
Add the correct password in the README
Closes: #1419 
> docs: Update README with correct db password of chat example.

- packages/serverpod_shared/lib/src/constants.dart
- tools/serverpod_cli/lib/src/create/create.dart
- tools/serverpod_cli/lib/src/create/database_setup.dart
- tools/serverpod_cli/lib/src/migrations/generator.dart
- Adds documentation about all exceptions creating a migration might throw.
- Adds better error messaging if creating a migration fails when creating a new project.
- Includes the migration creation process as part of the success reporting for creating a new project.
> fix: Exception handling for creating default migration.

- tests/serverpod_test_server/test_integration/database_operations/entity_relations/self/one_to_many/deleteWhere/where_every_test.dart
- tests/serverpod_test_server/test_integration/database_operations/entity_relations/self/one_to_many/find/where_every_test.dart
Flaky test that failed on main.
> test: Flaky integration tests stabalized.

- tools/serverpod_cli/lib/src/analyzer/dart/definition_analyzers/class_analyzer.dart
- tools/serverpod_cli/lib/src/analyzer/dart/definition_analyzers/method_analyzer.dart
- tools/serverpod_cli/lib/src/analyzer/dart/definition_analyzers/parameter_analyzer.dart
- tools/serverpod_cli/lib/src/analyzer/dart/definitions.dart
- tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart
- tools/serverpod_cli/lib/src/test_util/builders/parameter_definition_builder.dart
- tools/serverpod_cli/test/integration/analyzer/dart/endpoint_validation/endpoint_method_parameter_test.dart
- Refactors the code to make it simpler to understand where different type of analysis should be applied.
There already exists tests for this class validating that the functionality remains the same.
None
> refactor: Simplify the code in the endpoint analyzer.

- examples/auth_example/auth_example_server/README.md
- examples/chat/README.md
Adds info on how to setup the database password and connection to the auth example.
Adds info how to setup different clients to connect with different ips (android emulator, physical device, etc).
Closes: #544
> docs: Improve Readme of example project for different configurations.

- templates/serverpod_templates/projectname_server/lib/src/endpoints/example_endpoint.dart
- templates/serverpod_templates/projectname_server/lib/src/protocol/example.spy.yaml
We support `UuidValue` and `Duration`
> docs: Add supported types to the documentation comments.

- .github/workflows/dart-tests.yaml
- tools/serverpod_cli/lib/src/commands/generate.dart
- tools/serverpod_cli/lib/src/generator/generator.dart
- tools/serverpod_cli/lib/src/generator/generator_continuous.dart
- tools/serverpod_cli/test_e2e/LICENSE
- tools/serverpod_cli/test_e2e/README.md
- tools/serverpod_cli/test_e2e/analysis_options.yaml
- tools/serverpod_cli/test_e2e/lib/src/keyword_search_in_stream.dart
- tools/serverpod_cli/test_e2e/pubspec.yaml
- tools/serverpod_cli/test_e2e/test/generate_watch_test.dart
- util/pub_get_all
- Ensures that watch mode detects changes in endpoint files.
This PR depends on: https://github.com/serverpod/serverpod/pull/1653
Closes: https://github.com/serverpod/serverpod/issues/1274
None
> fix: Watch mode detects changes in endpoint files.

- tests/serverpod_test_server/lib/src/generated/model_types/object_with_serverpod_object.dart
- tests/serverpod_test_server/lib/src/generated/protocol.dart
- tests/serverpod_test_server/lib/src/model/model_types/object_with_serverpod_object.spy.yaml
- tests/serverpod_test_server/test/serialization_test.dart
- tools/serverpod_cli/lib/src/analyzer/models/stateful_analyzer.dart
- tools/serverpod_cli/lib/src/analyzer/models/validation/model_relations.dart
- tools/serverpod_cli/lib/src/analyzer/models/validation/restrictions.dart
- tools/serverpod_cli/lib/src/generator/types.dart
- tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/field/field_datatype_test.dart
- tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/modules/module_table_name_test.dart
- tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/relation/relation_keyword_test.dart
This PR depends on: #1680 and should be merged first.
Full type validation of fields in models on all primitive and other supported dart types, any other model types and any module and serverpod reference models.
Any type starting with `package:` or `project:` is not validated as I'm not sure if this is an intended functionality or not. We are parsing these types today so as not to break any past behavior this is left as is.
Explicit validation that the specified module exists, if not an error is given.
Explicit type error if `dynamic` is used as this is an unsupported type.
`List` and `Map` MUST define the generic part or else are not considered valid.
Generics on any other type are not allowed.
This PR also removes the validation of models from modules and will NOT run any error …
> feat: Add type validation to model fields.

- tools/serverpod_vscode_extension/README.md
Url was still not resolved correctly, set the correct path!
> docs: Put the correct url for gif animation in readme.

- CHANGELOG.md
- integrations/serverpod_cloud_storage_gcp/CHANGELOG.md
- integrations/serverpod_cloud_storage_s3/CHANGELOG.md
- modules/serverpod_auth/serverpod_auth_apple_flutter/CHANGELOG.md
- modules/serverpod_auth/serverpod_auth_client/CHANGELOG.md
- modules/serverpod_auth/serverpod_auth_email_flutter/CHANGELOG.md
- modules/serverpod_auth/serverpod_auth_firebase_flutter/CHANGELOG.md
- modules/serverpod_auth/serverpod_auth_google_flutter/CHANGELOG.md
- modules/serverpod_auth/serverpod_auth_server/CHANGELOG.md
- modules/serverpod_auth/serverpod_auth_shared_flutter/CHANGELOG.md
- modules/serverpod_chat/serverpod_chat_client/CHANGELOG.md
- modules/serverpod_chat/serverpod_chat_flutter/CHANGELOG.md
- modules/serverpod_chat/serverpod_chat_server/CHANGELOG.md
- packages/serverpod/CHANGELOG.md
- packages/serverpod_client/CHANGELOG.md
- packages/serverpod_flutter/CHANGELOG.md
- packages/serverpod_lints/CHANGELOG.md
- packages/serverpod_serialization/CHANGELOG.md
- packages/serverpod_service_client/CHANGELOG.md
- packages/serverpod_shared/CHANGELOG.md
- templates/serverpod_templates/CHANGELOG.md
- tests/serverpod_test_client/CHANGELOG.md
- tests/serverpod_test_module/serverpod_test_module_client/CHANGELOG.md
- tests/serverpod_test_module/serverpod_test_module_server/CHANGELOG.md
- tests/serverpod_test_server/CHANGELOG.md
- tools/serverpod_cli/CHANGELOG.md
Updates changelog for 1.2.0-rc.2
> chore: Updates changelog.

- packages/serverpod/lib/src/database/migrations/migration_manager.dart
- packages/serverpod/lib/src/database/migrations/repair_migrations.dart
- packages/serverpod/lib/src/server/serverpod.dart
- tools/serverpod_cli/lib/src/runner/serverpod_command_runner.dart
- if `--apply-migrations` flag is provided, Adds a print reporting how many migrations are applied or if we are already on the latest version.
- if `--apply-repair-migrations` flag is provided, Adds a print reporting if a database repair migration could be applied.
- Fixes an error that would show if the repair migration directory didn't exist.
None.
> fix: Prints when applying migrations.

- tools/serverpod_vscode_extension/package.json
- tools/serverpod_vscode_extension/src/extension.ts
Allow vscode plugin to function on windows.
> fix: Resolve LSP path on windows in VSCode plugin.

- tools/serverpod_cli/lib/src/create/create.dart
- Improved log message for `create` command
> fix: Improved log message for `create` command.

- tools/serverpod_vscode_extension/README.md
> docs: Rename protocol -> model

- modules/serverpod_auth/serverpod_auth_shared_flutter/pubspec.yaml
- templates/pubspecs/modules/serverpod_auth/serverpod_auth_shared_flutter/pubspec.yaml
- tests/serverpod_test_server/test_integration/database_operations/entity_relations/long_identifiers_test.dart
- Updates image_cropper dependency to 5.x.x.
Also fixes a flaky test issue.
Closes: #1749
Closes: #1693
None: Updates a dependency that doesn't change any of its APIs.
> chore: Update image_cropper to 5.x.x.

- packages/serverpod/test/database/columns/column_uuid_test.dart
- packages/serverpod_serialization/lib/src/serialization.dart
- packages/serverpod_serialization/pubspec.yaml
- packages/serverpod_serialization/test/copy_with_test.dart
- templates/pubspecs/packages/serverpod_serialization/pubspec.yaml
- templates/pubspecs/tools/serverpod_cli/pubspec.yaml
- tests/bootstrap_project/pubspec.yaml
- tests/serverpod_test_client/lib/src/protocol/client.dart
- tests/serverpod_test_client/lib/src/protocol/protocol.dart
- tests/serverpod_test_client/test/copy_with_mutable_test.dart
- tests/serverpod_test_server/lib/src/generated/endpoints.dart
- tests/serverpod_test_server/lib/src/generated/protocol.dart
- tests/serverpod_test_server/pubspec.yaml
- tests/serverpod_test_server/test/generated_methods/copy_with_mutable_test.dart
- tests/serverpod_test_server/test/serialization_legacy_test.dart
- tests/serverpod_test_server/test_e2e/column_operations_legacy/column_uuid_test.dart
- tests/serverpod_test_server/test_e2e/connection_test.dart
- tests/serverpod_test_server/test_e2e/database_operations/generated_operations/batch_interactions_generated_test.dart
- tests/serverpod_test_server/test_e2e/database_operations/generated_operations/batch_interactions_test.dart
- tests/serverpod_test_server/test_e2e/database_operations/generated_operations/general_interactions_test.dart
- tests/serverpod_test_server/test_integration/column_operations/column_uuid_test.dart
- tools/serverpod_cli/pubspec.yaml
- tools/serverpod_cli/test_e2e/pubspec.yaml
> chore: Updates uuid to latest version.

- tools/serverpod_vscode_extension/package.json
- tools/serverpod_vscode_extension/src/extension.ts
- Looks for "models" folder instead of "models" folder.
None.
> fix: Look for models folder instead of model folder.

- tests/bootstrap_project/pubspec.yaml
- Renames the specified name for the bootstrap test project to match the folder name.
> chore: Rename bootstrap project in pubspec to match folder.

- packages/serverpod/lib/src/relic/routes/static_directory.dart
- packages/serverpod/lib/src/server/server.dart
Issues related to : Fix: - #1689
> Fix: path parsing.

- tests/serverpod_test_client/lib/src/protocol/protocol.dart
- tests/serverpod_test_client/lib/src/protocol/scopes/scope_none_fields.dart
- tests/serverpod_test_server/lib/src/generated/protocol.dart
- tests/serverpod_test_server/lib/src/generated/scopes/scope_none_fields.dart
- tests/serverpod_test_server/lib/src/models/scopes/scope_none_fields.spy.yaml
- tests/serverpod_test_server/migrations/20240122104455162/definition.json
- tests/serverpod_test_server/migrations/20240122104455162/definition.sql
- tests/serverpod_test_server/migrations/20240122104455162/definition_project.json
- tests/serverpod_test_server/migrations/20240122104455162/migration.json
- tests/serverpod_test_server/migrations/20240122104455162/migration.sql
- tests/serverpod_test_server/migrations/migration_registry.txt
A scope none field class in the test project to make sure the code generation stays the same (regression check).
none
> test: Add class with scope none field. 

- templates/serverpod_templates/projectname_server/generated/tables.pgsql
Reintroduce the old postgres file for new projects with a comment referring to the migration system.
None
> fix: Reintroduce the old postgres file in the project template.

- packages/serverpod/lib/src/server/serverpod.dart
Call stop on health check manager.
> fix: Clean up health check manager on exit.

- examples/auth_example/auth_example_server/README.md
- packages/serverpod/lib/src/authentication/service_authentication.dart
- packages/serverpod/lib/src/server/serverpod.dart
- packages/serverpod_shared/lib/src/config.dart
- packages/serverpod_shared/lib/src/service_key_manager.dart
- tests/serverpod_test_server/config/passwords.yaml
- tests/serverpod_test_server/test_e2e/service_protocol_test.dart
- tests/serverpod_test_server/test_e2e_migrations/apply_repair_migration_test.dart
- tests/serverpod_test_server/test_e2e_migrations/create_repair_migration_test.dart
- tests/serverpod_test_server/test_e2e_migrations/migration_registry_test.dart
- tests/serverpod_test_server/test_e2e_migrations/migrations_roundtrip_test.dart
Additional requirements on the setup of insights, our defaults already match these.
None.
> fix: Add additional requirements to insights setup.

- .github/workflows/dart-tests.yaml
> ci: Runs tests on all stable branches.

- tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/field/field_parent_test.dart
> test: Align test with interface changes.

- tools/serverpod_cli/lib/src/util/model_helper.dart
- tools/serverpod_cli/test/integration/util/model_helper_test.dart
- tools/serverpod_cli/test/integration/util/test_assets/protocol_helper/nested_directory_server_project/test_server/lib/src/models/nested/folder/example.spy.yaml
Closes: https://github.com/serverpod/serverpod/issues/1878
> fix: Set the corret output path for generated files on windows.

- tools/serverpod_cli/lib/src/commands/language_server.dart
- tools/serverpod_cli/lib/src/runner/serverpod_command_runner.dart
- tools/serverpod_cli/test/runner/serverpod_command_runner_test.dart
- tools/serverpod_vscode_extension/package-lock.json
- tools/serverpod_vscode_extension/package.json
- tools/serverpod_vscode_extension/src/extension.ts
Same fix as [here](https://github.com/serverpod/serverpod/pull/1900) but targeting 1.2 branch.
Any specific naming convention that we use for PRs targeting a release branch?
> fix: Prevent vscode extension from crashing on startup.

- tools/serverpod_cli/lib/src/config/config.dart
Make the parsing of serverpod features automatically handle any new additions.
None
> refactor: Generalise feature parsing in config.

- tools/serverpod_cli/lib/src/config/config.dart
- tools/serverpod_cli/lib/src/util/directory.dart
> fix: Allow generate command in serverpod package project. (#1895)

- tools/serverpod_cli/lib/src/generator/types.dart
- tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/field/field_datatype_test.dart
Cherry-pick of PR https://github.com/serverpod/serverpod/pull/1948
> fix: Custom classes respect nullable configuration.

- packages/serverpod/pubspec.yaml
- templates/pubspecs/packages/serverpod/pubspec.yaml
Bump postgres to 1.6.4 to force this version.
Closes: https://github.com/serverpod/serverpod/issues/1924
None
> chore: Bump postgres lib to new minor version.

- .vaunt/config.yaml
> chore: Adds Vaunt achievements to repo.

- modules/serverpod_auth/serverpod_auth_client/lib/src/protocol/user_info.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/generated/user_info.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/models/user_info.spy.yaml
just a minor detail sorry for the trouble :)
> change spelling in comment

- tools/serverpod_cli/lib/src/logger/loggers/std_out_logger.dart
- tools/serverpod_cli/lib/src/runner/serverpod_command.dart
- tools/serverpod_cli/lib/src/runner/serverpod_command_runner.dart
Print fixes applied from this PR: https://github.com/serverpod/serverpod/pull/2034
None, only print fixes.
> fix: Misc developer experience print fixes.

- modules/serverpod_auth/serverpod_auth_server/lib/src/business/email_auth.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/business/password_hash.dart
- modules/serverpod_auth/serverpod_auth_server/test/password_hash/argon2id_password_hash_test.dart
- modules/serverpod_auth/serverpod_auth_server/test/password_hash/legacy_password_hash_test.dart
- modules/serverpod_auth/serverpod_auth_server/test/password_hash/legacy_to_argon2id_hash_test.dart
- tests/serverpod_test_server/test_integration/authentication/email_auth_provider_test.dart
Applies the same change to main: https://github.com/serverpod/serverpod/pull/2035
> fix: Add maxMigrationEntries option to the migration helper method.

- packages/serverpod_client/lib/src/serverpod_client_io.dart
- tests/serverpod_test_server/test_e2e/tsl_client_test.dart
> fix: Remove faulty certificate check.

- modules/serverpod_chat/serverpod_chat_server/lib/src/business/config.dart
- modules/serverpod_chat/serverpod_chat_server/lib/src/endpoints/chat_endpoint.dart
> feat: Adds callbacks when sending chat message in chat module.

- modules/serverpod_auth/serverpod_auth_server/lib/src/business/email_auth.dart
> fix: Improved Email authentication error messages

- modules/serverpod_auth/serverpod_auth_shared_flutter/pubspec.yaml
- modules/serverpod_chat/serverpod_chat_flutter/pubspec.yaml
- templates/pubspecs/modules/serverpod_auth/serverpod_auth_shared_flutter/pubspec.yaml
- templates/pubspecs/modules/serverpod_chat/serverpod_chat_flutter/pubspec.yaml
Same as: https://github.com/serverpod/serverpod/pull/2132 but targetting the stable 1.2 release branch.
None, this should be backwards-compatible. This is just a bugfix release.
https://github.com/miguelpruivo/flutter_file_picker/releases
> chore: Upgrade file picker stable 1.2

- modules/serverpod_auth/serverpod_auth_server/lib/src/business/email_auth.dart
Closes: https://github.com/serverpod/serverpod/issues/2051
https://github.com/serverpod/serverpod/pull/2134
> fix: Improved Email authentication error messages (Stable 1.2)

- tools/serverpod_cli/lib/src/runner/serverpod_command_runner.dart
- tools/serverpod_cli/test/integration/downloads/resource_manager_test.dart
Same as: https://github.com/serverpod/serverpod/pull/2173
None.
> fix: Misc serverpod fixes (Stable 1.2)

- tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart
- tools/serverpod_cli/test/generator/dart/server_code_generator/endpoints_test.dart
Same fix as here: https://github.com/serverpod/serverpod/pull/2177
None - simple bug fix.
> fix: Prevent generating empty endpoints variable when no endpoints are defined. (Stable 1.2)

- templates/serverpod_templates/projectname_server/Dockerfile
See: https://github.com/serverpod/serverpod/pull/2193
> fix: Docker template support x86. (#2193)

- util/pub_get_all
Replaces #2215, which had issues.
Replaces `dart pub upgrade` with `flutter pub upgrade` for flutter projects (to avoid errors).
> dart pub upgrade -> flutter pub upgrade (for flutter projects)

- examples/auth_example/auth_example_flutter/lib/src/widgets/account_page.dart
- modules/serverpod_auth/serverpod_auth_client/lib/src/protocol/email_password_reset.dart
- modules/serverpod_auth/serverpod_auth_client/lib/src/protocol/user_info.dart
- modules/serverpod_auth/serverpod_auth_client/lib/src/protocol/user_info_public.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/business/user_images.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/generated/email_password_reset.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/generated/protocol.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/generated/user_info.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/generated/user_info_public.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/models/email_password_reset.spy.yaml
- modules/serverpod_auth/serverpod_auth_server/lib/src/models/user_info.spy.yaml
- modules/serverpod_auth/serverpod_auth_server/lib/src/models/user_info_public.spy.yaml
- modules/serverpod_auth/serverpod_auth_server/migrations/20240516152014635/migration.json
- modules/serverpod_auth/serverpod_auth_server/migrations/20240520102713718/definition.json
- modules/serverpod_auth/serverpod_auth_server/migrations/20240520102713718/definition.sql
- modules/serverpod_auth/serverpod_auth_server/migrations/20240520102713718/definition_project.json
- modules/serverpod_auth/serverpod_auth_server/migrations/20240520102713718/migration.json
- modules/serverpod_auth/serverpod_auth_server/migrations/20240520102713718/migration.sql
- modules/serverpod_auth/serverpod_auth_server/migrations/migration_registry.txt
- modules/serverpod_auth/serverpod_auth_shared_flutter/lib/src/user_settings.dart
- tests/serverpod_test_server/migrations/20240520103319212/definition.json
- tests/serverpod_test_server/migrations/20240520103319212/definition.sql
- tests/serverpod_test_server/migrations/20240520103319212/definition_project.json
- tests/serverpod_test_server/migrations/20240520103319212/migration.json
- tests/serverpod_test_server/migrations/20240520103319212/migration.sql
- tests/serverpod_test_server/migrations/migration_registry.txt
Makes `userName` nullable in `UserInfo`.
Closes: https://github.com/serverpod/serverpod/issues/975
userName is nullable
> fix!: Make user name nullable in user info.

- packages/serverpod/lib/src/generated/log_settings.dart
- packages/serverpod/lib/src/generated/message_log_entry.dart
- packages/serverpod/lib/src/generated/query_log_entry.dart
- packages/serverpod/lib/src/generated/server_health_metric.dart
- packages/serverpod/lib/src/generated/session_log_entry.dart
- packages/serverpod_service_client/lib/src/protocol/log_settings.dart
- packages/serverpod_service_client/lib/src/protocol/message_log_entry.dart
- packages/serverpod_service_client/lib/src/protocol/query_log_entry.dart
- packages/serverpod_service_client/lib/src/protocol/server_health_metric.dart
- packages/serverpod_service_client/lib/src/protocol/session_log_entry.dart
- tests/serverpod_test_client/lib/src/protocol/nullability.dart
- tests/serverpod_test_client/lib/src/protocol/types.dart
- tests/serverpod_test_client/lib/src/protocol/types_list.dart
- tests/serverpod_test_client/lib/src/protocol/types_map.dart
- tests/serverpod_test_server/lib/src/generated/nullability.dart
- tests/serverpod_test_server/lib/src/generated/types.dart
- tests/serverpod_test_server/lib/src/generated/types_list.dart
- tests/serverpod_test_server/lib/src/generated/types_map.dart
- tests/serverpod_test_server/test/generated_methods/from_json_test.dart
- tools/serverpod_cli/lib/src/generator/dart/library_generators/util/class_generators_util.dart
> fix: jsonEncode is converting double to int when used in Web

- tests/serverpod_test_server/test_integration/database_operations/crud/update_test.dart
Correcting an implementation error in the test validating that ids are set with the update method.
None
> test: Correct test implementation of id check in db update.

- modules/serverpod_auth/serverpod_auth_apple_flutter/lib/src/signin_button.dart
- modules/serverpod_auth/serverpod_auth_firebase_flutter/lib/src/signin_button.dart
- modules/serverpod_auth/serverpod_auth_google_flutter/lib/src/signin_button.dart
Adding to sign in buttons customizable label & icon.
Issue: #731
None
> Add sign in customizable label & icon

- modules/serverpod_auth/serverpod_auth_server/lib/src/business/google_auth.dart
- modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/google_endpoint.dart
- modules/serverpod_auth/serverpod_auth_server/pubspec.yaml
- templates/pubspecs/modules/serverpod_auth/serverpod_auth_server/pubspec.yaml
> Google auth/upgrade

- packages/serverpod_flutter/lib/src/flutter_connectivity_monitor.dart
- packages/serverpod_flutter/pubspec.yaml
- templates/pubspecs/packages/serverpod_flutter/pubspec.yaml
> Connectivity Package Upgrade

- tests/serverpod_test_server/test_integration/database_operations/crud/delete_test.dart
Fixes a flaky test as a result from recent test refactorings.
> test: add awaits to fix flaky tests

- packages/serverpod/lib/src/database/adapters/postgres/database_connection.dart
- packages/serverpod/lib/src/server/log_manager/log_manager.dart
- packages/serverpod/lib/src/server/serverpod.dart
- packages/serverpod/lib/src/server/session.dart
- packages/serverpod/lib/src/server/websocket_request_handlers/endpoint_websocket_request_handler.dart
Refactor the logging decisions to be made inside the log manager instead of outside.
Related: https://github.com/serverpod/serverpod/issues/2450
Breaking internally annotated methods.
> refactor: Restructure log manager responsibility.

- .vaunt/config.yaml
> chore: Updates Vaunt achievements.

- packages/serverpod/lib/src/endpoints/insights.dart
Add orderBy to insights log endpoint
Remove unnecessary type casts.
none
> fix: Order logs by order id in insights endpoint.

- tests/serverpod_test_server/test_integration/logging/endpoint_logging_test.dart
Fixes flakiness in a test.
none
> test: Clear logs before running logging tests.

- .vaunt/config.yaml
> chore: Adds Dreamscape achievement.

- packages/serverpod/lib/src/database/adapters/postgres/database_connection.dart
- packages/serverpod/lib/src/server/log_manager/log_manager.dart
- packages/serverpod/lib/src/server/log_manager/log_settings.dart
- packages/serverpod/lib/src/server/log_manager/log_writer.dart
- packages/serverpod/lib/src/server/log_manager/session_log_cache.dart
- packages/serverpod/lib/src/server/session.dart
- packages/serverpod/lib/src/server/websocket_request_handlers/endpoint_websocket_request_handler.dart
- Moves logging related variables away from the log cache class into the log manager.
Related issue: https://github.com/serverpod/serverpod/issues/2450
> refactor: 

- packages/serverpod/lib/src/server/log_manager/log_manager.dart
- packages/serverpod/lib/src/server/log_manager/log_settings.dart
- packages/serverpod/lib/src/server/session.dart
Introduces `endpointName` and `methodName` on the base Session.
Related issue: https://github.com/serverpod/serverpod/issues/2450
> fix: Add methodName and endpointName to base session.

- packages/serverpod_client/lib/src/client_method_stream_manager.dart
- packages/serverpod_client/test/integration/method_stream_manager_connection_test.dart
Fixes an issue where the stream would not be closed if the output stream on the client stopped being listened to.
Relates to: #2338
None - simple bugfix.
> fix: Close method stream when output stream on client is not listened to anymore

- .github/workflows/dart-tests.yaml
- modules/serverpod_auth/serverpod_auth_apple_flutter/lib/src/signin_button.dart
- modules/serverpod_auth/serverpod_auth_apple_flutter/pubspec.yaml
- modules/serverpod_auth/serverpod_auth_email_flutter/pubspec.yaml
- modules/serverpod_auth/serverpod_auth_firebase_flutter/lib/src/auth.dart
- modules/serverpod_auth/serverpod_auth_firebase_flutter/lib/src/signin_button.dart
- modules/serverpod_auth/serverpod_auth_firebase_flutter/pubspec.yaml
- modules/serverpod_auth/serverpod_auth_server/pubspec.yaml
- modules/serverpod_chat/serverpod_chat_flutter/pubspec.yaml
- packages/serverpod_serialization/pubspec.yaml
- packages/serverpod_shared/pubspec.yaml
- templates/pubspecs/modules/serverpod_auth/serverpod_auth_apple_flutter/pubspec.yaml
- templates/pubspecs/modules/serverpod_auth/serverpod_auth_email_flutter/pubspec.yaml
- templates/pubspecs/modules/serverpod_auth/serverpod_auth_firebase_flutter/pubspec.yaml
- templates/pubspecs/modules/serverpod_auth/serverpod_auth_server/pubspec.yaml
- templates/pubspecs/modules/serverpod_chat/serverpod_chat_flutter/pubspec.yaml
- templates/pubspecs/packages/serverpod_serialization/pubspec.yaml
- templates/pubspecs/packages/serverpod_shared/pubspec.yaml
- templates/pubspecs/tests/bootstrap_project/pubspec.yaml
- templates/pubspecs/tests/serverpod_cli_e2e_test/pubspec.yaml
- templates/pubspecs/tests/serverpod_test_server/pubspec.yaml
- templates/pubspecs/tools/serverpod_cli/pubspec.yaml
- tests/bootstrap_project/pubspec.yaml
- tests/serverpod_cli_e2e_test/pubspec.yaml
- tests/serverpod_test_server/pubspec.yaml
- tools/serverpod_cli/pubspec.yaml
- util/pub_get_all
- util/run_tests_analyze
- c4be60c91c647b7e01a982d8e1cc1f31d9523888 `uuid` from `^4.0.0` to `^4.1.0`.
- Lowest version where "fromString" is defined.
- 875792db2386cbde5f66a0132029f3ac3fadfba6 `intl` '>=0.18.0 < 0.20.0' to `^0.19.0`
- Lowest version where "tryParseStrict" is defined.
- 7b03797e157162f69eb7247fdfe55628eb99dae3 `material_design_icons_flutter` from `">=6.0.0 < 7.0.0"` to `">=6.0.0 < 8.0.0"`.
- d25dd5b6a69bca2e68bc7b055af6ec34efd739c3 Changed to non const initializing icons to allow range.
- da15bbef077e940a17705b234da1fe0bfad2bb96 `email_validator` from  `^2.1.17` to `'>=2.1.17 <4.0.0'`
- 33903efd5f32a556b73732dd5dc5c171352bb645 `googleapis` from `^11.0.0` to `'>=11.0.0 <14.0.0'`.
- 3043e242c62d5a447b8f04739666d8bd08e2a853 `firebase_auth`
- 21df6e2c67497f3e5c247706aa467fbf6ba8f650 `firebase_core`
- …
> chore: Bump outdated depencies.

- tests/serverpod_test_client/lib/src/protocol/client.dart
- tests/serverpod_test_server/lib/src/endpoints/deprecation.dart
- tests/serverpod_test_server/lib/src/generated/endpoints.dart
- tests/serverpod_test_server/lib/src/generated/protocol.yaml
- tools/serverpod_cli/lib/src/analyzer/dart/definitions.dart
- tools/serverpod_cli/lib/src/analyzer/dart/endpoint_analyzers/endpoint_method_analyzer.dart
- tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart
- tools/serverpod_cli/lib/src/test_util/builders/annotation_definition_builder.dart
- tools/serverpod_cli/test/generator/dart/client_code_generator/client_test.dart
- tools/serverpod_cli/test/generator/dart/server_code_generator/endpoints_test.dart
- tools/serverpod_cli/test/integration/analyzer/dart/endpoint_validation/endpoint_method_test.dart
Added deprecated methods to serverpod_test project.
n/a
> test: Added deprecated methods to serverpod_test project.

- templates/serverpod_templates/github/workflows/deployment-aws.yml
- templates/serverpod_templates/projectname_server_upgrade/config/production.yaml
- templates/serverpod_templates/projectname_server_upgrade/config/staging.yaml
- templates/serverpod_templates/projectname_server_upgrade/deploy/aws/terraform/code-deploy.tf
- templates/serverpod_templates/projectname_server_upgrade/deploy/aws/terraform/init-script.sh
- templates/serverpod_templates/projectname_server_upgrade/deploy/aws/terraform/storage.tf
Have tried out the AWS deployment and encountered a few issues related to dart version and ACL Not Supported issues.
It also address that RDS request ssl by default, else the service will not start
closes: #2622
closes: #2620
closes: #2619
N/A
> fix: AWS deployment issues

- packages/serverpod/lib/src/server/server.dart
Fixed top error handling on server's request handler to ensure proper error boundary and returning 500 error code.
n/a
> fix: Fixed top error handling on server's request handler to ensure proper error boundary.

- modules/serverpod_auth/serverpod_auth_server/lib/src/business/google_auth.dart
> refactor: Validate serverside google_client_secret.json file and give descriptive error (auth_module)

- tests/serverpod_test_client/lib/src/custom_classes.dart
- tests/serverpod_test_client/lib/src/protocol/object_with_custom_class.dart
- tests/serverpod_test_client/lib/src/protocol/protocol.dart
- tests/serverpod_test_server/config/generator.yaml
- tests/serverpod_test_server/lib/src/custom_classes.dart
- tests/serverpod_test_server/lib/src/generated/object_with_custom_class.dart
- tests/serverpod_test_server/lib/src/generated/protocol.dart
- tests/serverpod_test_server/lib/src/models/object_with_custom_class.spy.yaml
- tools/serverpod_cli/lib/src/generator/dart/library_generators/util/class_generators_util.dart
- tools/serverpod_cli/test/generator/dart/client_code_generator/custom_class_test.dart
- tools/serverpod_cli/test/generator/dart/server_code_generator/custom_class_test.dart
> fix: Use dynamic type for fromJson parameter in custom class serialization

- tests/serverpod_test_server/lib/src/generated/object_field_persist.dart
- Somehow the generated code was not committed at somepoint, this should fix broken `main` branch
> fix: Commit generated code

- packages/serverpod_test/LICENSE
> chore: Adds missing LICENSE file.

- packages/serverpod_test/lib/src/with_serverpod.dart
- tests/serverpod_test_module/serverpod_test_module_server/test/integration/test_tools/serverpod_test_tools.dart
- tests/serverpod_test_server/dart_test.yaml
- tests/serverpod_test_server/test_integration/test_tools/serverpod_test_tools.dart
- tests/serverpod_test_server/test_integration/test_tools/test_tag_test/dummy_custom_tag_test.dart
- tests/serverpod_test_server/test_integration/test_tools/test_tag_test/dummy_default_tag_test.dart
- tests/serverpod_test_server/test_integration/test_tools/test_tag_test/test_tag_test.dart
- tools/serverpod_cli/lib/src/generator/dart/library_generators/server_test_tools_generator.dart
- tools/serverpod_cli/test/generator/dart/server_code_generator/test_tools_test.dart
Closes https://github.com/serverpod/serverpod/issues/2844.
Related to this docs PR: https://github.com/serverpod/serverpod_docs/pull/186.
- Adds a test tag to the `withServerpod` test group
- Adds an option to override it
> fix: Add integration test tag.

- packages/serverpod/lib/src/server/websocket_request_handlers/method_websocket_request_handler.dart
Added stream websocket close debug message.
n/a
> fix: Added stream websocket close debug message.

- packages/serverpod/lib/src/server/server.dart
- tests/serverpod_test_server/test_e2e/json_protocol_test.dart
> fix: Respond with 400 when throwing serializable exceptions.

- tests/bootstrap_project/lib/src/util.dart
- tests/bootstrap_project/test/module_test.dart
- tests/bootstrap_project/test/project_mini_test.dart
- tests/bootstrap_project/test/project_test.dart
One of the bootstrap tests failed in a tangent PR so I added some more print information to these tests to make them debuggable in the pipe.
None - simple test fixes.
> test: Improve debug print for bootstrap tests

- tools/serverpod_cli/lib/src/analyzer/models/stateful_analyzer.dart
Removes redundant separation and management of list of models.
None - tests should assert that the functionality is the same as before.
> refactor: Refactor model state management in analyzer

- packages/serverpod/lib/src/server/websocket_request_handlers/helpers/method_stream_manager.dart
In a cloud environment, streams sometimes seem to drop the last packages of a stream.
A guess is that this is caused by a data race between the subscription cancel call and the `onData` processing.
This fix mitigates the risk of that data race by introducing a last message that is sent through the stream to ensure that the buffer has been completely processed before cancel is called.
The message is passed as an error to circumvent branching in the "hot path" of the stream.
All the awaits have also been removed from the `listen` callback. This ensures that a new message is not processed before all methods have been called, ensuring that the subscription is canceled correctly if required.
Out tests caught this last edge-case by calling an endpoint that threw an exception. Because of the …
> fix: Introduce end of stream message to close stream gracefully.

- .github/workflows/dart-tests.yaml
Bump to latest flutter version in CI.
None - simple bump
> chore: Bump CI to latest flutter version.

- packages/serverpod/lib/src/server/serverpod.dart
This reverts commit 0120e776e1af205233f1276960a1cea6f3ddb81e.
> revert: "feat: Support for SERVERPOD_DEPLOY_TAGS (#3063)"

- tools/serverpod_cli/lib/src/analyzer/models/entity_dependency_resolver.dart
- tools/serverpod_cli/lib/src/analyzer/models/validation/restrictions.dart
- tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/inheritance_test.dart
This PR closes the issue #3093, where the problem is described in detail.
Closes: #3093
No breaking changes, only the fix for a case not covered on the tests.
> fix: [Inheritance] Failing to create an index on an inherited field

- packages/serverpod/lib/src/relic/web_server.dart
> fix: Do not leak internal exception message for web routes

- modules/serverpod_auth/serverpod_auth_server/analysis_options.yaml
- packages/serverpod/analysis_options.yaml
- packages/serverpod_client/analysis_options.yaml
- packages/serverpod_lints/lib/internal.yaml
- packages/serverpod_lints/lib/public.yaml
- packages/serverpod_lints/lib/public_flutter.yaml
- packages/serverpod_serialization/analysis_options.yaml
- packages/serverpod_service_client/analysis_options.yaml
- packages/serverpod_shared/analysis_options.yaml
- packages/serverpod_test/analysis_options.yaml
- tools/serverpod_cli/analysis_options.yaml
Relates to: #1146 
This PR simply configures our wanted linter rules but does not fix any linter issues.
The fixes for the linter issues will be fixed in subsequent PRs.
Maybe - These are simple lint changes but this might require action from downstream users.
> chore: Update Serverpod shared lints.

- packages/serverpod_serialization/lib/src/serialization.dart
- tests/serverpod_test_client/lib/src/protocol/client.dart
- tests/serverpod_test_client/lib/src/protocol/protocol.dart
- tests/serverpod_test_server/lib/src/endpoints/record_parameters.dart
- tests/serverpod_test_server/lib/src/endpoints/test_tools.dart
- tests/serverpod_test_server/lib/src/generated/endpoints.dart
- tests/serverpod_test_server/lib/src/generated/protocol.dart
- tests/serverpod_test_server/lib/src/generated/protocol.yaml
- tests/serverpod_test_server/test/serialization_test.dart
- tests/serverpod_test_server/test_e2e/record_types_test.dart
- tests/serverpod_test_server/test_integration/test_tools/return_and_input_types_test.dart
- tests/serverpod_test_server/test_integration/test_tools/serverpod_test_tools.dart
- tools/serverpod_cli/lib/src/generator/dart/library_generators/class_generators/repository_classes.dart
- tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart
- tools/serverpod_cli/lib/src/generator/dart/library_generators/model_library_generator.dart
- tools/serverpod_cli/lib/src/generator/dart/library_generators/server_test_tools_generator.dart
- tools/serverpod_cli/lib/src/generator/keywords.dart
- tools/serverpod_cli/lib/src/generator/types.dart
- tools/serverpod_cli/test/generator/types_test.dart
- tools/serverpod_cli/test/integration/analyzer/dart/endpoint_validation/endpoint_method_test.dart
> feat: Support `Record` types for endpoint return value and parameters.

- tests/serverpod_test_server/lib/src/generated/endpoints.dart
To fix import conflicts after merge of 2 changes to the same file
> chore: Fix import conflict.

- tests/serverpod_test_client/lib/src/protocol/protocol.dart
- tests/serverpod_test_client/lib/src/protocol/record.dart
- tests/serverpod_test_server/lib/src/generated/protocol.dart
- tests/serverpod_test_server/lib/src/generated/record.dart
- tests/serverpod_test_server/lib/src/models/record.spy.yaml
- tools/serverpod_cli/lib/src/analyzer/models/validation/restrictions.dart
- tools/serverpod_cli/lib/src/generator/keywords.dart
- tools/serverpod_cli/lib/src/generator/types.dart
- tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/model_types_test.dart
- tools/serverpod_cli/test/generator/types_test.dart
- tools/serverpod_cli/test/test_util/builders/type_definition_builder.dart
So models can still use this name
Fixes #3330
> fix: Do not reserve the model name "Record"

- modules/serverpod_auth/serverpod_auth_shared_flutter/pubspec.yaml
- modules/serverpod_chat/serverpod_chat_flutter/pubspec.yaml
- templates/pubspecs/modules/serverpod_auth/serverpod_auth_shared_flutter/pubspec.yaml
- templates/pubspecs/modules/serverpod_chat/serverpod_chat_flutter/pubspec.yaml
Widens the `file_picker` dependency range to allow the latest major version.
We are not using any of the features changed in the latest major version.
The latest version has these changes:
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/miguelpruivo/flutter_file_picker/blob/master/CHANGELOG.md">file_picker's changelog</a>.</em></p>
<blockquote>
<h2>10.0.0</h2>
<h3>General</h3>
<ul>
<li><strong>BREAKING CHANGE:</strong> The <code>compressionQuality</code> property in the <code>pickFiles</code> method now defaults to <code>0</code>.</li>
<li><strong>BREAKING CHANGE:</strong> The <code>allowCompression</code> property has been deprecated in favor of <code>compressionQuality</code>, and now defaults to <code>false</code>.</li>
</ul>
<h3>Android</h3>
<ul> …
> chore: Bump file_picker dependency.

- tools/serverpod_cli/lib/src/config/config.dart
- tools/serverpod_cli/lib/src/language_server/language_server.dart
- tools/serverpod_cli/lib/src/util/locate_modules.dart
This PR is done in preparation for fixing #3377.
It seems like the world around `locate_modules` changed without updating the method.
This made part of the internal logic redundant.
I broke this out into a clear refactor PR so that these changes could be viewed in isolation.
None - These changes are not indented to be breaking.
> refactor: Refactor locate modules logic.

- tests/serverpod_test_server/test_integration/shutdown_test.dart
Related to: https://github.com/serverpod/serverpod/issues/3431
> test: Disable flaky shutdown test.

- .github/workflows/dart-tests.yaml
Ensure web unit tests are run with wasm as well
None
> ci: Run web unit tests with wasm as well as js

- templates/serverpod_templates/projectname_server_upgrade/config/development.yaml
- templates/serverpod_templates/projectname_server_upgrade/config/production.yaml
- templates/serverpod_templates/projectname_server_upgrade/config/staging.yaml
- templates/serverpod_templates/projectname_server_upgrade/config/test.yaml
Adds commented-out future call configuration to templates.
This helps show what configuration options are available.
> chore: Add commented out future call configuration to templates.

- modules/new_serverpod_auth/serverpod_auth_profile/serverpod_auth_profile_server/test/integration/user_profiles_test.dart
so test code runs sequentially
> fix(auth2): Add missing `await` to `UserProfiles` tests

- templates/pubspecs/tools/serverpod_cli/pubspec.yaml
- tools/serverpod_cli/pubspec.yaml
Bumps version of CLI tools to latest.
None - we don't use the part that was breaking in the last release.
> chore: Bump cli tools version

- templates/serverpod_templates/projectname_flutter/lib/main.dart
- templates/serverpod_templates/projectname_server/analysis_options.yaml
- templates/serverpod_templates/projectname_server/lib/server.dart
- templates/serverpod_templates/projectname_server/lib/src/greeting_endpoint.dart
- templates/serverpod_templates/projectname_server/test/integration/greeting_endpoint_test.dart
- templates/serverpod_templates/projectname_server_upgrade/lib/server.dart
- templates/serverpod_templates/projectname_server_upgrade/lib/src/birthday_reminder.dart
- templates/serverpod_templates/projectname_server_upgrade/lib/src/web/widgets/built_with_serverpod_page.dart
Adds 
- unawaited_futures
- avoid_print
And formats the comments to 80 characters
> feat: Add lints to template and formats to 80 chars

- tests/serverpod_test_client/lib/src/protocol/protocol.dart
- tests/serverpod_test_client/lib/src/protocol/subfolder/model_in_subfolder.dart
- tests/serverpod_test_client/lib/src/protocol/types_list.dart
- tests/serverpod_test_server/lib/src/generated/protocol.dart
- tests/serverpod_test_server/lib/src/generated/subfolder/model_in_subfolder.dart
- tests/serverpod_test_server/lib/src/generated/types_list.dart
- tests/serverpod_test_server/lib/src/models/subfolder/model_in_subfolder.spy.yaml
- tests/serverpod_test_server/lib/src/models/types_list.spy.yaml
- tools/serverpod_cli/lib/src/generator/dart/library_generators/util/class_generators_util.dart
- tools/serverpod_cli/lib/src/generator/types.dart
By forwarding `subDirParts` parameter for types used in records
Closes #3737
> fix(codegen): Fix code generation for type definitions from other folders

- modules/new_serverpod_auth/serverpod_auth_email/serverpod_auth_email_server/lib/src/business/auth_email.dart
So that it can be better integrated into and combined with application code, resulting in the possibility of rolling back an entire stack of modifications
> feat(auth2): Take `transaction` parameter in all methods on the `AuthEmail` business logic class

- tests/bootstrap_project/test/module_test.dart
- tests/bootstrap_project/test/project_mini_test.dart
- tests/bootstrap_project/test/project_test.dart
- tests/docker/tests_e2e_migrations/run-tests.sh
- tests/serverpod_cli_e2e_test/test/generate_watch_test.dart
Fixes #3987.
Also apply the same fix to other scripts and tests that activate the CLI.
N/A.
> test: Fix verbose logging on tests that require the CLI

- modules/new_serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/pubspec.yaml
- modules/serverpod_auth/serverpod_auth_server/pubspec.yaml
- templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/pubspec.yaml
- templates/pubspecs/modules/serverpod_auth/serverpod_auth_server/pubspec.yaml
Widens the dependency range for googleapis.
None of the breaking changes are used by our code, which allows us to widen the range.
None - simple dependency bump.
> chore: Bump googleapis
