serverpod/serverpod

README.md
When I'm following the documentation, I encounter this error 
```
Error on line 3, column 7: Mapping values are not allowed here. Did you miss a colon earlier?
```
I think because we need to add fields after the table.
=> Add field on documentation when create table from yaml file

tools/serverpod_cli/bin/create/create.dart, tools/serverpod_cli/bin/generator/class_generator.dart
Currently traditional Windows command prompt cannot run Flutter create due to paths being hard constructed in the CLI tool.
=> Use platform path separator over hard coded values

packages/serverpod/lib/src/server/health_check_manager.dart, packages/serverpod/lib/src/server/serverpod.dart
Added missing call to initialize SystemResources class. This is due to a recent change found here https://github.com/jonasroussel/system_resources/commit/e66d68ab228228be108712f4e0e3eb99fe9345c7
I found myself running into an error related to health check, complaining that it needs to be initialized. This happened to me after I fixed another issue first: https://github.com/serverpod/serverpod/issues/271
=> Initialize SystemResources before making use of .cpuLoadAvg()

packages/serverpod/example/example_server/lib/src/future_calls/example_future_call.dart, templates/serverpod_templates/projectname_server/lib/src/future_calls/example_future_call.dart
As per issue https://github.com/serverpod/serverpod/issues/286, The sample comment given in the example_future_call.dart file to access the future function in the endpoint was given wrong, so I changed it.
https://github.com/serverpod/serverpod/issues/286
_No breaking changes were made_
=> fix: issue 286 fixed, changed the comment given in example future call

templates/serverpod_templates/projectname_server/lib/src/protocol/example_class.yaml
I used github.dev, so the PR template wasn't automatically used. The change I've made is as trivial as they get though, so I don't see the need to add more information.
=> fix: Description of supported types for generated classes; float -> double

tests/serverpod_test_client/lib/src/protocol/object_field_scopes.dart, tests/serverpod_test_client/lib/src/protocol/object_with_bytedata.dart, tests/serverpod_test_client/lib/src/protocol/object_with_duration.dart, tests/serverpod_test_client/lib/src/protocol/object_with_enum.dart, tests/serverpod_test_client/lib/src/protocol/object_with_object.dart, tests/serverpod_test_client/lib/src/protocol/simple_data.dart, tests/serverpod_test_client/lib/src/protocol/test_enum.dart, tests/serverpod_test_client/lib/src/protocol/types.dart, tests/serverpod_test_server/lib/src/generated/object_field_scopes.dart, tests/serverpod_test_server/lib/src/generated/object_with_bytedata.dart, tests/serverpod_test_server/lib/src/generated/object_with_duration.dart, tests/serverpod_test_server/lib/src/generated/object_with_enum.dart, tests/serverpod_test_server/lib/src/generated/object_with_object.dart, tests/serverpod_test_server/lib/src/generated/simple_data.dart, tests/serverpod_test_server/lib/src/generated/test_enum.dart, tests/serverpod_test_server/lib/src/generated/types.dart, tests/serverpod_test_server/lib/src/protocol/simple_data.yaml, tests/serverpod_test_server/lib/src/protocol/test_enum.yaml, tools/serverpod_cli/bin/generator/class_analyzer.dart, tools/serverpod_cli/bin/generator/class_generator_dart.dart, tools/serverpod_cli/bin/generator/protocol_definition.dart, tools/serverpod_cli/bin/generator/types.dart, tools/serverpod_cli/bin/util/extensions.dart, tools/serverpod_cli/bin/util/yaml_docs.dart
This PR allows documenting generated files in the protocol yaml files.
Examples:
```yaml
class: Foo
fields:
foo: int
###
bar: String
```
```yaml
enum: Foo
values:
- foo
- bar
```
The number of spaces in front of `###` is important.
(For enum values the doccumentation has to start two columns before the value name starts.)
Closes #548 
Not breaking.
=> feat: allow docs in protocol files

tools/serverpod_cli/bin/generator/types.dart
Fixes a small oversight by me. (Imports of generics in sub-directories are not calculated properly.)
Fix #622 
Fix #545 
*None*
=> fix: Fix import of generics in subdirectories

tools/serverpod_cli/bin/generator/class_analyzer.dart
The subdirectory has not been passed to the `EnumDefinition`.
Fix #628 
*none*
=> fix: Generated enums don't respect their subdirectories

modules/serverpod_auth/serverpod_auth_firebase_flutter/lib/src/auth.dart, modules/serverpod_auth/serverpod_auth_firebase_flutter/lib/src/signin_button.dart, modules/serverpod_auth/serverpod_auth_firebase_flutter/pubspec.yaml, templates/pubspecs/modules/serverpod_auth/serverpod_auth_firebase_flutter/pubspec.yaml
Migrated the serverpod_auth_firebase_flutter from FlutterFire UI to firebase_ui_auth.
SignInWithFirebase need now `List<AuthProvider> authProviders` instead of `  required List<ProviderConfiguration> providerConfigs`.
=> Migrated auth_firebase_flutter from FlutterFire UI to firebase_ui_auth

modules/serverpod_auth/serverpod_auth_google_flutter/lib/src/auth.dart
Don't show a stacktrace when Google sign-in disconnect fails (#735). Doesn't fix the issue of disconnect failing, just makes the console output look less critical.
=> Don't print stacktrace when Google signin disconnect fails

modules/serverpod_auth/serverpod_auth_shared_flutter/lib/src/session_manager.dart
Return bool from `SessionManager.initialize()` (address part of #764, but does not fix the whole issue).
=> Return bool from `SessionManager.initialize()`

tools/serverpod_cli/lib/src/database/create_definition.dart, tools/serverpod_cli/lib/src/generator/dart/library_generator.dart
*This PR is part of the long term goal of supporting database migrations (#154).*
This PR creates a new function called `createDatabaseDefinitionFromEntities` that can be used to generate the target `DatabaseDefinition` on the fly based on a supplied list of `SerializableEntityDefinition`.
**It does not add the tables from modules or the `package:serverpod` automatically.**
*none*
=> feat: Allow creating the `DatabaseDefinition` on the fly

tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart
This PR is part of the long term goal of supporting database migrations (#154).
The `recover` was not set. This resulted in an assert failing when running it in debug mode.
*none*
=> fix: Add missing recover option while parsing yaml documents

tests/serverpod_test_client/lib/src/protocol/object_with_self_parent.dart, tests/serverpod_test_client/lib/src/protocol/protocol.dart, tests/serverpod_test_server/generated/tables.pgsql, tests/serverpod_test_server/lib/src/generated/object_with_self_parent.dart, tests/serverpod_test_server/lib/src/generated/protocol.dart, tests/serverpod_test_server/lib/src/protocol/object_with_self_parent.yaml, tools/serverpod_cli/lib/src/generator/psql/pgsql_generator.dart
Say I define a self-referencing table, like this:
```yaml
class: MyTable
table: my_table
fields:
parentId: int?, parent=my_table
someData: String
```
Running `serverpod generate` hangs forever. I traced it to an endless loop in the `_sortClassInfos` function in `pgsql_generator.dart`. It seems that it gets stuck when it tries to move the self-referenced table below itself as a dependency, and this occurs repeatedly in an endless loop.
This PR fixes this issue by:
When looping through the table fields in `_sortClassInfos` and checking if a parent is not above the current table, also adds a check that the parent is not the same table as the current table.
#807 
If you need help, consider asking for advice on the …
=> Prevent self referencing table endless loop in serverpod generate

templates/serverpod_templates/modulename_server/config/generator.yaml
This PR is basically a chore that lowercases `MODULENAME_client` to `modulename_client` in the `templates/serverpod_templates/modulename_server/config/generator.yaml` template so that the modulename gets updated by `serverpod create`, and so that `serverpod generate` can subsequently find the client folder.
Fixes #821 
=> lowercase modulename_client in module generator template

modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/signin_button.dart
- onFailure callback removed from SignInWithEmailButton as it was not implemented
onFailure callback removed, it was not implemented and was none functional, if this was used by anyone, they had dead code that can safely be deleted without any additional effect.
=> fix: remove onFailure from email auth module (dead code)

modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/signin_dialog.dart
- Displays "Email is already in use" error if you are trying to create an account with an email that already exists.
- Rests all errors when the user clicks any buttons, such as "create account", "reset password", "login" etc.
=> fix: Add error message if email is already in use

packages/serverpod_serialization/lib/src/exceptions.dart, packages/serverpod_serialization/lib/src/serialization.dart, tests/docker/tests_single_server/run-tests.sh, tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_server/lib/src/endpoints/exception_test_endpoint.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/test/exception_test.dart
Throwing generated exceptions ended up as SerializeableExceptions rather than the type they were supposed to be. This PR removes the SerializeableExceptions from parsing of primitive datatypes which caused this issue. 
This means you are no longer allowed to throw a SerializableException on its own, instead, you have to extend the class, which is exactly what the code generator does already. To reflect this limitation the SerializableException class was changed to be an abstract class.
The exception tests were not running in CI either, this PR adds these tests to the CI pipeline.
Fixes: #913
=> Exception bug with modules

templates/pubspecs/tools/serverpod_cli/pubspec.yaml, tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart, tools/serverpod_cli/pubspec.yaml
The analyzer package was updated with a new type: `InvalidType` this PR implements support for this when checking the return type of endpoint methods. 
This PR also changes the behaviour of the parsing somewhat as it will **NOT** include any methods that does not meet the requirements for endpoint methods. Requirements here meaning the return types are following the required synax, e.g. Must be a Future, Must be a superset of InterfaceType, Must be a Valid type. 
A type can be for example be invalid if it was not defined or imported to the endpoint file.
https://github.com/serverpod/serverpod/issues/963 …
=> fix: handle invalid return types when parsing endpoint methods

tools/serverpod_cli/bin/serverpod_cli.dart, tools/serverpod_cli/lib/src/util/string_validators.dart
Validates that tag names for database migrations are valid.
=> fix: Correctly validates tag names for database migrations.

packages/serverpod/lib/src/database/migration_manager.dart, packages/serverpod/lib/src/endpoints/insights.dart, packages/serverpod/lib/src/generated/database/database_definition.dart, packages/serverpod/lib/src/generated/protocol.dart, packages/serverpod/lib/src/protocol/database/database_definition.yaml, packages/serverpod/lib/src/server/serverpod.dart, packages/serverpod_service_client/lib/src/protocol/database/database_definition.dart, packages/serverpod_service_client/lib/src/protocol/protocol.dart, tests/serverpod_test_server/test/migrations_test.dart, tools/serverpod_cli/bin/serverpod_cli.dart, tools/serverpod_cli/lib/src/config_info/config_info.dart, tools/serverpod_cli/lib/src/database/extensions.dart, tools/serverpod_cli/lib/src/database/migration.dart, tools/serverpod_cli/lib/src/migrations/generator.dart
This PR adds a repair option to the `serverpod migrate` command.
Example usage:
`serverpod migrate --repair --mode production`
The command will connect to the insights server and retrieve the structure of the database. The structure is compared with what is expected from the most up-to-date migrations (including modules). If the database is out of sync, the command will output the SQL queries required to synchronize the database with the latest migration. If any destructive changes are detected, warnings will be written and the `--force` option will need to be added to output the SQL code.
_If you have done any breaking changes, make sure to outline them here, so …
=> feat: Adds migrate --repair command to CLI.

packages/serverpod/lib/src/server/session.dart
This PR adds a URL bulk lookup method method to avoid server roundtrips when a long list of file URLs must be looked up. It uses `Future.wait()` to wait on a list of `Future`s for maximum concurrency.
=> Add bulk file URL lookup method

.gitignore, templates/pubspecs/tools/serverpod_cli/pubspec.yaml, tools/serverpod_cli/bin/serverpod_cli.dart, tools/serverpod_cli/lib/src/language_server/language_server.dart, tools/serverpod_cli/lib/src/language_server/wireformat.dart, tools/serverpod_cli/pubspec.yaml, tools/serverpod_vscode_extension/.eslintrc.json, tools/serverpod_vscode_extension/.gitignore, tools/serverpod_vscode_extension/.vscode/extensions.json, tools/serverpod_vscode_extension/.vscode/launch.json, tools/serverpod_vscode_extension/.vscode/settings.json, tools/serverpod_vscode_extension/.vscode/tasks.json, tools/serverpod_vscode_extension/.vscodeignore, tools/serverpod_vscode_extension/CHANGELOG.md, tools/serverpod_vscode_extension/README.md, tools/serverpod_vscode_extension/package-lock.json, tools/serverpod_vscode_extension/package.json, tools/serverpod_vscode_extension/src/extension.ts, tools/serverpod_vscode_extension/tsconfig.json
* Scaffolding for the VSCode extension project.
* Introduction for the command `serverpod language-server` command to start the LSP server for linting.
This PR introduces the first project setup / integration of a linter with an LSP protocol. It also adds the vscode extension that is intended to use this server. The server is simply initialized in the client but is not doing anything else, the linting features will be added in a new PR.
The client itself should not need to be updated very much unless we want to add other features aside from the language server stuff.
=> Add vs code plugin

tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart, tools/serverpod_cli/lib/src/util/string_validators.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/entity_properties_test.dart
- Allow class names such as `ServerpodSQLException` to be used in the protocol files.
- Change the error message from "CamelCaseString" to "PascalCaseString" to more accurately reflect the string type.
Closes: https://github.com/serverpod/serverpod/issues/965
=> fix: allow multiple uppercase chars in a class name in the protocol.

tools/serverpod_cli/bin/serverpod_cli.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer_test.dart
- Only allow 'class' OR 'exception' OR 'enum' in protocol files.
- Renable --stdio flag for language server as is required by the client.
=> Protocol property rules for entities

tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/indexes_properties_test.dart
Tests for the index definitions in the protocol analyzer.
Slight modification to the error messages for the indexs.
=> test: add tests for the index fields of the protocol analyzer

templates/pubspecs/tools/serverpod_cli/pubspec.yaml, tools/serverpod_cli/bin/serverpod_cli.dart, tools/serverpod_cli/lib/src/serverpod_packages_version_check/serverpod_packages_version_check.dart, tools/serverpod_cli/pubspec.yaml, tools/serverpod_cli/test/serverpod_packages_version_check/serverpod_packages_version_check_test.dart, tools/serverpod_cli/test/serverpod_packages_version_check/test_assets/approximate_1.1.0/pubspec.yaml, tools/serverpod_cli/test/serverpod_packages_version_check/test_assets/explicit_1.1.0/pubspec.yaml
Adds a new step to the generate process that validates that the current version of the CLI is compatible with the Serverpod packages specified in the pubspec files.
- Prints a warnings if a the version for the package is defined using an approximate version (for example "^").
- Prints a warning if the version of the package is not compatible with the running version of the Cli. 
=> Fix:  Validate serverpod packages and cli version before generating project

tools/serverpod_cli/lib/src/analyzer/entities/definitions.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/class_conflicts_test.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_validation_test.dart
- Two pass validation of protocol files.
- Validate that class names do not have collisions (exists in more than 1 file)
=> feat: add dual pass parsing to validation of protocol files

tools/serverpod_cli/bin/serverpod_cli.dart, tools/serverpod_cli/lib/src/serverpod_packages_version_check/serverpod_packages_version_check.dart, tools/serverpod_cli/test/serverpod_packages_version_check/serverpod_packages_version_check_test.dart, tools/serverpod_cli/test/serverpod_packages_version_check/test_assets/corrupted_pubspec/pubspec.yaml
Fix for: https://github.com/serverpod/serverpod/issues/1072
With a recent addition we now parse and warn if Serverpod packages are incompatible with the running Serverpod Cli.
This check wrongly aborted and exited the Serverpod Cli if a pub spec file could not be parsed.
This PR silences irrelevant errors and only validates valid pubspec files.
=> fix: Silence pubspec open or parse errors when checking cli and serverpod packages compatibility

tools/serverpod_cli/lib/src/analyzer/entities/validation/protocol_validator.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/validate_node.dart
Refactors the error collection logic to be centralized to a single file in the validator.
=> refactor: centralize error collection logic

tools/serverpod_cli/test/serverpod_packages_version_check/serverpod_packages_version_check_test.dart, util/run_tests_unit
Because the script for triggering the unit tests utilised a loop, the return value from the tests were not propagated back to the process that started it. This caused Github to report all tests passed even if tests failed.
This PR:
- Returns exit code 1 if any of the tests in the loop fail.
- Fixes a failing test - The test was missing test assets.
=> Fix: Fix unit test runner

tools/serverpod_cli/lib/src/analyzer/entities/converter/converter.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_parser/enetity_parser.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_parser/entity_parser.dart, tools/serverpod_cli/lib/src/analyzer/entities/stateful_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/protocol_validator.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/lib/src/analyzer/entities/yaml_definitions/class_yaml_definition.dart, tools/serverpod_cli/lib/src/analyzer/entities/yaml_definitions/enum_yaml_definition.dart, tools/serverpod_cli/lib/src/analyzer/entities/yaml_definitions/exception_yaml_definition.dart, tools/serverpod_cli/lib/src/language_server/language_server.dart, tools/serverpod_cli/lib/src/util/protocol_helper.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/class_conflicts_test.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/documentation_test.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/entity_types_test.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/enum_values_test.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/extra_properties_test.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_validation_test.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/indexes_properties_test.dart, tools/serverpod_cli/test/analyzer/entities/stateful_analyzer/stateful_analyzer_test.dart, tools/serverpod_cli/test/util/protocol_helper_test.dart
Modifies the analyzer to do the serializing and validation in two steps. The benefits is that we can completely omit the first validation and collection of errors which saves us a lot of compute. This refactor also clears up a re-validation issue in the language server where we in some cases wouldn't re-parse a protocol file when it was necessary. 
This PR is dependent on #1075 being merged first.
Closes: https://github.com/serverpod/serverpod/issues/1077
=> Refactor analyzer parts

tools/serverpod_cli/lib/src/analyzer/entities/stateful_analyzer.dart, tools/serverpod_cli/lib/src/language_server/language_server.dart, tools/serverpod_cli/test/analyzer/entities/stateful_analyzer/stateful_analyzer_test.dart
Modifies the logic of the StatefulAnalyzer to be simpler and easier to work with. This in turns also made it possible to make the language server have a cleaner architecture.
- Unnecessary tests due to above modifications
This PR is dependent on https://github.com/serverpod/serverpod/pull/1083.
=> Refactors structure of language server and simplifies the code.

tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/indexes_properties_test.dart
#Fix
Only allow the index types in the protocol to be one of: 'btree', 'hash', 'gin', 'gist', 'spgist', 'brin'.
Closes: https://github.com/serverpod/serverpod/issues/1089
Depends on: https://github.com/serverpod/serverpod/pull/1083
=> fix: Enforce index type to be one of the valid pgsql types.

tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_validation_test.dart
Changes the protocol validation to give an error if a field named `id` is present at the same time as a class has a table defined.
Closes: https://github.com/serverpod/serverpod/issues/1088
Depends on: https://github.com/serverpod/serverpod/pull/1083
=> fix: Do not allow the id field to be used for classes that has a table defined.

tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/entity_relations.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart
A new object to keep track of relationships and collisions of keywords in protocol files. The goal is to make it easier to implement additional checks that depends on other protocol files. Right now instantiating this object means we have an n-squared time complexity, I want to move the instantiation of it to the outside so we only have to do it once for each full pass. However to do that I have to change the function declaration and with that break all tests, therefor ill complete that step in a subsequent PR.
=> fix: Add an entity relation resolver to the analyzer

tools/serverpod_cli/lib/src/util/string_validators.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_validation_test.dart
Previously we reported errors for datatypes referencing a module.
I.E:
```yaml
class: Example
fields:
user: module:auth:UserInfo
```
This PR removes this error.
=> fix: Do not report errors for module datatypes in fields.

tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_validation_test.dart
Validates that the referenced parent table exists in this OR another protocol class, if not reports an error.
Example:
```yaml
class: Example
table: example
fields:
parentId: int, parent=unknown_parent
```
Will report an error for `unknown_parent`.
Closese: https://github.com/serverpod/serverpod/issues/1085
=> fix: Report an error if the referenced parent table does not exist.

tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/extra_properties_test.dart
Restrict table names to be globally unique across all project protocol files. 
Example:
```yaml
class: Example
table: example
fields:
name: String
class: Example2
table: example
fields:
name: String
```
The above example will give an error in both files on the table name `example`.
Closes: https://github.com/serverpod/serverpod/issues/1087
=> fix: Report an error if the table name in a class is not globally unique.

modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/signin_button.dart
Corrects wrong wording in a comment for the `maxPasswordLength` in `siginin_button.dart`.
Fixes this Issue: #1102
=> Fix typo in signin_button.dart

tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/indexes_properties_test.dart
Reports an error if the index name in a class protocol is not globally unique.
Example:
```yaml
class: Example
table: example
fields:
name: String
indexes:
example_index:
fields: name
class: example2
table: example2
fields:
name: String
indexes:
example_index:
fields: name
```
Then an error that the index name "example_index" is used multiple times is generated.
Closes: #1082
=> fix: Report an error if an index name is not globally unique.

tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart
Resolve crash when using serverpod generate from relative folder in VSCode debug launcher.
Closes: https://github.com/serverpod/serverpod/issues/1130
=> fix: Convert relative path to absolute, resolve crash in vscode debugger.

tools/serverpod_cli/lib/src/analyzer/entities/converter/converter.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/protocol_validator.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_source_location_test.dart
Extracts the exact subspan for each key/value pair in the fields comma separated string. This means that we can specify the exact part of the string that caused an error instead of reporting an error on the entire string.
With this PR the errors are reported like this:
Previously:
Closese: https://github.com/serverpod/serverpod/issues/1115
=> fix: Parse the source location for all comma seperated values in field string.

tools/serverpod_cli/lib/src/internal_tools/analyze_pubspecs.dart, tools/serverpod_cli/lib/src/serverpod_packages_version_check/serverpod_packages_version_check.dart, tools/serverpod_cli/lib/src/util/pubspec_helpers.dart, tools/serverpod_cli/test/serverpod_packages_version_check/serverpod_packages_version_check_test.dart, tools/serverpod_cli/test/serverpod_packages_version_check/test_assets/vendor/serverpod/pubspec.yaml, tools/serverpod_cli/test/util/pubspec_helpers_test.dart
Issue: https://github.com/serverpod/serverpod/issues/1079
Excludes any Serverpod or vendor folder that is placed next to the Serverpod server folder from the Serverpod package version check.
=> fix: Exclude Serverpod when placed in vendor folder from serverpod package version check

modules/serverpod_auth/serverpod_auth_google_flutter/lib/src/auth.dart, modules/serverpod_auth/serverpod_auth_google_flutter/lib/src/google/sign_in_with_google_mobile.dart
Generate a refresh token for every Google sign-in, by forcing a user to re-consent to access rules each time they sign in. This is required because without a valid refresh token, the Google dart libraries throw an assertion error (https://github.com/google/googleapis.dart/issues/487).
Fixes #754.
=> Require consent in order to generate refresh token on every signin

tools/serverpod_cli/lib/src/analyzer/entities/converter/converter.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/entity_types_test.dart
Restricts the class name to not be able to use the values 'List', 'Map', 'String' and 'DateTime'.
Closes: https://github.com/serverpod/serverpod/issues/1159
=> fix: Restrict class names to not allow standard datatypes.

tools/serverpod_cli/lib/src/analyzer/entities/validation/protocol_validator.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/validate_node.dart
Ability to tag keys as deprecated in for the protocol and automatically give warnings / errors if usage is detected.
Closes: https://github.com/serverpod/serverpod/issues/1160
=> fix: Add automatic deprecated reporting of keys in analyzer.

modules/serverpod_auth/serverpod_auth_firebase_flutter/lib/src/auth.dart, tools/serverpod_cli/lib/src/analyzer/entities/converter/converter.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_parser/entity_parser.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/protocol_validator.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/validate_node.dart, tools/serverpod_cli/lib/src/analyzer/entities/yaml_definitions/class_yaml_definition.dart, tools/serverpod_cli/lib/src/analyzer/entities/yaml_definitions/exception_yaml_definition.dart
Allow us to toggle if there should be an implicit key in stringified nodes when parsing protocol files. The use-case is to allow for stringified nodes without an implicit key which we will need when implementing the `relation` key.
=> fix: Add ability to toggle implicit key in stringified nodes.

tools/serverpod_cli/lib/src/analyzer/entities/converter/converter.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_parser/entity_parser.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/keywords.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/protocol_validator.dart, tools/serverpod_cli/lib/src/analyzer/entities/yaml_definitions/class_yaml_definition.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_source_location_test.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_validation_test.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/relation_keyword_test.dart
* Adds `relation` keyword for protocol
* Deprecate `parent` keyword for protocol
Previous syntax:
```yaml
class: Example
table: example
fields:
parentId: id, parent=parent_table
```
New syntax:
```yaml
class: Example
table: example
fields:
parentId: id, relation(parent=parent_table)
```
This PR is the first iteration of the `relation` keyword, and with this change only supports the old behavior.
Closese: https://github.com/serverpod/serverpod/issues/1144
=> feat: Introduce relation keyword, deprecate parent keyword.

tools/serverpod_cli/lib/src/analyzer/entities/converter/converter.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_validation_test.dart
Allow whitespace around =. 
Example:
```yaml
class: Example
table: example
fields:
parentId: int, parent = parent_table
```
Closes: https://github.com/serverpod/serverpod/issues/1177
=> fix: Allow whitespace around "=" in protocol.

util/generate_all, util/publish_all, util/run_tests_update_pubspecs, util/update_pubspecs
Make `generate_all` use the git version of `serverpod_cli`, not the `pub` version. May help with #1076.
=> Use git version of serverpod_cli

tools/serverpod_cli/lib/src/analyzer/entities/definitions.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_parser/entity_parser.dart
Remove the yaml string content from extracted entities. Reason for this is to not pass things forward that will be unused in the code generator, this simplifies the interface and makes it much more intuitive/cleaner to write tests for. I.E. we do not have to define a yaml structure in tests where they would otherwise not be used.
=> refactor: Remove polluting variable from extracted entities.

tools/serverpod_cli/lib/src/internal_tools/analyze_pubspecs.dart, tools/serverpod_cli/lib/src/util/latest_cli_version.dart, tools/serverpod_cli/lib/src/util/pub_api_client.dart, tools/serverpod_cli/test/util/latest_cli_version_test.dart, tools/serverpod_cli/test/util/pub_api_client_test.dart
issue: https://github.com/serverpod/serverpod/issues/611
- Pub API Client - The CLI shared client to get the latest version package version from pub.dev.
After introducing the update prompt I noticed that we already used a package to fetch the latest version from pub.dev. This is a cleanup PR that consolidates our way of fetching the package.
After this PR we are ready to close the issue.
=> fix: Introduce Pub API Client to consolidate our pub.dev interactions

packages/serverpod/lib/src/database/bulk_data.dart, packages/serverpod/lib/src/database/extensions.dart, packages/serverpod/lib/src/endpoints/insights.dart, packages/serverpod/lib/src/generated/database/bulk_data.dart, packages/serverpod/lib/src/generated/database/bulk_data_exception.dart, packages/serverpod/lib/src/generated/database/filter/filter.dart, packages/serverpod/lib/src/generated/database/filter/filter_constraint.dart, packages/serverpod/lib/src/generated/database/filter/filter_constraint_type.dart, packages/serverpod/lib/src/generated/endpoints.dart, packages/serverpod/lib/src/generated/protocol.dart, packages/serverpod/lib/src/protocol/database/bulk_data.yaml, packages/serverpod/lib/src/protocol/database/bulk_data_exception.yaml, packages/serverpod/lib/src/protocol/database/filter/filter.yaml, packages/serverpod/lib/src/protocol/database/filter/filter_constraint.yaml, packages/serverpod/lib/src/protocol/database/filter/filter_constraint_type.yaml, packages/serverpod_service_client/lib/src/protocol/client.dart, packages/serverpod_service_client/lib/src/protocol/database/bulk_data.dart, packages/serverpod_service_client/lib/src/protocol/database/bulk_data_exception.dart, packages/serverpod_service_client/lib/src/protocol/database/filter/filter.dart, packages/serverpod_service_client/lib/src/protocol/database/filter/filter_constraint.dart, packages/serverpod_service_client/lib/src/protocol/database/filter/filter_constraint_type.dart, packages/serverpod_service_client/lib/src/protocol/protocol.dart
This adds improved fetching of bulk data for Serverpod Insights.
- Support for filters.
- Better error checks.
- Doesn't fetch binary data (instead just number of bytes).
It's still work in progress, so no tests yet. The code only affects Insights though, so should be safe.
=> feat: Support for filtering bulk data fetched from Serverpod Insights.

tools/serverpod_cli/bin/serverpod_cli.dart, tools/serverpod_cli/lib/src/commands/create.dart, tools/serverpod_cli/lib/src/logger/logger.dart, tools/serverpod_cli/lib/src/runner/serverpod_command_runner.dart, tools/serverpod_cli/test/runner/serverpod_command_runner_test.dart
issue: https://github.com/serverpod/serverpod/issues/1042
When playing around with the logger and build runner I noticed two important issues.
The logger was accessed before it was initialized because the terminal line width is determined on initialization for the command runner.
This was fixed by initializing the logger before we build the command runner and use the flag passed by the user to only set the logger debug level.
The logic for parsing the argument for the create command could try and access a value through null. Implemented correct parsing logic now, based on the same feature in [flutter](https://github.com/flutter/flutter/blob/48f08e3db23f14e41051d672ed3da1bc65caa87d/packages/flutter_tools/lib/src/commands/create_base.dart#L182).
We now correctly inform the user if `create` …
=> fix: Command runner related fixes

tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_validation_test.dart
Add validation for deeply nested datatypes in protocols.
Example:
```yaml
class: Example
fields:
data: Map<String, invalid-type>
```
Now reports an error on `invalid-type` where none was detected before.
=> fix: Correctly validate deeply nested datatypes in protocols.

tools/serverpod_cli/lib/src/analyzer/entities/validation/protocol_validator.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/validate_node.dart, tools/serverpod_cli/lib/src/analyzer/entities/yaml_definitions/class_yaml_definition.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/relation_keyword_test.dart
Validate that the current class has a table if the relation key is in use.
example that will give an error:
```yaml
class: Example
fields:
parentId: int, relation(parent=parent_table)
```
=> fix: Validate that a table is defined  on a class with a relation.

tools/serverpod_vscode_extension/language-configuration.json, tools/serverpod_vscode_extension/package.json, tools/serverpod_vscode_extension/syntaxes/serverpod.tmLanguage.json
Syntax highlighting of protocol files with the vscode plugin, the file extension is required to be `.sp.yaml` to work. There has to be a file extension toggle for this to work, and we don't want to override other yaml stylings. Hence this file extension.
=> feat: Syntax highlighting in protocol files.

tools/serverpod_cli/lib/src/create/create.dart, tools/serverpod_cli/lib/src/logger/loggers/std_out_logger.dart, tools/serverpod_cli/lib/src/util/ansi_style.dart
issue: https://github.com/serverpod/serverpod/issues/1042
Colors the prefixes for Error, Warning and Debug messages so that they are easier to spot.
Word wrap didn't calculate the correct width of the line. This fixes that and ensures that any trimmable characters in the beginning of a line are preserved.
None
=> feat: Colored Error, Warning and Debug prefix.

tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/lib/src/util/string_validators.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/enum_values_test.dart
Changes the allowed enum values to match the linting rules in dart.
Closes: https://github.com/serverpod/serverpod/issues/1128
=> fix: Enum value restrictions matches default linting in dart.

tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/lib/src/util/string_validators.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_validation_test.dart
Field name restrictions in protocol files match the default restrictions in dart. Similar too the enum values in https://github.com/serverpod/serverpod/issues/1128.
=> fix: Less restrictive naming of class fields.

tools/serverpod_cli/lib/src/test_util/builders/enum_definition_builder.dart, tools/serverpod_cli/test/generator/dart/client_generator_dart/enum_field_test.dart, tools/serverpod_cli/test/generator/dart/client_generator_dart/expected_files_created_test.dart, tools/serverpod_cli/test/generator/dart/client_generator_dart/static_comment_test.dart, tools/serverpod_cli/test/generator/dart/client_generator_dart/unsupported_entity_test.dart, tools/serverpod_cli/test/generator/dart/server_generator.dart/enum_field_test.dart, tools/serverpod_cli/test/generator/dart/server_generator.dart/expected_files_created_test.dart, tools/serverpod_cli/test/generator/dart/server_generator.dart/static_comment_test.dart, tools/serverpod_cli/test/generator/dart/server_generator.dart/unsupported_entity_test.dart
issue: https://github.com/serverpod/serverpod/issues/1151
Adds tests for the enum dart code generator for the client and server code.
Adds tests that validates that an exception is thrown if an unsupported entity type is passed in.
=> test: Add tests for enum dart code generator

tools/serverpod_cli/lib/src/analyzer/entities/stateful_analyzer.dart, tools/serverpod_cli/lib/src/generator/generator.dart
Needs https://github.com/serverpod/serverpod/pull/1219 to function.
Crashes on invalid protocol files fixed by ignoring protocol files that have errors.
Resolves: https://github.com/serverpod/serverpod/issues/1164
=> fix: Do not generate code from broken protocol files.

tools/serverpod_cli/lib/src/analyzer/entities/definitions.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_parser/entity_parser.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/lib/src/database/create_definition.dart, tools/serverpod_cli/lib/src/generator/psql/legacy_pgsql_generator.dart, tools/serverpod_cli/lib/src/test_util/builders/serializable_entity_field_definition_builder.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_validation_test.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/relation_keyword_test.dart
Renaming relation object and pointer reference variable in our entity definitions.
=> refactor: Rename internal relation representation.

tools/serverpod_cli/lib/analyzer.dart, tools/serverpod_cli/lib/src/analyzer/entities/converter/converter.dart, tools/serverpod_cli/lib/src/analyzer/entities/definitions.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_parser/entity_parser.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/keywords.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/protocol_validator.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/lib/src/analyzer/entities/yaml_definitions/class_yaml_definition.dart, tools/serverpod_cli/lib/src/analyzer/entities/yaml_definitions/enum_yaml_definition.dart, tools/serverpod_cli/lib/src/analyzer/entities/yaml_definitions/exception_yaml_definition.dart, tools/serverpod_cli/lib/src/generator/psql/legacy_pgsql_generator.dart, tools/serverpod_cli/lib/src/test_util/builders/class_definition_builder.dart, tools/serverpod_cli/lib/src/test_util/builders/serializable_entity_field_definition_builder.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/extra_properties_test.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_persist_test.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_scope_test.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_validation_test.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/indexes_properties_test.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/relation_keyword_test.dart, tools/serverpod_vscode_extension/syntaxes/serverpod.tmLanguage.json
- New keyword `scope` can have value of `all` or `serverOnly` (case-insensitive), defaults to `all`
- New keyword `persist` can have value of true or false, default is true if a table is defined, false otherwise (invalid use if table is not defined).
- New support for operator `!` in field keys in the protocol, can be used on keys without a value to inverse the implicit boolean value. 
- Old keyword `api` mapped to `!persist`
- Old keyword `database` mapped to `scope=serverOnly`
- VScode plugin to support highlighting of inverted keywords e.g. `!persist`
- Internal models consistently built from the new data.
Closes: https://github.com/serverpod/serverpod/issues/1142
- Code generator is only retrofitted to previous functionality, new combination such as `scope=serverOnly, !persist` is not …
=> feat: Add scope and persist keywords to protocol.

tools/serverpod_cli/lib/src/create/create.dart
Stumbled upon this when working on other stuff.
None.
=> fix: Fix typo in create start instructions.

tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/lib/src/analyzer/entities/yaml_definitions/class_yaml_definition.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_persist_test.dart
Make the `persist` key mutually exclusive with `relation` and `parent` keywords. Gives a hint that `persist` key is redundant to set to true on fields (on a class with a table).
=> fix: Restrict persist key from being use on relations.

tools/serverpod_cli/lib/src/analyzer/entities/definitions.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/field_scope_test.dart, tools/serverpod_cli/test/generator/dart/client_code_generator/class_field_test.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/class_field_test.dart
Closes: https://github.com/serverpod/serverpod/issues/1281
Introduces scope "none" a long side "all" and "serverOnly".
The scope makes a field not available on the server or the client.
This will be used to create implicit fields in one to many relationships: https://github.com/serverpod/serverpod/issues/1239
=> feat: Introduce scope "none".

packages/serverpod/lib/src/generated/protocol.dart, tests/serverpod_test_server/lib/src/generated/protocol.dart, tests/serverpod_test_server/test/service_protocol_test.dart, tools/serverpod_cli/lib/src/analyzer/entities/definitions.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_parser/entity_parser.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/keywords.dart, tools/serverpod_cli/lib/src/analyzer/entities/yaml_definitions/class_yaml_definition.dart, tools/serverpod_cli/lib/src/database/create_definition.dart, tools/serverpod_cli/lib/src/database/extensions.dart, tools/serverpod_cli/lib/src/test_util/builders/class_definition_builder.dart, tools/serverpod_cli/lib/src/test_util/builders/foreign_relation_definition_builder.dart, tools/serverpod_cli/lib/src/test_util/builders/serializable_entity_field_definition_builder.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/relation_database_action_test.dart, tools/serverpod_cli/test/database/create_definition/database_action_definition_test.dart, tools/serverpod_cli/test/database/extentions/pgsql_code_generation_test.dart, tools/serverpod_cli/test/generator/dart/server_generator.dart/generateProtocol/circular_relation_test.dart
- New keyword `onDelete` in protocol, can have values `SetNull`, `SetDefault`, `Cascade`, `NoAction`, `Restrict`. Default to `Cascade` (previous behavior).
- New keyword `onUpdate` in protocol, can have values `SetNull`, `SetDefault`, `Cascade`, `NoAction`, `Restrict`. Default to `NoAction` (previous behavior).
Example:
```yaml
class: Example
table: example
fields:
parent: Example, relation(onUpdate=Cascade, onDelete=SetNull)
```
Closes: https://github.com/serverpod/serverpod/issues/1148
I set up the initial test structure for the database code generation, but there was some strange things regarding variables that we will have to take a look at. We should probably extract this code  into distinct modules to make it easier to test.
Since we do not support a default value yet `SetDefault` …
=> feat: Add onDelete and onUpdate bindings in protocol.

tools/serverpod_cli/lib/src/analyzer/entities/definitions.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_parser/entity_parser.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/keywords.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/lib/src/analyzer/entities/yaml_definitions/class_yaml_definition.dart, tools/serverpod_cli/lib/src/test_util/builders/class_definition_builder.dart, tools/serverpod_cli/lib/src/test_util/builders/foreign_relation_definition_builder.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/relation_keyword_test.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/relation_manual_field_test.dart, tools/serverpod_cli/test/analyzer/entities/entity_analyzer/relation_one_to_many_test.dart
- Adds the `field` keyword to be used on relations.
- `field` keyword cannot be used on list relations or id relations.
- The named field must exist in the class
- The field type must match the reference field type (I.E. be an int).
Closes: https://github.com/serverpod/serverpod/issues/1150
=> feat: Add ability to specify the relation field holding the id for object relations.

packages/serverpod/lib/src/database/database_query.dart, packages/serverpod/test/database/database_query_test.dart
Closes: https://github.com/serverpod/serverpod/issues/1312
Adds a more helpful error message if a "Where" or "OrderBy" column expression is built from another table than the one we are performing operations on.
``` dart
Citizen.find(
session,
where: (_) =>
Company.t.name.equals('Serverpod'),
);
```
Will give an exception with message: 
```
FormatException: Column references starting from other tables than "citizen" are not supported. The following expressions need to be removed or modified:
"where" expression referencing column company."name".
```
``` dart
Citizen.find(
session,
orderBy: Company.t.name,
);
```
Will give an exception with message: 
```
FormatException: Column references starting from other tables than "citizen" are not supported. The following expressions need to be …
```
=> fix: Add helpful error message if wrong table is used for Where or OrderBy expression.

tools/serverpod_cli/lib/src/generator/dart/library_generators/entities_library_generator.dart
Break out the entities library generator into functions that each is responsible for one thing.
This PR does not change the behavior of the class.
Further refactoring will be done later on but this helps understanding what parts are responsible for what in the generated classes.
None.
=> refactor: Break out entities library generator into functions.

tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart, tools/serverpod_cli/lib/src/generator/generator_database_definition.dart
Removes the old path for analyzing protocol files, now all usages utilize the `StatefulAnalyzer` that is well tested.
=> refactor: Remove legacy protocol analyzer.

tools/serverpod_cli/lib/src/analyzer/entities/definitions.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_dependency_resolver.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_parser/entity_parser.dart, tools/serverpod_cli/lib/src/test_util/builders/class_definition_builder.dart, tools/serverpod_cli/test/analyzer/entities/stateful_analyzer/protocol_validation/relation_keyword_test.dart, tools/serverpod_cli/test/analyzer/entities/stateful_analyzer/protocol_validation/relation_one_to_many_test.dart, tools/serverpod_cli/test/analyzer/entities/stateful_analyzer/protocol_validation/relation_one_to_one_test.dart
Adds nullability check for class definition relations from the analyzer. This feature is required for the code generation of relational operations.
=> feat: Add nullability information in internal protocol definitions.

packages/serverpod/lib/src/database/database_connection.dart, packages/serverpod_serialization/lib/src/serialization.dart
Moves `DateTime` and `Uint8List` management from our database layer into the deserialization logic making it work for any deeply nested objects.
Related: https://github.com/serverpod/serverpod/issues/1339
=> fix: Deep check of DateTime and Uint8Lists during deserialization.

tools/serverpod_cli/lib/src/commands/create.dart
Specific issue was an incorrect plural combined with `if` instead of `it` in the help for the `--force` flag.
Fixes #1394.
=> Fix typo in `CreateCommand`'s CLI help text

tools/serverpod_cli/lib/src/analyzer/entities/entity_dependency_resolver.dart, tools/serverpod_cli/test/analyzer/entities/stateful_analyzer/protocol_validation/relation_one_to_many_test.dart
Fixes a bug where the ordered of the protocol files mattered when resolving list relations.
Closes: https://github.com/serverpod/serverpod/issues/1397
=> fix: Resolve list relation regardless of order of protocol files.

packages/serverpod/lib/src/database/database_connection.dart, packages/serverpod/lib/src/database/database_connection_legacy.dart, packages/serverpod/lib/src/database/database_query.dart, packages/serverpod/lib/src/database/expressions.dart, packages/serverpod/test/database/database_query_test.dart, tests/serverpod_test_server/test/database_operations/entity_relations/sql_query_test.dart
Mixed improvements to QueryBuilder and one cleanup if Table.
- Remove `columns` parameter in table to remove dangerous dereference.
- QueryBuilder now takes in Table instead of table name.
- QueryBuilder now always selects explicit fields (removes use of `*`).
=> fix: Remove redundant Table variable and Query builder takes table as param.

packages/serverpod/lib/src/database/database_query.dart, packages/serverpod/test/database/database_query_test.dart
Stops developers from including multiple many relation orderings when querying database.
The reason is that we right now do a common join and then group for any many relation count ordering. This does not work when multiple many relation counts are included.
For that to work we probably need to implement subqueries that can then be used to order on.
Closes: 
=> fix: throw UnimplementedError when ordering by multiple many relations.

packages/serverpod/lib/src/database/database_query.dart, packages/serverpod/test/database/database_query_test.dart, tests/serverpod_test_server/test_integration/database_operations/entity_relations/entities_with_list_relations/order_by_test.dart
Given these entities: 
``` yaml
class: Person
table: person
fields:
name: String
organization: Organization?, relation(name=org_person, optional)
```
``` yaml
class: Organization
table: organization
fields:
name: String
people: List<Person>?, relation(name=org_person)
```
There was an issue when ordering by nested count queries like so:
``` dart
Person.db.find(
session,
// Order people by number of people in their organization with a name
// starting with 'a'
orderBy: Person.t.organization.people.count((p) => p.name.ilike('a%')),
orderDescending: true,
);
```
An issue occurred that named both the grouping and the joins incorrectly.
This PR fixes that issue.
Affects …
=> fix: Support Order by count in nested relation

packages/serverpod/lib/src/database/database_query.dart, packages/serverpod/test/database/database_query_test.dart
- Small code cleanup to remove the now redundant `_JoinContext` class.
- Move and improve error message for if unsupported count columns are used in delete queries.
None.
=> refactor: Remove redundant `_JoinContext`.

packages/serverpod_serialization/lib/src/serialization.dart
Explicitly null check DateTime on deserialization this will stop us from unnecessarily throwing exceptions.
Closes: #1469
=> fix: Deserialization of datetime handles null explicitly.

packages/serverpod/lib/src/database/columns.dart, packages/serverpod/lib/src/database/database_query.dart, packages/serverpod/lib/src/database/many_relation.dart, packages/serverpod/test/database/database_query/filter_on_any_test.dart, tests/serverpod_test_server/test_integration/database_operations/entity_relations/nested_one_to_many/count/where_any_test.dart, tests/serverpod_test_server/test_integration/database_operations/entity_relations/nested_one_to_many/find/where_any_test.dart, tests/serverpod_test_server/test_integration/database_operations/entity_relations/one_to_many/count/where_any_test.dart, tests/serverpod_test_server/test_integration/database_operations/entity_relations/one_to_many/find/where_any_test.dart
- Support for filtering on any for filtered or unfiltered many side in 1:n relations.
Given the following entities:
``` company.yaml
class: Company
table: company
fields:
name: String
employees: List<Citizen>?, relation
```
``` citizen.yaml
class: Citizen
table: citizen
fields:
name: String
```
> We can retrieve all companies that have any employee
``` dart
Company.find(
session,
where: (company) => company.employees.any()
);
```
> We can retrieve all companies that have any employee with a name starting with **a**
``` dart
Company.find(
session,
where: (company) => company.employees.any((e) => e.name.ilike("a%"))
);
```
> We can retrieve all companies with any employees with a name starting with **a** AND any employees with a name starting with **b**
``` dart
Company.find(
session, …
```
=> feat: Add support for any filter on 1:n relations.

packages/serverpod/lib/src/database/columns.dart, packages/serverpod/lib/src/database/database_query.dart, packages/serverpod/lib/src/database/expressions.dart, packages/serverpod/lib/src/database/many_relation.dart, packages/serverpod/lib/test_util/many_relation_builder.dart, packages/serverpod/lib/test_util/table_relation_builder.dart, packages/serverpod/test/database/database_query/filter_on_any_test.dart, packages/serverpod/test/database/database_query/filter_on_count_test.dart, packages/serverpod/test/database/database_query/filter_on_every_test.dart, packages/serverpod/test/database/database_query/filter_on_none_test.dart, packages/serverpod/test/database/expressions/expression_test.dart, tests/serverpod_test_server/test_integration/database_operations/entity_relations/nested_one_to_many/count/where_every_test.dart, tests/serverpod_test_server/test_integration/database_operations/entity_relations/nested_one_to_many/find/where_every_test.dart, tests/serverpod_test_server/test_integration/database_operations/entity_relations/one_to_many/count/where_every_test.dart, tests/serverpod_test_server/test_integration/database_operations/entity_relations/one_to_many/find/where_every_test.dart
- Support for filtering on many for filtered or unfiltered many side in 1:n relations.
Given the following entities:
``` company.yaml
class: Company
table: company
fields:
name: String
employees: List<Citizen>?, relation
```
``` citizen.yaml
class: Citizen
table: citizen
fields:
name: String
```
> We can retrieve all companies where every employee has a name starting with **a**.
``` dart
Company.find(
session,
where: (company) => company.employees.every((e) => e.name.ilike("a%"))
);
```
> We can retrieve all companies where every employee has a name starting with **a** OR every employee has a name starting with **b**.
``` dart
Company.find(
session,
where: (company) => 
company.employees.every((e) => e.name.ilike("a%")) 
| company.employees.every((e) => e.name.ilike("b%"))
);
```
Best …
=> feat: Add support for every filter on 1:n relations.

tools/serverpod_cli/lib/src/analyzer/entities/definitions.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_dependency_resolver.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/test/analyzer/entities/stateful_analyzer/protocol_validation/relation_manual_field_test.dart
- Prevents defining the relation keyword on both the foreign key name and on the object relation. Error message shows up on the object relation informing the user that the foreign key field already contains a relation definition.
Closes: https://github.com/serverpod/serverpod/issues/1321
None.
=> fix: Prevent double relation definition for entity fields.

tools/serverpod_cli/bin/serverpod_cli.dart, tools/serverpod_cli/lib/src/commands/create_migration.dart
- Renames the command for creating migrations from `migrate` to `create-migration`.
- Fixes an issue where `Done` would be printed even if the migration failed to be created.
Closes: #1502
None - This renames a non released command.
=> fix: Rename `migrate` command to `create-migration`.

tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/test/analyzer/entities/stateful_analyzer/protocol_validation/relation_many_to_many_test.dart
Gives an explicit warning if a m:n relation is specified without a third protocol file.
Closes: https://github.com/serverpod/serverpod/issues/1506
=> fix: Give explicit error on implicit many-to-many relations in protocols.

modules/serverpod_auth/serverpod_auth_server/lib/src/business/users.dart, packages/serverpod/lib/src/database/analyze.dart, packages/serverpod/lib/src/database/bulk_data.dart, packages/serverpod/lib/src/database/database.dart, packages/serverpod/lib/src/database/migration_manager.dart, packages/serverpod/lib/src/endpoints/insights.dart, packages/serverpod/lib/src/server/health_check_manager.dart, tests/serverpod_test_server/lib/src/endpoints/failed_calls.dart
Renames raw queries to `unsafeQuery` etc, prefixing all raw queries with `unsafe`.
Closes: https://github.com/serverpod/serverpod/issues/1486
=> refactor: Rename raw query methods with prefix unsafe

tools/serverpod_cli/lib/src/commands/create_migration.dart, tools/serverpod_cli/lib/src/database/extensions.dart, tools/serverpod_cli/lib/src/database/migration.dart, tools/serverpod_cli/lib/src/migrations/generator.dart, tools/serverpod_cli/test/migrations/migration_generator_test.dart
- Prevents crashing when corrupted migrations are attempted to be loaded.
- Informs users about what has occurred and what actions to take.
- Command returns exit code != 0 if migration could not be created.
- Always use explicit module name for methods.
- Remove inout parameter in favor of existing warning mechanism.
- Initialize client just before it is used to enable unit testing error handling logic.
Closes: #1512 
=> fix: Prevent crashing when trying to load corrupt migration folder.

tools/serverpod_cli/lib/src/commands/create_migration.dart, tools/serverpod_cli/lib/src/util/project_name.dart
- Prints error message and exits with exit code `Command Invoked Cannot Execute` when creating migrations outside of Serverpod folder.
- Prints error messages and exits with same exit code when there is an issue determining the name of a project.
Closes: #1402
None - Changes behavior of a new command in Serverpod 1.2.
=> fix: Prevent `create-migration` command from crashing CLI when run outside serverpod project.

tools/serverpod_cli/lib/src/migrations/generator.dart
- Adds error handling for retrieving live database definition from server when creating a repair migration for database.
Closes: #1318 
None.
=> fix: Prevent crash when creating repair migration without access to server.

templates/pubspecs/packages/serverpod/extension/devtools/config.yaml
Keeps Dart Devtools extension version in sync with Serverpod version.
=> chore: Adds version number to devtools extension.

tests/serverpod_test_server/lib/test_util/migration_test_utils.dart
- Add uuid to every tag for migration tests, otherwise we could end up with a migration with the same name that caused unexpected behavior and made the tests flaky.
We should add tests for this later to give better warnings when there are collisions in created migrations.
=> test: Unique uuid as tag for every migration created to avoid conflicts.

packages/serverpod/generated/protocol.yaml, tests/serverpod_test_server/generated/protocol.yaml, tools/serverpod_cli/lib/src/generator/serverpod_code_generator.dart, tools/serverpod_cli/lib/src/generator/yaml/endpoint_description_generator.dart, tools/serverpod_cli/lib/src/test_util/builders/endpoint_definition_builder.dart, tools/serverpod_cli/lib/src/test_util/builders/method_definition_builder.dart, tools/serverpod_cli/lib/src/test_util/builders/parameter_definition_builder.dart, tools/serverpod_cli/lib/src/test_util/builders/type_definition_builder.dart, tools/serverpod_cli/test/generator/yaml/endpoint_description_test.dart
Code generation class for the protocol.yaml file.
Unit test suit for the code generator.
Closes: https://github.com/serverpod/serverpod/issues/1566
=> fix: Reintroduce generation of protocol.yaml removed in #771.

tests/bootstrap_project/test/project_test.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart
=> test: Wait for ports to be available before executing the nest e2e test.

tests/bootstrap_project/test/project_test.dart, tests/serverpod_test_server/lib/test_util/migration_test_utils.dart, tools/serverpod_cli/lib/src/analytics/analytics.dart, tools/serverpod_cli/lib/src/runner/serverpod_command_runner.dart, tools/serverpod_cli/test/runner/serverpod_command_runner_test.dart, util/generate_all, util/recreate_all_migrations
- Adds a flag to disable analytics reporting when using the Serverpod CLI.
- Removes all analytics reporting from our CI.
=> fix: Add flag to disable analytics reporting and disable it for CI.

packages/serverpod_shared/lib/src/migration_exceptions.dart, tests/serverpod_test_server/test_e2e_migrations/migrations_roundtrip_test.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart, tools/serverpod_cli/lib/src/commands/create_migration.dart, tools/serverpod_cli/lib/src/generator/generator_database_definition.dart, tools/serverpod_cli/test/analyzer/entities/stateful_analyzer/stateful_analyzer_test.dart
- Now stops generating migration if a warning is detected when generating the database definition. This means that we are unable to understand the current entity state of the project.
- Improves the error message printed when a yaml file can't be parsed on the top level.
- Closes: #1583 
None.
=> fix: Print warnings from protocols and stop when generating migrations.

packages/serverpod_shared/lib/src/migration_exceptions.dart, tools/serverpod_cli/lib/src/commands/create_migration.dart, tools/serverpod_cli/lib/src/migrations/generator.dart, tools/serverpod_cli/lib/src/test_util/builders/migration_version_builder.dart, tools/serverpod_cli/test/migrations/migration_version_test.dart
- Display a warning and stops migration creation if migration with the same name already exists.
This likely only happens if migrations are created as part of a CI chain as they would need to call date time during the same second.
- Closes: #1582 
None.
=> fix: Prevent overwriting the same migration when creating migrations.

examples/auth_example/auth_example_client/pubspec.yaml, examples/auth_example/auth_example_server/pubspec.yaml, examples/chat/chat_client/pubspec.yaml, examples/chat/chat_server/pubspec.yaml, templates/pubspecs/tools/serverpod_cli/pubspec.yaml, tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_client/lib/src/protocol/protocol.dart, tests/serverpod_test_client/pubspec.yaml, tests/serverpod_test_module/serverpod_test_module_client/pubspec.yaml, tests/serverpod_test_module/serverpod_test_module_server/pubspec.yaml, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/protocol.dart, tests/serverpod_test_shared/pubspec.yaml, tools/serverpod_cli/lib/src/config/config.dart, tools/serverpod_cli/lib/src/test_util/builders/generator_config_builder.dart, tools/serverpod_cli/lib/src/test_util/builders/module_config_builder.dart, tools/serverpod_cli/lib/src/util/locate_modules.dart, tools/serverpod_cli/pubspec.yaml, tools/serverpod_cli/test/serverpod_packages_version_check/test_assets/approximate_1.1.0/pubspec.yaml, tools/serverpod_cli/test/serverpod_packages_version_check/test_assets/corrupted_pubspec/pubspec.yaml, tools/serverpod_cli/test/serverpod_packages_version_check/test_assets/explicit_1.1.0/pubspec.yaml, tools/serverpod_cli/test/serverpod_packages_version_check/test_assets/vendor/serverpod/pubspec.yaml
Add migration version list to module in config.
Load modules even if they have no nickname defined (defaults to the module name instead).
Improve logic for loading modules, manual configurations now only overload the nickname from disk.
Related: [1499](https://github.com/serverpod/serverpod/issues/1499)
=> fix: Load migration versions for modules to project config.

tools/serverpod_cli/lib/src/config/config.dart, tools/serverpod_cli/lib/src/test_util/builders/generator_config_builder.dart, tools/serverpod_cli/lib/src/test_util/builders/module_config_builder.dart, tools/serverpod_cli/lib/src/util/locate_modules.dart
Loads all modules including serverpod and local project when building project config.
Old modules getter still returning ONLY projects with type module.
New getter to get the entire module list.
Related #1499
=> fix: Add reference to all modules in config.

tools/serverpod_cli/lib/src/commands/create_migration.dart, tools/serverpod_cli/lib/src/commands/create_repair_migration.dart, tools/serverpod_cli/lib/src/migrations/generator.dart
- Add a link to the created migration directory or repair file when creating migrations or repair migrations.
=> fix: provide link to generated migration after it is generated.

tests/serverpod_test_server/generated/migration/migrations/20231202120948541/definition.json, tests/serverpod_test_server/generated/migration/migrations/20231202120948541/definition.sql, tests/serverpod_test_server/generated/migration/migrations/20231202120948541/definition_project.json, tests/serverpod_test_server/generated/migration/migrations/20231202120948541/migration.json, tests/serverpod_test_server/generated/migration/migrations/20231202120948541/migration.sql, tests/serverpod_test_server/generated/migration/migrations/migration_registry.txt, tests/serverpod_test_server/lib/src/generated/protocol.dart, tests/serverpod_test_server/lib/src/protocol/entities_with_relations/nested_one_to_many/team.yaml, tests/serverpod_test_server/lib/src/protocol/entities_with_relations/one_to_one/address.yaml, tools/serverpod_cli/lib/src/analyzer/entities/definitions.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_dependency_resolver.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_parser/entity_parser.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/entity_relations.dart, tools/serverpod_cli/lib/src/analyzer/entities/validation/restrictions.dart, tools/serverpod_cli/lib/src/database/create_definition.dart, tools/serverpod_cli/lib/src/test_util/builders/class_definition_builder.dart, tools/serverpod_cli/test/analyzer/entities/stateful_analyzer/protocol_validation/indexes_properties_test.dart, tools/serverpod_cli/test/analyzer/entities/stateful_analyzer/protocol_validation/relation_database_action_test.dart, tools/serverpod_cli/test/analyzer/entities/stateful_analyzer/protocol_validation/relation_manual_field_test.dart, tools/serverpod_cli/test/analyzer/entities/stateful_analyzer/protocol_validation/relation_one_to_one_test.dart, tools/serverpod_cli/test/analyzer/entities/stateful_analyzer/protocol_validation/relation_self_one_to_one_test.dart
- Adds a requirement to declare a unique index when defining one to one object relations. This is needed to ensure that it actually is a one-to-one relation once the ORM methods are generated.
- Closes: #1619 
=> fix: Add unique index requirement on one to one object relations.

tools/serverpod_cli/lib/src/analyzer/entities/entity_analyzer.dart, tools/serverpod_cli/lib/src/util/protocol_helper.dart
Allow `.spy`, `.spy.yaml` and `.spy,yml` file extensions on protocol files. The extensions will be replaced with .dart when code is generated.
=> fix: Allow .spy file extensions on protocols.

packages/serverpod_shared/lib/src/migration_exceptions.dart, tools/serverpod_cli/lib/src/migrations/generator.dart
- Adds back a helpful message displayed when the repair migration target can't be found.
We don't have any tests for this area right now, but I have manually validated the output.
=> fix: Add back repair migration ux.

examples/auth_example/auth_example_server/lib/server.dart
Typo in example auth project.
Closes: https://github.com/serverpod/serverpod/issues/1428
=> fix: Typo in reset password example email.

templates/serverpod_templates/projectname_flutter/lib/main.dart
Reset error state if successful call to endpoint was made.
Closes: https://github.com/serverpod/serverpod/issues/1028
=> fix: Reset error message state when endpoint call was successful in template project.

modules/serverpod_chat/serverpod_chat_flutter/pubspec.yaml, templates/pubspecs/modules/serverpod_chat/serverpod_chat_flutter/pubspec.yaml, templates/pubspecs/tools/serverpod_cli/pubspec.yaml, tools/serverpod_cli/pubspec.yaml
Serverpod uses an old version of `intl`, which causes a conflict with multiple other libraries I need to depend upon.
This PR upgrades the Serverpod `intl` dependency version from `0.17.0` to `0.18.1`.
=> Upgrade intl dependency to version 0.18.1

packages/serverpod/lib/src/server/endpoint_dispatch.dart
- Close the session when throwing an exception to the client.
- Log the method call made.
Closes: https://github.com/serverpod/serverpod/issues/974
=> fix: Close session when protocol exception is thrown.

examples/auth_example/auth_example_client/lib/src/protocol/client.dart, examples/chat/chat_client/lib/src/protocol/client.dart, packages/serverpod_client/lib/src/serverpod_client_browser.dart, packages/serverpod_client/lib/src/serverpod_client_io.dart, packages/serverpod_client/lib/src/serverpod_client_shared.dart, packages/serverpod_service_client/lib/src/protocol/client.dart, templates/serverpod_templates/projectname_client/lib/src/protocol/client.dart, tests/serverpod_test_client/lib/src/protocol/client.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart
Makes client timeout configurable.
Also adds timeout to `_httpClient.close()`, since this seems to be able to hang forever even if `_httpClient.connectionTimeout` is set.
Does this even need a test? It is a very minor change.
=> Make HTTP timeout configurable

tools/serverpod_cli/lib/src/analyzer/entities/converter/converter.dart, tools/serverpod_cli/lib/src/analyzer/entities/entity_parser/entity_parser.dart, tools/serverpod_cli/lib/src/config/config.dart, tools/serverpod_cli/lib/src/generator/types.dart, tools/serverpod_cli/lib/src/util/string_manipulation.dart, tools/serverpod_cli/test/analyzer/entities/stateful_analyzer/protocol_validation/field_datatype_test.dart, tools/serverpod_cli/test/analyzer/entities/stateful_analyzer/protocol_validation/field_source_location_test.dart, tools/serverpod_cli/test/util/string_manipulation_test.dart
- Refactors parsing of types logic to a cleaner interface.
- Changes the logic to split the strings on , to allow for deeply nested Maps and Lists.
- Allows trailing commas in protocol files.
Discussion point: 
The previous implementation did "validation" of the type string. It only handled a single invalid scenario namely if the programmer forgot the close a bracket with `>`. This validation is removed in the new implementation, we could implement a proper validation, but to get a complete type validation it requires quite a bit of extra information, hence I propse we do that in a future PR. Issue tracked here: https://github.com/serverpod/serverpod/issues/282
Closes: #1104 …
=> fix: Allow deeply nested Maps and Lists in protocol files.

packages/serverpod/lib/src/server/serverpod.dart, tools/serverpod_cli/lib/src/create/create.dart, tools/serverpod_cli/lib/src/util/command_line_tools.dart, tools/serverpod_cli/lib/src/util/constants.dart
- Checks that the docker volume does not exist, if it does give an error to the user.
- In maintenance mode only try to reconnect to the database 6 times before giving up.
Closes: #531
=> fix: Validate docker volume names when creating new project.

modules/serverpod_auth/serverpod_auth_firebase_flutter/lib/src/auth.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/firebase_endpoint.dart
- Removes explicit check for email from firebase, I.E. allow none email based providers to work with serverpod.
- Fixes an invalid response check in the client causing the logic to throw on a null value cast.
- Fixes bug where we would pop the view twice after login / failed to login with firebase.
- Adds log of errors when authentication fails on exception in the server, (such as invalid firebase credentials).
Closes: #417
=> fix: Allow firebase phone auth and log auth errors.

tools/serverpod_cli/lib/src/analyzer/dart/endpoint_analyzers/endpoint_method_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/dart/endpoint_analyzers/endpoint_parameter_analyzer.dart, tools/serverpod_cli/lib/src/generator/types.dart, tools/serverpod_cli/test/integration/analyzer/dart/endpoint_validation/endpoint_method_parameter_test.dart, tools/serverpod_cli/test/integration/analyzer/dart/endpoint_validation/endpoint_method_test.dart
- Adds check in method validator ensuring we can convert the return type to our internal dart type.
- Adds check in parameter validator ensuring we can convert parameter to our internal dart type.
This PR is more of a catch all to remove the crashing issue.
More validation with specific errors should be added here to ensure the user is properly informed about what is supported.
These validation messages will be added once we can validate the classes used as return type and parameters.
Task for implementing full support for records is tracked here: https://github.com/serverpod/serverpod/issues/588
This PR depends on: https://github.com/serverpod/serverpod/pull/1672
- Closes: #1574,
- Closes: #1275,
- Closes: #1299,
- Closes: #1390. 
If you need help, consider asking for advice on the …
=> fix: Prevent endpoint analyzer from crashing when unsupported type is used.

.github/workflows/dart-tests.yaml, tests/bootstrap_project/test/project_test.dart, tools/serverpod_cli/test_e2e/test/generate_watch_test.dart
Increase the timeout on the integration test as we are hitting the limit on macOS runners.
=> test: Increase timeout on integration tests.

tools/serverpod_cli/test_e2e/lib/src/keyword_search_in_stream.dart
- Adds debug output and does not cancel stream if error is encountered in stream.
In an effort to debug the issues with the CLI e2e tests recently encountered we add some debug information if a steam encounters an error.
=> test: Add debug output on stream errors.

tools/serverpod_cli/test_e2e/lib/src/keyword_search_in_stream.dart, tools/serverpod_cli/test_e2e/test/generate_watch_test.dart
- Moves the stream listen initialization out into the test class for hopefully a different lifecycle management.
For some reason moving the listen initialization out into the test instead of having it inside of the keyword search class seems to help to keep the stream open.
=> test: Initiate listen outside of keyword search class for test.

tools/serverpod_cli/lib/src/analyzer/code_analysis_collector.dart, tools/serverpod_cli/lib/src/analyzer/models/stateful_analyzer.dart, tools/serverpod_cli/lib/src/generator/code_generation_collector.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/field_validation_test.dart
- Fixes a bug where we would ignore a model regardless of error level reported.
- Changes the output when errors are found to write "issue(s)" instead and color the output based on the existing error levels, see screenshot.
- Generate command reports as succeeded if only info / hint level errors are created. 
Closes: #1682 
=> fix: Generate output from models from hints and into level errors.

tools/serverpod_cli/lib/src/commands/version.dart, tools/serverpod_vscode_extension/package.json, tools/serverpod_vscode_extension/src/extension.ts
- Adds a helpful warning to the user if the extension is installed together with an incompatible serverpod version or if the serverpod cli is not found.
Only impacts unreleased feature.
=> fix: Add warnings if Serverpod CLI is not found or if version is not compatible with extension.

tests/serverpod_test_server/test_e2e_migrations/migrations_roundtrip_test.dart
Adds an e2e test to check that we do not create a new migration if we only add a none managed table.
Related to PR: [#16](https://github.com/serverpod/serverpod/pull/1688)
=> test: Add e2e test for opting out from migrations.

tools/serverpod_cli/lib/src/analyzer/models/validation/restrictions.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/field/field_validation_test.dart
- Reduces the max number of characters allowed for a model field to allow space for implicit id fields.
None.
=> fix: Reduce model field name max length.

tools/serverpod_cli/lib/src/commands/create_migration.dart, tools/serverpod_cli/lib/src/commands/create_repair_migration.dart, tools/serverpod_cli/lib/src/commands/generate.dart, tools/serverpod_cli/lib/src/config/config.dart, tools/serverpod_cli/lib/src/create/database_setup.dart, tools/serverpod_cli/lib/src/language_server/language_server.dart
Report explicit errors when failing to load the config, this enable us to give better error messages when we are unable to load a project in the vscode plugin.
Report that `dart pub get` needs to be run if we are unable to locate the modules.
=> fix: Add error validation if unable to locate modules.

templates/serverpod_templates/projectname_server/Dockerfile
- Removes reference to removed folder.
When rearranging the folder structure (PR here: https://github.com/serverpod/serverpod/pull/1752) a copy in the docker file was not correctly removed preventing the docker file from being built.
Closes: #1763
None - this file copied once on project creation and influenced projects don't have the generated file anymore.
=> fix: Remove copy of removed generated folder

packages/serverpod/pubspec.yaml, templates/pubspecs/packages/serverpod/pubspec.yaml
- Bumps the vm_service version from 13.x.x to the range ">=13.x.x <15.x.x".
Using the range since there seems to be some lacking support in the dart sdk for all features of the vm_service.
Since this is only used in one place in the Serverpod project it probably won't influence us but could be a transitive limitation for anyone utilizing the Serverpod package.
Thanks @yahu1031 for the heads up on the compatibility issues.
Dart thread here: https://github.com/dart-lang/sdk/issues/54483
None - backwards compatible upgrade.
=> chore: Bump vm_service version to ">=13.x.x <15.x.x".

tools/serverpod_cli/lib/src/language_server/language_server.dart
- Remove displaying warning when the LSP fails to resolve the Serverpod project.
When opening VSCode, currently warnings "not a serverpod project" warnings are shown as soon as a file that matches the lsp pattern I opened, such as `.yaml` files in a protocol or model folder.
We are concerned that this warning in the wrong context will drive users to disable or uninstall the plugin.
This PR removes that warning for now.
None.
=> fix: Remove Serverpod project warning message.

packages/serverpod/lib/src/relic/routes/static_directory.dart, packages/serverpod/lib/src/server/server.dart
- Make path parsing windows compatible.
Recent change modified the URI path parsing, but by using the path library the paths on windows would use backslash.
=> fix: Make path parsing windows compatible.

tools/serverpod_cli/lib/src/create/create.dart
- Enables the possibility to create modules in developer mode with a reference to local Serverpod project.
Part of: https://github.com/serverpod/serverpod/issues/1768
Noticed that we didn't support creating developer projects for modules.
This is just a small fix too align the implementation in order to change it later.
None: only fixes for developer mode.
=> fix: Enable possiblity to create module templates in developer mode.

tools/serverpod_cli/lib/src/analyzer/models/entity_dependency_resolver.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/field/field_datatype_test.dart
- Mark enum types in generic data types in model files, E.g. on List and Map
Example:
```yaml
class: Example
fields:
listEnum: List<MyEnum>
mapEnum: Map<MyEnum, MyEnum>
```
Before this change the internal model did not correctly mark the enums as enums.
None.
=> fix: Correctly mark nested enum types in the analyzer.

tools/serverpod_cli/lib/src/analyzer/models/validation/restrictions.dart, tools/serverpod_cli/lib/src/util/string_validators.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/enum_values_test.dart
Allow enums to have uppercase in a snakecase string. 
Remove any info level warnings on enums.
Only restrict values to valid dart enum names. 
Defer the info warning linting to dart in this case as we do not support toggling rules and users may want to allow non-standard naming conventions in their code. 
Closes: #1813 
none
=> fix: Less restrictive enum naming rules.

templates/serverpod_templates/projectname_server/Dockerfile, tests/docker/tests_e2e_migrations/Dockerfile-server, tests/docker/tests_e2e_migrations/Dockerfile-tests, tests/docker/tests_integration/Dockerfile, tests/docker/tests_single_server/Dockerfile-server, tests/docker/tests_single_server/Dockerfile-tests
- Lock Dart and Busybox image versions to versions that are compatible.
When creating a new project a lot of users ran into issues where the Dart and Busybox image would resolve to incompatible versions. This was most notably seen in the error messages:
```
/bin/sh: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /bin/sh)
/bin/sh: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /bin/sh)
```
Closes: #1054
Closes: #1101
Closes: #882 (Should probably resolve this issue as well if using current released version of Serverpod).
None - this will only influence newly created projects.
=> fix: Pin Dart and Busybox docker image versions.

packages/serverpod/test/database/table_relation_test.dart
- Adds unit tests for table relation alias truncations.
Closes: #1746
None - only tests.
=> test: Add unit tests for table relation alias truncations.

packages/serverpod/lib/src/server/serverpod.dart, tests/bootstrap_project/test/project_test.dart
- Fixes an issue where we would try to apply null runtime settings instead of the default runtime settings when database is not initialized.
- Adds an e2e test to start the server without applying any migrations.
None - Fixes a previously introduced issue.
=> fix: Enable server to start with running but not migrated database.

tools/serverpod_cli/lib/src/analyzer/models/definitions.dart, tools/serverpod_cli/lib/src/analyzer/models/entity_dependency_resolver.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/relation/relation_one_to_many_test.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/relation/relation_one_to_one_test.dart
Adds additional field pointers in our internal class representation in the analyzer / code generator. This will help us make relational decisions when generating code.
Adds new tests to cover the new functionality and a few tests to cover some basic scenarios that was not tested explicitly before (different combinations of setups in the model files).
none
=> fix: Resolve internal relation pointers in class representations.

tools/serverpod_cli/lib/src/config/config.dart
Support running the `serverpod generate` command when the generator.yaml is not present in the project.
Will use the project name to find the path to the client project as a default. If the user want a none default path it has to be specified in the generator.yaml file.
Related issue: https://github.com/serverpod/serverpod/issues/1725
None
=> fix: Support projects without a config generator file in cli.

packages/serverpod/lib/src/database/database_pool_manager.dart, packages/serverpod/lib/src/server/health_check.dart
- Removes a method for creating a database connection from the pool manager.
Cleanups to alleviate bumping the Postgres package version https://github.com/serverpod/serverpod/issues/1766
Internal method that should not have been used.
=> fix: Remove creating database connection in pool manager.

tools/serverpod_cli/lib/src/analyzer/models/validation/restrictions.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/field/field_parent_test.dart
Fixes a crash if none string value was given to the parent keyword.
Closes: #1859 
None
=> fix: Give error if none string value is supplied to parent keyword.

packages/serverpod/lib/src/server/serverpod.dart, packages/serverpod_shared/lib/src/config.dart, tools/serverpod_cli/lib/src/analyzer/models/validation/restrictions.dart, tools/serverpod_cli/lib/src/commands/create_migration.dart, tools/serverpod_cli/lib/src/commands/create_repair_migration.dart, tools/serverpod_cli/lib/src/config/config.dart
In a project with the database feature disabled:
* Gives an error for command `serverpod create-migration`
* Gives an error for the command `serverpod create-repair-migration`
* Gives an error if starting the server with the `--apply-migrations` flag
* Gives an error if starting the server with the `--apply-repair-migration` flag
Remove prints of null values in the config.
Related issue: #1725 
None
=> fix: Give explicit errors when using migration system in a mini project.

packages/serverpod/lib/src/database/database.dart
Removes the unused session param in unsafeMappedQueryResult. This looks like a copy paste error in the code and should not have been included in the first place.
Closes: #1890
Breaks the interface of the method as the param was required before.
=> fix: Remove unused param in unsafe mapped query.

tools/serverpod_cli/lib/src/config/config.dart, tools/serverpod_cli/lib/src/util/directory.dart
Bug that stopped the generated command to work in the serverpod package project.
None
=> fix: Allow generate command in serverpod package project.

util/generate_all
Adds a check for exit code in the generate_all script. The script will exit with a failure if any generate command returns a none zero exit code.
=> chore: Exit generate all if one command fails.

tools/serverpod_cli/lib/src/commands/language_server.dart, tools/serverpod_cli/lib/src/runner/serverpod_command_runner.dart, tools/serverpod_cli/test/runner/serverpod_command_runner_test.dart, tools/serverpod_vscode_extension/package-lock.json, tools/serverpod_vscode_extension/package.json, tools/serverpod_vscode_extension/src/extension.ts
- Sets log level `nothing` when `language-server` command is provided to CLI.
- Adds the quite flag to the vs code extension so silence new version available warnings. This ensures that the extension starts working for all users that to not use the latest version of Serverpod.
Closes: #1847
When the CLI is run we perform a version check to see if a new version of serverpod is available. If a new version is available we print a message prompting the user to update. The LSP requires that no other messages are transmitted and therefore crashed on startup when an update prompted message was printed. 
This PR ensure we don't make any prints if when running the LSP.
_If …
=> fix: Prevent vscode extension from crashing on startup.

packages/serverpod/lib/src/cloud_storage/database_cloud_storage.dart, packages/serverpod/lib/src/database/database.dart
- Marks the file handling methods in the database layer as deprecated for 2.0.0.
None, simply an annotation change.
=> docs: Mark file handling db methods as deprecated.

packages/serverpod/lib/src/database/expressions.dart, packages/serverpod/test/database/expressions/constant_test.dart
- BREAKING: Removes the deprecated constant expression constructor.
YES -> Removes the constant expression constructor.
=> fix!: Remove deprecated constant expression constructor.

packages/serverpod/lib/src/server/future_call_manager.dart, tests/serverpod_test_server/lib/src/endpoints/database_transactions.dart, tests/serverpod_test_server/lib/src/endpoints/field_scopes.dart, tests/serverpod_test_server/lib/src/endpoints/logging.dart
- Converts the future call manager from using a deprecated db method to using a transaction.
- Updates non legacy tests to not use deprecated methods.
None - functionally should operate the same.
=> fix: Remove non legacy deprecated member use.

tools/serverpod_vscode_extension/syntaxes/serverpod.tmLanguage.json
- Correctly syntax highlight comments under indexes.
Closes: #1909
None.
=> fix: syntax highlight comments for indexes in model files.

modules/serverpod_auth/serverpod_auth_shared_flutter/lib/src/session_manager.dart, packages/serverpod/lib/src/database/expressions.dart, packages/serverpod_client/lib/src/serverpod_client_shared.dart
- BREAKING: Remove deprecated methods in serverpod client (`serverpod_client_shared.dart`).
- BREAKING: Remove deprecated methods in serverpod auth (`session_manager.dart`).
- BREAKING: Remove deprecated methods in serverpod (`expressions.dart`)
Removes the last methods marked as deprecated.
The following files have listed methods removed as part of this PR.
`serverpod_client_shared.dart` in serverpod_client package.
- `connectWebSocket()`
- `reconnectWebSocket()`
- `addWebSocketConnectionStatusListener(...)`
- `removeWebSocketConnectionStatusListener(...)`
- `isWebSocketConnected`
`session_manager.dart` in serverpod_auth package.
- `signedInUser(...)` …
=> fix!: Remove deprecations in serverpod client, and serverpod auth and serverpod package.

packages/serverpod/lib/database.dart, packages/serverpod/lib/src/database/concepts/expressions.dart, packages/serverpod/lib/src/database/database.dart, packages/serverpod/lib/src/database/database_pool_manager.dart, packages/serverpod/lib/src/database/extensions.dart, packages/serverpod/lib/src/server/health_check_manager.dart, packages/serverpod/lib/src/server/server.dart, packages/serverpod/lib/src/server/serverpod.dart, packages/serverpod/lib/src/server/session.dart
- BREAKING: Removes accessor to database_pool_manager from `Serverpod` and `Server`.
- BREAKING: don't export `database_pool_manager.dart` from `database` library.
- Create a database object directly in `Server` from `Session`.
Preparation for https://github.com/serverpod/serverpod/issues/1766.
The goal is to isolate all library specific implementation around the database so that we get a stable user facing interface while we can change the internal implementation.
Yes -> Removes all accessors to DatabasePoolManager and stops the exporting of the class.
=> refactor!: Hide database pool manager.

packages/serverpod/lib/src/database/adapters/postgres/database_connection.dart
- Passes transaction into the delete method.
This was probably overlooked at sometime.
None - Delete now properly functions with transactions.
=> fix: Pass transaction for delete method.

packages/serverpod/lib/src/database/adapters/postgres/database_connection.dart, packages/serverpod/lib/src/database/adapters/postgres/database_result.dart, packages/serverpod/lib/src/database/database.dart
- Removes usage of `mappedResultsQuery` in preparation for Postgres library V.3.
- BREAKING: Changes return type for `unsafeQueryMappedResults` to align with Postgres V.3 return types where mappedResultsQuery is removed.
This is done in preparation for: https://github.com/serverpod/serverpod/issues/1766
Upgrade instructions documentation PR here: https://github.com/serverpod/serverpod_docs/pull/75
Given the following query is executed through the `unsafeQueryMappedResults` method the following results can be observed.
```sql
SELECT
"company"."id" AS "company.id",
"company"."name" AS "company.name",
"company"."townId" AS "company.townId",
"company_town_town"."id" AS "company_town_town.id",
"company_town_town"."name" AS "company_town_town.name",
"company_town_town"."mayorId" AS …
```
=> fix!: Remove usage of mappedResultQuery and update return type.

packages/serverpod/lib/src/database/adapters/postgres/database_connection.dart, packages/serverpod/lib/src/database/concepts/transaction.dart, tests/serverpod_test_server/test_integration/database_operations/transactions/transaction_test.dart
- Make the transaction object a more generic interface that does not depend on package dependency types.
- BREAKING: Removes the `PostgreSQLExecutionContext` from the transaction object.
- Adds a cancel method to the transaction object so that transactions can be cancelled.
This is done in preparation for https://github.com/serverpod/serverpod/issues/1766.
Serverpod needs to own its own interfaces so that we can make implementation changes (such has switching underlying packages) without making braking changes for our users.
This PR makes the transaction object generic and only exposes the `cancel` method that allows developers to cancel transactions.
All transaction functionality is still available using direct queries towards the database.
If you need help, consider asking for advice on …
=> fix!: Make transaction a generic interface.

packages/serverpod/lib/src/database/bulk_data.dart, packages/serverpod/lib/src/generated/database/bulk_query_column_description.dart, packages/serverpod/lib/src/models/database/bulk_query_column_description.spy.yaml, packages/serverpod_service_client/lib/src/protocol/database/bulk_query_column_description.dart
- BREAKING: Removes table name from BulkQueryColumnDescription.
In the Postgres 3.0 library the table name is no longer included in the result schema information for each column.
We don't use it in insights so it should be safe for us to removed.
Done in preparation for https://github.com/serverpod/serverpod/issues/1766.
Yes -> Removes a field from an exposed class.
=> fix!: Remove table from bulk query column description.

tools/serverpod_cli/lib/src/analyzer/models/model_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/models/model_parser/model_parser.dart, tools/serverpod_cli/lib/src/analyzer/models/stateful_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/models/validation/restrictions.dart, tools/serverpod_cli/lib/src/config/config.dart, tools/serverpod_cli/lib/src/generator/types.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/field/field_datatype_test.dart
Fixes regression that gave error on valid custom classes, this applies to all generic types too.
Example:
```yaml
...
extraClasses:
- package:serverpod_test_shared/serverpod_test_shared.dart:ExternalCustomClass
```
```yaml
class: Example
fields:
customClassField: ExternalCustomClass
list: List<ExternalCustomClass>
map: Map<String, ExternalCustomClass>
```
All of the above declarations gave an invalid type error when running `serverpod generate`.
With this PR all of the above will not give any error and will resolve the import paths correctly.
Closes: https://github.com/serverpod/serverpod/issues/1932
None
=> fix: Resolve and validate registered custom classes used as types in model fields.

packages/serverpod/lib/database.dart, packages/serverpod/lib/src/database/adapters/postgres/database_connection.dart, packages/serverpod/lib/src/database/exceptions.dart, packages/serverpod/lib/src/endpoints/insights.dart
- BREAKING: Throw library database exception instead of the Postgres libraries version of the exception.
- Catch the library version of the exception in the insights endpoint.
Preparation for: https://github.com/serverpod/serverpod/issues/1766
Yes -> Stops Serverpod code from throwing Postgres library exception type.
=> fix!: Introduce and use Serverpod database exception.

tools/serverpod_cli/lib/src/generator/types.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/field/field_datatype_test.dart
Add proper nullability check on custom classes.
Closes: https://github.com/serverpod/serverpod/issues/1947
None
=> fix: Custom classes respect nullable configuration.

packages/serverpod/lib/database.dart, packages/serverpod/lib/src/database/adapters/postgres/database_connection.dart, packages/serverpod/lib/src/database/adapters/postgres/postgres_database_result.dart, packages/serverpod/lib/src/database/adapters/postgres/value_encoder.dart, packages/serverpod/lib/src/database/analyze.dart, packages/serverpod/lib/src/database/concepts/query_mode.dart, packages/serverpod/lib/src/database/concepts/transaction.dart, packages/serverpod/lib/src/database/database.dart, packages/serverpod/lib/src/database/database_pool_manager.dart, packages/serverpod/lib/src/database/migrations/migration_manager.dart, packages/serverpod/pubspec.yaml, templates/pubspecs/packages/serverpod/pubspec.yaml, tests/serverpod_test_server/test_integration/database_operations/transactions/transaction_test.dart, tests/serverpod_test_server/test_integration/database_operations/unsafe_query/database_result_test.dart
- Bumps Postgres package to ^3.0.
- Introduce Postgres query mode selection for unsafe queries.
- Refactors the code used to make calls for analyzing the database.
The reason we need to expose the query mode is because the driver now seems to always initiate an extended query behavior for all requests even if no functionality is used. The extended query behavior does not allow multiple queries to be executed as a single query, which is the way we apply our migrations. Therefore we expose it as a configurable for unsafe queries.
Closes: https://github.com/serverpod/serverpod/issues/1766
Best reviewed commit by commit, it is mostly about adapting files to the new behaviors of the interface. …
=> fix!: Bump postgres package version.

modules/serverpod_auth/serverpod_auth_server/lib/src/business/config.dart
- Disables unsecure random by default.
Default value for method changes which might cause the random call to throw.
=> fix: Change default value for allowUnsecureRandom.

tools/serverpod_cli/lib/src/commands/upgrade.dart, tools/serverpod_cli/lib/src/logger/loggers/std_out_logger.dart, tools/serverpod_cli/lib/src/runner/serverpod_command.dart, tools/serverpod_cli/lib/src/runner/serverpod_command_runner.dart
- Non zero exit code when upgrade command fails.
- Command help message has new line at the end.
- Fixed an issue where `log.progress` would print two empty lines to create a new paragraph.
**Command help message after fix**
**Log progress after fix:**
None.
=> fix: Misc developer experience fixes.

modules/serverpod_auth/serverpod_auth_server/lib/src/business/email_auth.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/business/password_hash.dart, modules/serverpod_auth/serverpod_auth_server/test/password_hash/argon2id_password_hash_test.dart, modules/serverpod_auth/serverpod_auth_server/test/password_hash/legacy_password_hash_test.dart, modules/serverpod_auth/serverpod_auth_server/test/password_hash/legacy_to_argon2id_hash_test.dart, tests/serverpod_test_server/test_integration/authentication/email_auth_provider_test.dart
- Adds a limit option to the password migration helper.
This can be used to batch the number of migrations that are done.
None - this is a new method.
=> fix: Add maxMigratedEntries option to the migration helper method. (Targeting 1.2)

packages/serverpod_client/lib/src/serverpod_client_io.dart, tests/serverpod_test_server/test_e2e/tsl_client_test.dart
- Remove callback that allowed any certificate to be valid.
- Add e2e test to validate that we now reject untrusted certificates. 
Closes: https://github.com/serverpod/serverpod/issues/2040
=> fix: Remove faulty certificate check.

packages/serverpod/lib/src/database/columns.dart, packages/serverpod/test/database/columns/column_bool_test.dart, packages/serverpod/test/database/columns/column_count_test.dart, packages/serverpod/test/database/columns/column_date_time_test.dart, packages/serverpod/test/database/columns/column_double_test.dart, packages/serverpod/test/database/columns/column_duration_test.dart, packages/serverpod/test/database/columns/column_enum_test.dart, packages/serverpod/test/database/columns/column_int_test.dart, packages/serverpod/test/database/columns/column_string_test.dart, packages/serverpod/test/database/columns/column_uuid_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_bool_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_count_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_date_time_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_double_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_duration_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_enum_serialized_by_index_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_enum_serialized_by_name_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_int_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_string_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_uuid_test.dart
- Passing empty set to inSet matches no row in the database.
- Passing empty set to notInSet matches all rows in the database.
Closes: #2070
Closes: #1968
None - fixes a bug.
=> fix: Fix issue when passing empty set to InSet and notInSet.

packages/serverpod/lib/src/database/concepts/columns.dart, packages/serverpod/test/database/columns/column_bool_test.dart, packages/serverpod/test/database/columns/column_count_test.dart, packages/serverpod/test/database/columns/column_date_time_test.dart, packages/serverpod/test/database/columns/column_double_test.dart, packages/serverpod/test/database/columns/column_duration_test.dart, packages/serverpod/test/database/columns/column_enum_test.dart, packages/serverpod/test/database/columns/column_int_test.dart, packages/serverpod/test/database/columns/column_string_test.dart, packages/serverpod/test/database/columns/column_uuid_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_bool_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_count_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_date_time_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_double_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_duration_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_enum_serialized_by_index_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_enum_serialized_by_name_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_int_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_string_test.dart, tests/serverpod_test_server/test_integration/column_operations/column_uuid_test.dart
Apply same change as here: https://github.com/serverpod/serverpod/pull/2073
None.
=> fix: Fix issue when passing empty set to InSet and notInSet. 

templates/serverpod_templates/projectname_server/gitignore
This adds the firebase service account key file to the templates gitignore. Since the name is a serverpod convention it is safe to assume that adding it to gitignore should also be a convention similar to the passwords.yaml.
Closes #2085
=> Add firebase service account key to gitignore

packages/serverpod/lib/src/server/session.dart
This Pull Request have fixed the typo 'UserAuthetication' -> 'UserAuthentication' in /serverpod/lib/src/server/session.dart (Line 356 & 359)
Also Created a dummy class with the old (incorrect) name and add a deprecated annotation, so it's easier to find the correct class when upgrading.
This solves issue: https://github.com/serverpod/serverpod/issues/1887
URL Link: https://github.com/serverpod/serverpod/blob/main/packages/serverpod/lib/src/server/session.dart in Line 356 and 359.
Pre-launch Checklist
- [] I added new tests to check the change I am making.
Breaking changes - 
Since the Class Name has changed its spelling, which is a publically exposed API, it is a breaking change which could be easily fixed with correcting the spelling.
=> Typo fix 'UserAuthetication' -> 'UserAuthentication' 

packages/serverpod/lib/src/server/session.dart
This Pull Request have fixed the typo 'UserAuthetication' -> 'UserAuthentication' in /serverpod/lib/src/server/session.dart (Line 356 & 359) and kept the deprecated API(It is removed in 2.0.0 by this [PR](https://github.com/serverpod/serverpod/pull/2088)). 
Created a dummy class with the old (incorrect) name and add a deprecated annotation, so it's easier to find the correct class when upgrading.
This solves issue: https://github.com/serverpod/serverpod/issues/1887
URL Link: https://github.com/serverpod/serverpod/blob/main/packages/serverpod/lib/src/server/session.dart in Line 356 and 359.
Since the Class Name has changed its spelling, which is a publically exposed API, it is a breaking change which could be easily fixed with correcting the spelling.
=> Deprecated the Older Class's API and added the updated Class to use.

packages/serverpod/lib/src/server/future_call_manager.dart
- Utilize the delete where operation to retrieve and remove future call entries.
Since no policy is configured for transactions, multiple instance of Serverpod might read and process the same future call operations before where removed from the database.
This issue was introduced when the `deleteAndReturn` method was removed but has not been released in a stable release yet.
This PR depends on the changes in https://github.com/serverpod/serverpod/pull/2121
None - internal functionality.
=> fix: Retrieve and remove future call entries in one operation.

packages/serverpod/lib/src/relic/templates.dart, packages/serverpod/lib/src/relic/web_server.dart, packages/serverpod/test/relic/templates_test.dart
- Adds a check if the template directory exists before trying to load it.
- Use platform agnostic pattern when loading template directory.
Closes: #2101 
None - simple bugfix.
=> fix: Prevent crash when missing web or template directory.

packages/serverpod/lib/src/relic/templates.dart, packages/serverpod/lib/src/relic/web_server.dart, packages/serverpod/test/relic/templates_test.dart
Same fix as here: https://github.com/serverpod/serverpod/pull/2138
Connected to #2101 
None.
=> fix: Prevent crash when missing web or template directory (Stable 1.2)

tools/serverpod_cli/lib/src/runner/serverpod_command_runner.dart, tools/serverpod_cli/test/integration/downloads/resource_manager_test.dart
Minor fixes encountered when working on a different feature.
These should also be applied to the stable 1.2 branch.
- Removes a trailing `%` print for error messages (same fix as we applied before but for regulair messages)
- Moves the resource manager integration tests to the integration test folder.
None - just minor fixes.
=> fix: Misc serverpod fixes.

tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/endpoints_test.dart
- It prevents generating an unused variable if no endpoints are defined.
Without this fix, the analyzer will give a warning if no endpoints are defined.
Fixes: #2154
None - simple bug fix.
=> fix: Prevent generating empty endpoints variable when no endpoints are defined.

templates/serverpod_templates/projectname_server_upgrade/Dockerfile
**Edit:**
Reverting back some of the changes here with the effect that the `--apply-migrations` feature described will not work.
The reason for this decision is that we have terraform modules and bash scripts that require the environment variable input to exist. These deployment scripts are today pinned to the main branch and has no versioning reference. This means we are not able to update the scripts without breaking old docker images. 
The solution we want to implement in the future is to have proper environment variable support in Serverpod so that they can be parsed natively by the framework. This way we would be able to to allow both env configurations as well as command line args, even outside a docker environment. 
The current image is based on alpine as we need sh in the …
=> fix: Docker template support x86 and dynamic flags.

tools/serverpod_cli/lib/src/generator/generator_continuous.dart
This adds a timestamp to the log output when "serverpod generate --watch" detects changes 
closes:  #971
=> add timestamp to generate --watch log output

tools/serverpod_cli/lib/src/generator/generator_continuous.dart
Like #2198, this PR adds a timestamp to the log output when "serverpod generate --watch" detects changes
closes: #971
no breaking changes
=> add timestamp to generate --watch log output 1.2

tests/serverpod_test_client/lib/src/custom_classes.dart, tests/serverpod_test_client/lib/src/protocol/protocol.dart, tests/serverpod_test_client/lib/src/protocol_custom_classes.dart, tests/serverpod_test_server/lib/src/custom_classes.dart, tests/serverpod_test_server/lib/src/generated/protocol.dart, tests/serverpod_test_server/lib/src/protocol_custom_classes.dart, tests/serverpod_test_shared/lib/src/external_custom_class.dart, tests/serverpod_test_shared/lib/src/freezed_custom_class.dart, tools/serverpod_cli/lib/src/generator/types.dart
This PR continues the work started in [PR #2102](https://github.com/serverpod/serverpod/pull/2102) by removing the `SerializationManager` parameter from the `fromJson` factory constructor in custom classes. The previous PR successfully eliminated this parameter from all serverpod-generated classes and models, and this change extends that simplification to include custom classes as well.
=> removing SerializationManager as parameter from fromJson factory consructor on the code generator for custom classes

tests/serverpod_test_server/test_e2e/json_protocol_test.dart
This PR introduces end-to-end tests specifically for endpoints that generate runtime exceptions.
=> adding e2e tests for exceptions

packages/serverpod/lib/src/relic/web_server.dart
Removes the redirect path on host name match from relic. 
Reasoning: This makes more sense to configure in the loadbalancer and simplifies the setup when configuring health checks and doing more complex internal traffic etc.
Since you are not able to disable this feature today you will have to set the `host` in the header of the request to work around this limitation which you may or may not be able to do.
none
=> fix: Remove redirect from relic.

examples/auth_example/auth_example_server/README.md, integrations/serverpod_cloud_storage_gcp/lib/src/cloud_storage/google_cloud_storage.dart, integrations/serverpod_cloud_storage_s3/lib/src/cloud_storage.dart/s3_cloud_storage.dart
Small typo fix 
wrong: `password.yaml`
right: `passwords.yaml`
=> fix typo in filename mentioning "password.yaml" to "passwords.yaml"

packages/serverpod/lib/src/server/endpoint_dispatch.dart, packages/serverpod/lib/src/server/server.dart, packages/serverpod/lib/src/server/session.dart, packages/serverpod/test/endpoint/authentication_test.dart, tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_client/lib/src/protocol/protocol.dart, tests/serverpod_test_server/lib/src/endpoints/authentication.dart, tests/serverpod_test_server/lib/src/endpoints/signin_required.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/protocol.dart, tests/serverpod_test_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/test_e2e/authentication_test.dart, tests/serverpod_test_server/test_e2e/websocket_test.dart
- AuthenticationInfo is now accessible throug the `Session` object.
- During endpoint authentication:
- If no authentication info is returned server will response with 401 on authenticated endpoints.
- If authentication info is returned but the authenticated user is missing required endpoint scopes the server will respond with 403.
- (BREAKING) Removes `scopes` and `authenticatedUser` getter from `Session`.
This change is made to support Refresh and Access tokens in the future (JWT requires this).
New response code can be sent from the server but this is treated the same in the client currently.
Removes scopes and authenticatedUser getter from `Session` since they …
=> fix: Endpoint requests can now respond with 401 or 403 on failed authentication.

modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/signin_dialog.dart, packages/serverpod/lib/src/database/concepts/columns.dart, packages/serverpod/lib/src/database/concepts/expressions.dart, packages/serverpod/test/database/columns/column_count_test.dart, packages/serverpod/test/database/columns/column_date_time_test.dart, packages/serverpod/test/database/columns/column_double_test.dart, packages/serverpod/test/database/columns/column_duration_test.dart, packages/serverpod/test/database/columns/column_int_test.dart
- (BREAKING) Removes implicit `dynamic` to Expression conversion for `&`, `|`, `<`, `<=`, `>` and `>=`.
- (Bonus) Makes sure the authentication flutter widgets uses the min configured password length for client-side validation.
The motivation for this change is that if we would like to support more databases in the future, we might need to adapt the query language to fit their flavor.
By removing implicit casting of dynamic, we can move to a more tree based structure for the query operations that can then be translated in the database adapter layer to fit the running database.
Closes: #2254
YES - removes implicit support for dynamic to Expression conversion for `&`, …
=> fix!: Remove support for implicit string to expression conversion.

modules/serverpod_auth/serverpod_auth_server/lib/src/business/config.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/business/email_auth.dart, tests/serverpod_test_server/test_integration/authentication/auth_config_changes_test.dart
This adds another field to the  `serverpod_auth_server` modules\` `AuthConfig`.
The length of the validation code  can now be configured by setting `validationCodeLength`  when declaring the `AuthConfig` in server.dart.
default is still 8.
When 0 or a negative value is passed an Exception is thrown. 
Tests were added to check:
- if valid lengths result in a code of that length being generated and Emails.createAccountRequest returns true
- if invalid lengths result in an exception being thrown in the constructor of AuthConfig 
closes #2247
=> Make Email Verification Code Length Customizable

modules/serverpod_auth/serverpod_auth_shared_flutter/lib/src/session_manager.dart
Currently on logout, the signed in user id is not being removed from stored prefs, which makes Serverpod flutter apps think they are signed in when they are restarted after logout (during session manager initialization).
This fixes this by calling `_storeSharedPrefs` (which is obviously missing from the code).
=> Add missing `_storeSharedPrefs` in `logOut()`

modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/apple_endpoint.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/firebase_endpoint.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/google_endpoint.dart
- Fixes an issue where the scopes configured for the user info would not be respected when creating authentication token though the apple, google or firebase providers.
Unfortunately, because of the code structure this code is extremely hard to add automated tests for and have therefore not been included in the PR.
Closes: #2164 
None - fixes a scope propagation issue.
=> fix: Use user scopes from UserInfo when authenticating in all providers.

.github/workflows/dart-tests.yaml, util/pub_get_all, util/run_tests_serverpod_generate
pub_get_all script is refactored to loop all packages instead and allow for an --offline flag to be passed (very useful in worktree repos).
=> chore: Modify pub get all to support offline mode.

packages/serverpod/lib/src/server/server.dart
Fixes #2188.
Reports exceptions in the streaming message handler the same way that exceptions are reported in the endpoint handler.
=> Print streaming message handler exceptions to console

examples/auth_example/auth_example_client/lib/src/protocol/protocol.dart, examples/auth_example/auth_example_server/lib/src/generated/protocol.dart, examples/chat/chat_client/lib/src/protocol/protocol.dart, examples/chat/chat_server/lib/src/generated/protocol.dart, modules/serverpod_auth/serverpod_auth_client/lib/src/protocol/protocol.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/generated/protocol.dart, modules/serverpod_chat/serverpod_chat_client/lib/src/protocol/protocol.dart, modules/serverpod_chat/serverpod_chat_server/lib/src/generated/protocol.dart, packages/serverpod/lib/src/generated/protocol.dart, packages/serverpod_serialization/lib/src/serialization.dart, packages/serverpod_service_client/lib/src/protocol/protocol.dart, templates/serverpod_templates/modulename_client/lib/src/protocol/protocol.dart, templates/serverpod_templates/modulename_server/lib/src/generated/protocol.dart, templates/serverpod_templates/projectname_client/lib/src/protocol/protocol.dart, templates/serverpod_templates/projectname_server/lib/src/generated/protocol.dart, tests/serverpod_test_client/lib/serverpod_test_client.dart, tests/serverpod_test_client/lib/src/custom_classes.dart, tests/serverpod_test_client/lib/src/protocol/protocol.dart, tests/serverpod_test_module/serverpod_test_module_client/lib/src/protocol/protocol.dart, tests/serverpod_test_module/serverpod_test_module_server/lib/src/generated/protocol.dart, tests/serverpod_test_server/config/generator.yaml, tests/serverpod_test_server/lib/server.dart, tests/serverpod_test_server/lib/src/custom_classes.dart, tests/serverpod_test_server/lib/src/generated/protocol.dart, tests/serverpod_test_server/test_e2e/connection_test.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart
Removes unnecessary code
customConstructor is no longer available on the Protocol class.
Custom classes should instead be registered the way we have documented.
=> fix!: Remove customConstructor map from protocol class.

packages/serverpod/lib/src/server/serverpod.dart
Removes a useless stacktrace that just fills up the log when the servers are not correctly configured. It looks like this, and it doesn't help diagnose anything, other than what's in the error message.
```
INFO 2024-05-20T23:26:57.791531610Z [resource.labels.instanceId: serverpod-production-pbqx] startup-script: Failed to connect to the database. Retrying in 10 seconds. SocketException: Connection timed out, host: database.clicksocial.app, port: 5432
INFO 2024-05-20T23:26:57.791677662Z [resource.labels.instanceId: serverpod-production-pbqx] startup-script: #0 _NativeSocket.connect.<anonymous closure>.<anonymous closure> (dart:io-patch/socket_patch.dart:990)
INFO 2024-05-20T23:26:57.791713295Z [resource.labels.instanceId: serverpod-production-pbqx] startup-script: #1 _rootRun …
```
=> Remove useless stacktrace print

modules/serverpod_auth/serverpod_auth_server/pubspec.yaml, templates/pubspecs/modules/serverpod_auth/serverpod_auth_server/pubspec.yaml
- Locks the googleapis_auth package version to less than the breaking change that was introduced in the minor version.
Issue reported on google repo here: https://github.com/google/googleapis.dart/issues/622
Closes: #2305
None.
=> chore: add range for googleapis_auth.

packages/serverpod_client/lib/src/serverpod_client_shared.dart
Currently web socket errors are not reported to stderr in most cases (although in one strange case, they are reported and not caught by the caller: https://github.com/dart-lang/sdk/issues/55664 )
This PR prints websocket errs to stderr.
Solves #1679.
=> Report websocket errors to stderr

packages/serverpod_client/lib/src/serverpod_client_shared.dart
Add missing `_notifyWebSocketConnectionStatusListeners` call when websocket is closed by client.
=> Add missing _notifyWebSocketConnectionStatusListeners

modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/signin_dialog.dart
This PR adds the option to show/hide the password on the SignInWithEmailDialog. 
Tries to close #1707 
I wanted to add some WidgetTests, but got an error, when tapping "I have an account" within the test. 
This error appears in debug mode when the screen is not wide enough. 
```
The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the
rendering with a yellow and
black striped pattern. This is usually caused by the contents being too big
for the RenderFlex.
Consider applying a flex factor (e.g. using an Expanded widget) to force the
children of the
RenderFlex to fit within the available space instead of being sized to their
natural size.
This is considered an error condition because it indicates that there is …
```
=> SignInWithEmailDialog allow to toggle obscure password

modules/serverpod_auth/serverpod_auth_server/lib/src/business/users.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/google_endpoint.dart
Delay the call to `onUserCreated` if signing up with google and we request additional access to the google apis. This makes it possible to use the google API in the `onUserCreated` callback.
Additional thoughts for the future: 
* The session object does not contain the userId when the callback is made. It would not be too hard to add this but the problem is that the email auth flow is not signing in users when we create the account. Hence the session object could be populated with some providers but not with others.
* If the callback throws (user code) we don't catch that. This might be reasonable, but we are in a half complete state in some situations where the user is created but we have not created any refresh tokens. This may be the desired behavior but could be a problem, I'm not …
=> fix: Allow usage of user related google api calls in onUserCreated callback.

packages/serverpod_client/lib/src/connectivity_monitor.dart, packages/serverpod_client/lib/src/serverpod_client_shared.dart
Currently the client sends multiple notifications of `connecting` status. It should only notify listeners if the streaming connection status actually changes (which is what this PR does).
I also applied the same fix to `ConnectivityMonitor`.
=> Only notify listeners if connection status actually changes

packages/serverpod_client/lib/src/serverpod_client_shared.dart
Add missing `await _webSocket!.ready` after `WebSocketChannel.connect`.
(See docs for `WebSocketChannel.connect`)
=> Add missing await _webSocket!.ready after WebSocketChannel.connect

packages/serverpod/lib/src/server/server.dart
Once you expose a server to the Internet, you get all sorts of crawlers hitting your site. This small change properly handles a bad websocket upgrade request by sending back BadRequest rather than throwing an exception (which causes the server debugger process to stop on uncaught exception).
=> Handle bad websocket upgrade requests

packages/serverpod/lib/src/server/session.dart
- Adds back a getter for the authenticaiton key that was accidentally removed during some refactoring work around authentication.
Closes: #2327 
None - adds a simple getter.
=> fix: Add getter for authentication key.

templates/pubspecs/tools/serverpod_cli/pubspec.yaml, tools/serverpod_cli/lib/src/downloads/resource_manager.dart, tools/serverpod_cli/lib/src/internal_tools/analyze_pubspecs.dart, tools/serverpod_cli/lib/src/runner/serverpod_command.dart, tools/serverpod_cli/lib/src/update_prompt/prompt_to_update.dart, tools/serverpod_cli/pubspec.yaml
- Updates the usage of Pub API client to use exceptions instead of callbacks to handle errors.
- Updates the usage of Local Storage Manager to use exceptions instead of callbacks to handle errors.
- Uses the BetterCommand abstract class to do correct terminal width print bindings.
- Bumps the cli_tools dependency to 0.1.0.
None - just a dependency bump.
=> fix: Bump cli tools dependency.

packages/serverpod/lib/src/database/adapters/postgres/value_encoder.dart
Change the value encoder to postgres to set the offset and length of byte data.
none
=> fix: Att offset checking of value encoder to bytedata.

packages/serverpod/pubspec.yaml, templates/pubspecs/packages/serverpod/pubspec.yaml
Changed because the `TxSession` object is not available in postgres 3.0.0.
=> postgres package upgrade

modules/serverpod_auth/serverpod_auth_apple_flutter/pubspec.yaml, templates/pubspecs/modules/serverpod_auth/serverpod_auth_apple_flutter/pubspec.yaml
Allows a range for the `sign_in_with_apple` package.
Since the Serverpod implementation does not directly depend on any changes between version 5 and 6 in the package we can allow a range there.
Version 6 has dart 3.3 as minimum required version, so opting for a range instead of a direct bump to allow users to still use dart 3.2 if they prefer.
=> sign_in_with_apple pacakge version update

modules/serverpod_auth/serverpod_auth_server/lib/src/business/email_auth.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/business/google_auth.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/google_endpoint.dart
Removes `asserts` in the auth module in favor of throws and logs.
none
=> fix: Replace asserts in auth module with throws / logs.

modules/serverpod_auth/serverpod_auth_server/lib/src/business/config.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/business/email_auth.dart, tests/serverpod_test_server/test_integration/authentication/auth_config_changes_test.dart
* The default expiration time for the validation code is now 15 minutes (down from 24 hours).
* A warning is printed if the validation code is less than 8 chars.
* The minimum validation code length is now 4 chars.
* The validation now contains a-z, A-Z, 0-9.
The default values of the auth module has been change, and the minimum validation code length has been increase from 1 to 4.
=> fix!: Change default values for auth config.

modules/serverpod_auth/serverpod_auth_server/lib/src/business/email_auth.dart
Removes the verification code in db when resetPassword endpoint is called.
Closes: https://github.com/serverpod/serverpod/issues/2360
None
=> fix: Remove password reset verification code onusage attempt.

packages/serverpod/lib/src/server/serverpod.dart
Call stop on the webserver when shutdown on the serverpod object is called.
=> fix: Stop webserver when shutdown is called.

examples/auth_example/auth_example_server/aws/terraform/database.tf, examples/auth_example/auth_example_server/docker-compose.yaml, examples/chat/chat_server/aws/terraform/database.tf, examples/chat/chat_server/docker-compose.yaml, templates/serverpod_templates/projectname_server_upgrade/deploy/aws/terraform/database.tf, templates/serverpod_templates/projectname_server_upgrade/docker-compose.yaml, tests/docker/tests_e2e/docker-compose.yml, tests/docker/tests_e2e_migrations/docker-compose.yml, tests/docker/tests_integration/docker-compose.yml, tests/serverpod_test_server/docker-local/docker-compose.yml
An issue reported that Postgres version 14.2 is no longer available from Amazon RDS making the supplied terraform script fail when used.
- Bumps the Postgres version used in the aws terraform scripts from 14.2 -> 16.3: https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-versions.html#postgresql-versions-version163.
- Bumps the Postgres version in all docker composes.
Closes: #2375 
None - simple configuration change that will affect users creating new projects.
=> chore: Bump postgres version to 16.3.

packages/serverpod/lib/src/database/database_pool_manager.dart, packages/serverpod/lib/src/relic/web_server.dart, packages/serverpod/lib/src/server/server.dart, packages/serverpod/lib/src/server/serverpod.dart, packages/serverpod/lib/src/server/websocket_request_handler.dart, tests/docker/tests_integration/docker-compose.yml, tests/serverpod_test_server/lib/test_util/test_serverpod.dart, tests/serverpod_test_server/test_integration/websocket_connection_test.dart, util/run_tests_integration
Collection of improvements related to WebSockets and their lifetime management.
- Correctly set session logs to current endpoint when connection is being closed.
- Only log failed websocket upgrade requests if logging verbose is enabled.
- Break out websocket request handling to separate file.
- Make server shutdown async and await all HTTP close calls.
- Close database pool on server shutdown.
- Close all websocket connections on server shutdown.
After these changes, the server can now be gracefully shut down. This was a required change in order to test the websocket lifetime management on the server. This also means we should no longer have to have the `exit(0)` call inside of the shutdown method.
Best reviewed commit by commit to be able to follow the refactoring and break out of the …
=> fix: Websocket lifetime improvements

packages/serverpod/lib/src/server/server.dart, packages/serverpod/lib/src/server/websocket_request_handlers/endpoint_websocket_request_handler.dart, packages/serverpod/lib/src/server/websocket_request_handlers/method_websocket_request_handler.dart, packages/serverpod_serialization/lib/serverpod_serialization.dart, packages/serverpod_serialization/lib/src/websocket_messages.dart, packages/serverpod_serialization/test/websocket_messages_test.dart, tests/serverpod_test_server/lib/test_util/config.dart, tests/serverpod_test_server/test_e2e/json_protocol_test.dart, tests/serverpod_test_server/test_integration/websockets/endpoint_websocket_connection_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websocket_connection_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/bad_request_command_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/invalid_command_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/ping_pong_command_test.dart, tests/serverpod_test_server/test_integration/websockets/mixed_websocket_connection_test.dart
Introduces a new Web Socket connection endpoint '/v1/websocket` that will be used to implement #2338.
- Serverpod now accepts websocket connection on `/v1/websocket`.
- Introduce WebSocket messages to the serialization package to give a standardized way of communicating over the websocket.
- Add ping/pong command to new websocket connection point.
This PR depends on: https://github.com/serverpod/serverpod/pull/2397
None - this is a new websocket endpoint.
=> feat: Introduce new websocket connection endpoint.

packages/serverpod/lib/src/server/future_call_manager.dart, packages/serverpod/lib/src/server/serverpod.dart
When shutting down the server we did not await any pending future calls which could lead to lost data.
I encountered this during integration tests where the server was started and stopped multiple times in quick succession.
This PR introduces a mechanism for awaiting pending future calls and prevents additional ones from being started during shutdown.
No tests added since we don't really have the infrastructure for it around future calls.
None.
=> fix: add mechanism for awaiting pending future calls on shutdown

packages/serverpod/lib/src/database/database_pool_manager.dart, packages/serverpod/lib/src/server/serverpod.dart
A recent change (https://github.com/serverpod/serverpod/pull/2397)  separated establishing a database connection from creating the Serverpod instance.
This behavior breaks the possibility of doing database operations without starting the Server. And feature such as just registering FutureCall methods require a database connection in order to function which is a breaking change.
This PR re-introduced the possibility of establishing a database connection when instantiating the Serverpod instance.
None - Revevert of a previous change to prevent a breaking change.
=> fix: Start database pool manager on Serverpod instance creation.

packages/serverpod/lib/src/server/endpoint_dispatch.dart, packages/serverpod/lib/src/server/websocket_request_handlers/method_websocket_request_handler.dart, tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_server/lib/src/endpoints/method_streaming.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/test_integration/websockets/method_websockets/close_method_stream_command_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_stream_message_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/open_method_stream_command_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/throwing_method_endpoint_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/void_response_endpoint_test.dart, tools/serverpod_cli/lib/src/analyzer/dart/definitions.dart, tools/serverpod_cli/lib/src/analyzer/dart/endpoint_analyzers/endpoint_method_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/dart/endpoint_analyzers/endpoint_parameter_analyzer.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart, tools/serverpod_cli/lib/src/generator/types.dart, tools/serverpod_cli/lib/src/test_util/builders/method_definition_builder.dart, tools/serverpod_cli/lib/src/test_util/builders/type_definition_builder.dart, tools/serverpod_cli/test/generator/dart/client_code_generator/protocol_test.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/endpoints_test.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/protocol_test.dart, tools/serverpod_cli/test/generator/yaml/endpoint_description_test.dart, tools/serverpod_cli/test/integration/analyzer/dart/endpoint_validation/endpoint_method_parameter_test.dart, tools/serverpod_cli/test/integration/analyzer/dart/endpoint_validation/endpoint_method_test.dart
Another stepping stone towards #2338.
This PR introduces Server support for endpoints that have a Stream return value.
It also prepares for supporting single and void response type from Streaming method endpoints once Streaming parameters are supported.
This PR includes the Parsing, Code generation and validation required to configure an endpoint with a Streaming return value.
- An assumption is made that once an exception has been thrown from a Streaming endpoint we will close the connection to the client. The connection will either receive a an optional SerializableException message before a CloseStream message with reason type Error.
- A new base class for MethodConnectors have been introduced. The reason the base class is not called the more fitting name `MethodConnector` is that this …
=> feat: Server support endpoints with Stream return.

packages/serverpod/lib/src/server/session.dart
Adds a random uuid to sessions.
Motivation is to get traceability of sessions internally which gives us the ability to link a session directly with logs and client requests.
none
=> feat: Add a random generated id to sessions.

modules/serverpod_auth/serverpod_auth_google_flutter/lib/src/auth.dart
This PR enhances the exception handling in the SignInWithGoogle process by rethrowing exceptions. This will allow us to differentiate between the types of exceptions that occur, including distinguishing between an actual error and a user cancellation.
closes #2417
=> feat: Improve error handling in SignInWithGoogle by rethrowing exceptions

examples/auth_example/auth_example_server/lib/src/generated/endpoints.dart, examples/chat/chat_server/lib/src/generated/endpoints.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/generated/endpoints.dart, modules/serverpod_chat/serverpod_chat_server/lib/src/generated/endpoints.dart, packages/serverpod/lib/src/generated/endpoints.dart, templates/serverpod_templates/modulename_server/lib/src/generated/endpoints.dart, templates/serverpod_templates/projectname_server/lib/src/generated/endpoints.dart, tests/serverpod_test_module/serverpod_test_module_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart
Removes a temporary variable added to make it possible to do streaming calls to normal MethodConnectors.
Now that support for MethodStreamConnector is added this is no longer needed.
Making it possible to call MethodConnectors from a streaming call will be achieve in a different way.
None- this was an optional field introduced on main but never released.
=> fix: Remove temporary return type bool for MethodConnectors.

modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/signin_dialog.dart
Since the validation code is alpha numeric the KeyboardType in the `SignInWithEmailDialog`  needs to be updated otherwise the code can't be entered directly.  
_not linked to an issue_
no breaking changes
=> SignInWithEmailDialog: Update KeyboardType for validationCode 

tests/serverpod_test_server/test_integration/logging/endpoint_stream_logging_test.dart
Adds a small delay after the test action is completed so that any potential logs have time to be written to the database.
None - simple test fixes.
=> test: Fix flaky streaming log tests.

packages/serverpod/lib/src/server/websocket_request_handlers/method_websocket_request_handler.dart, packages/serverpod_serialization/lib/src/websocket_messages.dart, packages/serverpod_serialization/test/websocket_messages_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/close_method_stream_command_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_return_websocket_connection_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_stream_message_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_stream_serializable_exception_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/in_out_endpoint_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/multiple_input_streams_endpoint_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/void_return_endpoint_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/open_method_stream_command_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/open_method_stream_response_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/ping_pong_command_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/throwing_method_endpoint_test.dart
Related to #2338 
- Encodes all method stream messages with encoding for the protocol to ensure that server-only fields are not leaked.
- Only encode serializable objects once by utilising wrapWithClassName instead of taking a string for message creation.
- Write any method stream errors to stderr.
None: touches unreleased features.
=> fix: Encode method stream messages with encode for protocol.

packages/serverpod/lib/src/server/websocket_request_handlers/method_websocket_request_handler.dart, packages/serverpod_serialization/lib/src/websocket_messages.dart, packages/serverpod_serialization/test/websocket_messages_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/invalid_command_test.dart
Another stepping stone towards #2338.
- ~~Adds a single digit version to websocket messages.~~
- ~~Add tests for this change.~~
~~This will allow us to update WebSocket messages in the future allowing us to possibly support multiple clients along with deprecating old ones.~~
After the review it was concluded that we can probably do a version handshake as part of the WebSocket upgrade request and therefore we can skip versioning all together at this stage.
The PR now contains the grouping of the metadata for the messages.
None - these are changes related to a non-released feature.
=> fix: Improve Method Stream Websocket Message data structure.

tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_server/lib/src/endpoints/method_streaming.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_stream_message_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/dynamic_stream_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/nullable_stream_test.dart, tools/serverpod_cli/lib/src/analyzer/dart/endpoint_analyzers/endpoint_method_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/dart/endpoint_analyzers/endpoint_parameter_analyzer.dart, tools/serverpod_cli/test/integration/analyzer/dart/endpoint_validation/endpoint_method_parameter_test.dart, tools/serverpod_cli/test/integration/analyzer/dart/endpoint_validation/endpoint_method_test.dart
Connected to #2338 
- Add support for nullable types in streams now that we support deserializing and serializing streams.
- Add support for dynamic types in streams.
None - this touches unreleased features.
=> fix: Support nullable and dynamic types in streams.

packages/serverpod/lib/src/server/endpoint_dispatch.dart, packages/serverpod/lib/src/server/websocket_request_handlers/method_websocket_request_handler.dart, packages/serverpod/test/endpoint/parse_parameters_test.dart, packages/serverpod/test/endpoint/parse_requested_input_streams_test.dart, packages/serverpod_serialization/lib/src/websocket_messages.dart, packages/serverpod_serialization/test/websocket_messages_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websocket_connection_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/close_method_stream_command_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_return_websocket_connection_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_stream_message_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_stream_serializable_exception_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/dynamic_stream_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/in_out_endpoint_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/multiple_input_streams_endpoint_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/nullable_stream_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/void_return_endpoint_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/open_method_stream_command_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/throwing_method_endpoint_test.dart, tools/serverpod_cli/lib/src/analyzer/dart/endpoint_analyzers/endpoint_parameter_analyzer.dart, tools/serverpod_cli/test/integration/analyzer/dart/endpoint_validation/endpoint_method_parameter_test.dart
Another stepping stone towards #2338:
To preserve backwards compatibility for an endpoint, new parameters are added as optional. However, adding a new parameter as a stream parameter would break compatibility with existing clients by transforming the endpoint from a method call to a method stream.
To prevent this unexpected API-breaking change, we will not allow stream parameters to be nullable.
Since this issue is solvable (e.g., by allowing method calls to invoke streams without the optional stream parameter), we will add information to the OpenMethodStreamCommand listing the stream parameters the stream should open. This approach enables future support for nullable streams without breaking the current protocol.
- Adds the input streams that should be opened to the …
=> fix: Handle nullable stream parameters for Method Streams.

packages/serverpod_client/lib/src/serverpod_client_shared.dart
While implementing the new method streams, I noticed that we had accidentally added a dependency towards `dart:io` in some shared client code used inside the browser client.
This PR removes that dependency.
I find it very strange that our browser tests don't pick this issue up.
None.
=> fix: change stderr writeline to print and remove dart:io dependency.

modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/google_endpoint.dart
While trying to work around sign in with Google on Windows using [google_sign_in_dartio](https://pub.dev/packages/google_sign_in_dartio), I managed to sign in thru the windows frontend but failed on back end. After some digging into the auth module, I found that it was caused by the `authenticateWithIdToken` function in `google_endpoint.dart` failing to verify a valid ID token with `iss` equals `https://accounts.google.com`.
According to [Verify the Google ID token on your server side](https://developers.google.com/identity/gsi/web/guides/verify-google-id-token):
> The value of `iss` in the ID token is equal to `accounts.google.com` or `https://accounts.google.com`.
This PR fixed #2536 auth issues related to ID token flow.
It may also fixed #2354, but I do not have a Mac device to verify …
=> fix: Verify Google ID Token correctly

packages/serverpod/lib/src/relic/web_server.dart, packages/serverpod/lib/src/server/endpoint_dispatch.dart, packages/serverpod/lib/src/server/session.dart
Depends on: https://github.com/serverpod/serverpod/pull/2483
- Adds a Web server specific Session class
- Refactors the MethodCallSession to parse the HTTP request outside of the session constructor.
Motivation:
The idea is to move all the parsing away from the session creation. The web server and the endpoint dispatcher were using the same session object but in reality, used very different data and logic internally by a lot of branching. Hence splitting them into to distinct classes makes this more obvious.
Discussion point:
What to call this new session? The current name is `WebCallSession` but it doesn't feel like a great name.
Review notes:
The WebCallSession only supports auth tokens via cookie or query params. This is behavior is preserved from the previous implementation. Meaning …
=> fix: Create a standalone Session class for the webserver.

packages/serverpod/lib/src/server/log_manager/log_manager.dart, packages/serverpod/lib/src/server/session.dart, packages/serverpod/lib/src/server/websocket_request_handlers/endpoint_websocket_request_handler.dart, tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_server/lib/src/endpoints/logging.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/test_integration/logging/endpoint_call_logging_test.dart, tests/serverpod_test_server/test_integration/logging/endpoint_stream_logging_test.dart
Moves the currentMessageId from StreamingSession to the base session.
Fixes a bug where the messageId was not recorded for logged database queries.
Motivation for this change is that we want a generic way to deal with the message id rather than having to cast types as this functionality needs to be supported in more than one session.
There is an argument to be made that this id could be handled in the logger instead and have a similar logic to the session logs life cycle. Meaning each message would require an "open" and a "close" method. But this would make this much more complex. Reason for this is that we are writing the logs before we write the message log. Message log being the message received on the stream. The reason for this order is that the message log also records the execution …
=> refactor: Move currentMessageId into the base session.

packages/serverpod/lib/src/server/log_manager/log_manager.dart, packages/serverpod/lib/src/server/log_manager/session_log_cache.dart, tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_server/lib/src/endpoints/logging.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/test_integration/logging/endpoint_call_logging_test.dart
Moves the query counter into the log manager.
Motivation is that the cache class will be deleted and replaced with a different system.
Related issue: https://github.com/serverpod/serverpod/issues/2450
none
=> refactor: Move query counter to the log manager.

packages/serverpod/lib/src/server/log_manager/log_manager.dart, tests/serverpod_test_server/test_integration/logging/endpoint_call_logging_test.dart, tests/serverpod_test_server/test_integration/logging/endpoint_stream_logging_test.dart
Fixes two bugs, one where two log entries were created if the session was very short-lived, e.g. the open log was called at the same time as the finalized logs. This meant that the logs where not collected to the same session and it looked like two different sessions was executed.
The second bug was related to database queries where they may be in transit when the finalize logger was called. This resulted in no logs being recorded. This is fixed by collecting all logging tasks and awaiting any pending jobs before starting the finalize sequence. 
Related issue: https://github.com/serverpod/serverpod/issues/2450
none
=> fix: Await all logging has completed before finalizing the session.

packages/serverpod/lib/src/relic/routes/static_directory.dart
Allows `/index.html` (or any other page) to be served statically at path `/`.
=> Allow for rewrite rule for root path

packages/serverpod/lib/src/relic/routes/static_directory.dart
Solves a bug where the wrong session type cast was made in the relic web server.
none
=> fix: Invalid session type cast removed.

packages/serverpod/lib/src/server/session.dart
Removes the messageId from MethodStreamSession as we are not supporting message logging yet for this session type.
Feature is tracked here: https://github.com/serverpod/serverpod/issues/2563
none
=> fix: Remove messageId management from new stream session.

packages/serverpod/lib/src/server/future_call_manager.dart, packages/serverpod/lib/src/server/health_check.dart, packages/serverpod/lib/src/server/health_check_manager.dart, packages/serverpod/lib/src/server/log_manager/log_writers.dart, packages/serverpod/lib/src/server/serverpod.dart, packages/serverpod/lib/src/server/session.dart
Change the creation of multiple internal sessions into a single consolidated object that is reused in all places where logging was turned off for the internal session.
The only exception to this refactor is inside the auth module, where I cannot access the internal session.
Related PR: 
none
=> refactor: Create a long lived internal session instead of recreating the object.

packages/serverpod/lib/src/server/websocket_request_handlers/method_websocket_request_handler.dart, tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_server/lib/src/endpoints/method_streaming.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/test_integration/websockets/method_websockets/close_method_stream_command_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/dynamic_stream_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/in_out_endpoint_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/multiple_input_streams_endpoint_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/never_ending_yield_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/nullable_stream_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/void_return_endpoint_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/throwing_method_endpoint_test.dart
Fixes some misc bugs and corrects som tests for the new streaming method interface.
The main subject of this PR is removing the middle controller layer between the websocket and streaming methods return value.
This makes the implementation simpler and allows us to cancel the subscription of a streaming endpoint when requested by either the client or by the server.
Related issue: #2338 
None: changes related to an unreleased feature.
=> fix: Misc stream cleaninups along with proper subscription handling.

tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_server/lib/src/endpoints/method_streaming.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart, tools/serverpod_cli/test/generator/dart/client_code_generator/client_test.dart
Adds an experimental warning to client streaming methods.
Relates to: #2338 
None - simple docs fix.
=> fix: Add experimental warning to streaming methods on client.

tools/serverpod_cli/lib/src/analyzer/dart/endpoint_analyzers/endpoint_method_analyzer.dart, tools/serverpod_cli/test/integration/analyzer/dart/endpoint_validation/endpoint_method_test.dart
Restrict void in stream output of methods e.g.
```dart
Stream<void> myMethod(Session session) {
...
}
```
none
=> fix: restric void returns in streams output.

packages/serverpod/lib/src/server/message_central.dart, packages/serverpod/lib/src/server/session.dart, tests/serverpod_test_server/test_integration/message_central_test.dart
Closes: #2580 
Makes it possible to create a stream that listens to a channel in the message central.
Such as:
```dart
Stream<DeckState> deckUpdates(Session session) async* {
// Listen for changes and relay them to the client.
var stream = session.messages.createStream<DeckState>(kChannelName);
await for (var state in stream) {
yield state;
}
}
```
None: introduces a new way to subscribe to messages in the message central.
=> feat: Add possibility to create a stream subscription to message central.

packages/serverpod/lib/src/server/session.dart, tests/serverpod_test_server/test_integration/session/will_close_listener_test.dart
Closes: #2581 
Adds support for registering listeners that are called when the session is about to close.
This could become handy with the new streaming interface as such:
```dart
Stream<int> intEchoStream(Session session, Stream<int> stream) async* {
var closeLog = (Session session) {
session.log('Stream closed before completion');
};
session.addWillCloseListener(closeLog);
await for (var value in stream) {
yield value;
}
session.removeWillCloseListener(closeLog);
}
```
None - new feature on the streaming interface.
=> feat: Add support for willClose listeners on Session.

packages/serverpod_client/lib/src/client_method_stream_manager.dart, tests/serverpod_test_server/test_e2e/method_streaming/close_connection_test.dart
Mixed fixes to the clients connection handling.
- Throw exception if the client ever tries to post a message on a closed websocket connection. This will help us detect any disruptions that might occur.
- Prevent echoing a close command to the server when the server closes the streaming method.
- Prevent redundant close command when closing web socket connection.
- Add a future to wait for the web socket listen to close when closing web socket connection.
=> fix: Client streaming method connection fixes.

tools/serverpod_cli/analysis_options.yaml
When using dart `3.5.0`, the `util/run_tests_analyze --allow-infos` command fails due the following warning by the analyzer:
```
warning • test/integration/util/test_assets/pubspec_helpers/conditionally_ignored/pubspec.yaml:1:1 •
The 'name' field is required but missing. Try adding a field named 'name'. •
missing_name
```
Simply excluding the file in `tools/serverpod_cli/analysis_options.yaml` fixes it.
=> test: add exclude path to dart analyzer

modules/serverpod_auth/serverpod_auth_server/pubspec.yaml, templates/pubspecs/modules/serverpod_auth/serverpod_auth_server/pubspec.yaml
Applies the [suggested changes](https://dart.dev/tools/pub/pubspec#false_secrets) referenced in the issue: https://github.com/serverpod/serverpod/issues/2478
- Adds `false_secrets` property to `pubspec.yaml` in the `serverpod_auth_server` module
- Verified that it works by running `dart pub publish --dry-run` ✅ 
=> build: fix auth_server pub error

examples/auth_example/auth_example_server/lib/src/models/example.spy.yaml, templates/serverpod_templates/projectname_server/lib/src/models/example.spy.yaml
Updated example template files to replace old 'protocol' name with 'models'.
Closes #2598
n/a
=> fix: Updated example template files to replace old 'protocol' name with 'models'.

tools/serverpod_cli/lib/src/analyzer/dart/endpoint_analyzers/endpoint_method_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/dart/endpoint_analyzers/endpoint_parameter_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/dart/endpoint_analyzers/keywords.dart, tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart, tools/serverpod_cli/test/integration/analyzer/dart/endpoint_validation/endpoint_method_test.dart
Fixes #2557, where a public method was incorrectly interpreted as an Endpoint method. This causes the following two `sublist` calls to throw a `RangeError`:
```dart
// tools/serverpod_cli/lib/src/analyzer/dart/endpoint_analyzers/endpoint_method_analyzer.dart
if (isStream) {
return MethodStreamDefinition(
// ...
parameters: parameters.required.sublist(1), // Skip session parameter,
// ...
);
}
return MethodCallDefinition(
// ...
parameters: parameters.required.sublist(1), // Skip session parameter,
// ...
);
Additionally, for the case of a nullable `Session` (`Future<void> hello(Session? session) async {}`), there is now a hint message, see below. 
```
- Adds a test case according to the filed bug (#2557)
- Adds an additional check for named parameter in the …
=> fix: Only consider positional `Session` parameter when validating Endpoint method.

tools/serverpod_cli/lib/src/commands/analyze_pubspecs.dart, tools/serverpod_cli/lib/src/internal_tools/analyze_pubspecs.dart
Updates the hidden helper command to allow us to check if there are any new major versions out for any of the dependencies in the Serverpod mono repo.
Sample output when running the command on the state of the repo now:
```
$ serverpod analyze-pubspecs --check-latest-version --only-major --ignore-serverpod
Dependencies match.
Checking latest pub versions.
web_socket_channel
local: ^2.4.0
pub:   ^3.0.1
found in:
• serverpod_client
firebase_auth
local: ^4.4.2
pub:   ^5.1.4
found in:
• serverpod_auth_firebase_flutter
firebase_core
local: ^2.10.0
pub:   ^3.3.0
found in:
• serverpod_auth_firebase_flutter
material_design_icons_flutter
local: >=6.0.0 <7.0.0
pub:   ^7.0.7296
found in:
• serverpod_auth_firebase_flutter
• serverpod_auth_apple_flutter
email_validator
local: ^2.1.17
pub:   ^3.0.0 …
```
=> chore: Update analyze command to allow only giving warnings on new major versions.

tools/serverpod_cli/lib/src/analyzer/models/model_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/models/validation/restrictions.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/class_conflicts_test.dart
This PR fixes [#2339](https://github.com/serverpod/serverpod/issues/2339).
Adds an additional check for custom classes to the `Restrictions.validateClassName` method and returns an error in case there are collisions. Tried to keep the error message similar to the one for colliding model class names:
```
Model class collision:  "The class name "HampusCustomClass" is already used by another model class."
Custom class collision: "The class name "HampusCustomClass" is already used by a custom class (package:onboarding_todo_app_shared/onboarding_todo_app_shared.dart)."
```
- Fixes a tiny typo
- Adds validation for collisions between model class names and custom class names  …
=> fix: Validate model and custom class names collisions

tools/serverpod_cli/lib/src/analyzer/dart/definitions.dart, tools/serverpod_cli/lib/src/analyzer/dart/endpoint_analyzers/endpoint_method_analyzer.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart, tools/serverpod_cli/lib/src/test_util/builders/method_definition_builder.dart, tools/serverpod_cli/test/generator/dart/client_code_generator/client_test.dart, tools/serverpod_cli/test/integration/analyzer/dart/endpoint_validation/endpoint_method_test.dart
Deprecated annotation reflected in generated client code. Handles `@Deprecated('..')` and `@deprecated`.
Closes #2214
n/a
=> feat: Deprecated annotation reflected in generated client code.

packages/serverpod_client/pubspec.yaml, templates/pubspecs/packages/serverpod_client/pubspec.yaml
Bumps the web_socket_channel dependency from `^2.4.0` to `'>=2.4.0 <4.0.0'`.
No breaking changes for the Serverpod code.
=> chore: Bump web_socket_channel to allow '3.0.0'.

.github/dependabot.yml
Allows dependabot to create PRs for pub updates that are not compatible with the current version range.
Configures the versioning strategy to `widen` which means dependabot will atempt to widen the allowed dependency range to include the new release.
Since we are a library mono-repo we need to keep the same version for a dependency across all packages. Dependabot doesn't seem to support that sort of grouping. As a workaround we will limit the number of open pull requests to 1, this makes it easy for us to find all instances of that dependency and update it in all packages without getting spammed.
Asked a question in the Dependabot discussions around the possibility to group a dependency update for all packages here: https://github.com/dependabot/dependabot-core/discussions/10454
If you …
=> chore: Enable dependabot version update pull requests for pub.

packages/serverpod_client/lib/serverpod_client.dart, packages/serverpod_client/lib/src/client_method_stream_manager.dart, packages/serverpod_client/lib/src/method_stream/method_stream_manager_exceptions.dart, packages/serverpod_client/lib/src/serverpod_client_shared.dart, packages/serverpod_client/test/integration/method_stream_manager_connection_test.dart, tests/serverpod_test_server/test_e2e/method_streaming/close_connection_test.dart, tests/serverpod_test_server/test_e2e/method_streaming/connectivity_monitor_test.dart
- Renames and exports `MethodStreamException`; fixes #2624  and #2625
=> fix: Rename and export `MethodStreamException`

packages/serverpod_client/lib/src/serverpod_client_shared.dart, tests/serverpod_test_client/test/method_stream_call_test.dart
Fixes an issue where not all method stream exceptions would be captured and delivered through the output `Future` or `Stream`.
Added test that simulates when no server is available.
None - simple bugfix.
=> fix: Deliver method stream exceptions through the output stream.

packages/serverpod/lib/src/database/adapters/postgres/database_connection.dart, packages/serverpod/lib/src/server/server.dart, tests/serverpod_test_server/test_integration/server_restart_test.dart
Fixes two issues that prevented us from restarting a Serverpod server.
In the `database_connection` we used to create a copy of the database pool and store it locally. This caused issue when we stopped the existing database pool through the `DatabasePoolManager` since the copied reference would then be preserved towards stopped instance.
To fix the issue we now always fetch the pool from the pool manager.
As part of the server start we set the _httpServer field. This was a `late final` field, but since it was assigned every time we started the server we would get a `LateInitializationError` on the second assignment.
To fix the `final` declaration was removed since the field in essence is not final. …
=> fix: Make it possible to restart Serverpod server.

packages/serverpod/lib/src/database/adapters/postgres/database_connection.dart, tests/serverpod_test_server/test_integration/database_operations/exceptions/missing_table_test.dart
Improve the error message if a database table is missing. Motivation, if you are using our ORM you are not able to write the wrong table name (except with raw queries), and therefore the most common problem will be that you did not apply the migration before running the code.
none
=> fix: Clarify the missing table exception from postgres.

tools/serverpod_cli/lib/src/commands/generate.dart, tools/serverpod_cli/lib/src/config/config.dart
Warns if there are packages in the `<app>_server` module that are not installed, which fixes [#2384](https://github.com/serverpod/serverpod/issues/2384).
Also captures exceptions at the top level and surfaces sad-paths that were failing silently.
- Adds a warning if packages are not installed
- Prints out exceptions
=>  fix: warn if dependencies are missing when generating

packages/serverpod_serialization/lib/src/websocket_message_keys.dart, packages/serverpod_serialization/lib/src/websocket_messages.dart, packages/serverpod_serialization/test/websocket_messages_test.dart
This PR minimizes the keys used in the method stream message protocol.
The purpose is to reduce the data footprint of each message delivered on the protocol without sacrificing readability completely.
This is a breaking change to a feature that has only been released in a Beta and that is marked Experimental. Therefore we can ship breaking changes without increasing the major version.
=> fix: Minimize method stream message protocol keys.

packages/serverpod/lib/serverpod.dart
- Hides the `CloneByteData` extension, which fixes #2643 
- The removal of `clone` is technically breaking, but it's not intended to be exposed.
=> fix: Hide internal clone extension.

templates/serverpod_templates/projectname_server_upgrade/deploy/aws/scripts/install_dependencies, templates/serverpod_templates/projectname_server_upgrade/deploy/aws/scripts/run_serverpod, templates/serverpod_templates/projectname_server_upgrade/deploy/aws/scripts/start_server, templates/serverpod_templates/projectname_server_upgrade/deploy/aws/terraform/init-script.sh
This removes the installation of dart from launch template and install during code deploy. The purpose for this:
1. launch template only loads once an old instance is deleted, which means for upgrading dart, users need to delete the old machine and launch a new one which causes significant downtime
2. this allows multiple versions of dart to be installed on the instance, but only the specified one will be used to run code
For users using prior version of serverpod cli, we have commented out a section of the code in `install_dependencies`. Users can uncomment the code and upgrade their dart version on running instance. The downtime will be approximately the same as rolling out a code release
_List …
=> fix: Allow users on AWS to set/upgrade dart version.

examples/auth_example/auth_example_server/lib/src/generated/protocol.dart, examples/chat/chat_server/lib/src/generated/protocol.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/generated/protocol.dart, modules/serverpod_chat/serverpod_chat_server/lib/src/generated/protocol.dart, templates/serverpod_templates/modulename_server/lib/src/generated/protocol.dart, templates/serverpod_templates/projectname_server/lib/src/generated/protocol.dart, tests/serverpod_test_module/serverpod_test_module_server/lib/src/generated/protocol.dart, tests/serverpod_test_server/lib/src/generated/protocol.dart, tests/serverpod_test_server/test/decode_with_type_test.dart, tests/serverpod_test_server/test/encode_with_type_test.dart, tests/serverpod_test_server/test/serialization_test.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart
The generated code on the Server did not properly delegate to the Serverpod Protocol file when for calls to `getClassNameForObject` and `deserialzieByClassName`.
This made it impossible to encode and decode Serverpod-defined models.
Fixes: #2657
An important note here is that we only support encoding and decoding Serverpod defined models on the server side.
The client does not have access to the Serverpod generated client Protocol (referred to as serverpod_service_client).
Therefore no delegated call has been added to the client code.
None.
=> fix: Allow Serverpod defined models to be encoded and decoded with type.

modules/serverpod_auth/serverpod_auth_server/lib/src/business/user_authentication.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/business/users.dart, packages/serverpod/lib/src/authentication/authentication_info.dart, packages/serverpod/lib/src/generated/authentication/revoked_authentication_auth_id.dart, packages/serverpod/lib/src/generated/authentication/revoked_authentication_scope.dart, packages/serverpod/lib/src/generated/authentication/revoked_authentication_user.dart, packages/serverpod/lib/src/generated/protocol.dart, packages/serverpod/lib/src/models/authentication/revoked_authentication_auth_id.spy.yaml, packages/serverpod/lib/src/models/authentication/revoked_authentication_scope.spy.yaml, packages/serverpod/lib/src/models/authentication/revoked_authentication_user.spy.yaml, packages/serverpod/lib/src/server/message_central.dart, packages/serverpod/lib/src/server/session.dart, packages/serverpod/lib/src/server/websocket_request_handlers/method_websocket_request_handler.dart, packages/serverpod_client/lib/src/client_method_stream_manager.dart, packages/serverpod_client/lib/src/method_stream/method_stream_manager_exceptions.dart, tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_client/lib/src/protocol/protocol.dart, tests/serverpod_test_server/lib/src/endpoints/authentication.dart, tests/serverpod_test_server/lib/src/endpoints/method_streaming.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/protocol.dart, tests/serverpod_test_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/lib/test_util/test_serverpod.dart, tests/serverpod_test_server/test_e2e/method_streaming/authenticated_streaming_method_test.dart, tests/serverpod_test_server/test_e2e/method_streaming/out_future_test.dart, tests/serverpod_test_server/test_e2e/method_streaming/out_stream_test.dart, tests/serverpod_test_server/test_integration/session/revoked_authentication_test.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/revoked_authentication_stream_test.dart
For the new streaming methods, authentication for each streaming method call is done on the open stream request.
After that no further validation is required.
However, since authentication for a user can be revoked at any time, there needs to exist a way to close any stream that are utalizing a revoked authentication 
Connected to: #2338
This PR introduced a new channel (or one for each authenticated user) used for communicating revoked authentications. The Serverpod framework will then listen to updates on the authenticated information and close streams if authentication has been changed in a way that would make the streaming method unavailable for the user.
The channel is prefixed with the user ID, and three types of events can be broadcasted on the channel.
- …
=> fix: Respect authentication changes in method streams.

tests/serverpod_test_client/lib/src/protocol/client.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart, tools/serverpod_cli/test/generator/dart/client_code_generator/client_test.dart
Removes the experimental warning from method streams making them ready to be released as stable.
Closes: #2338 
None.
=> fix: Remove experimental warning from method streams.

integrations/serverpod_cloud_storage_gcp/lib/src/cloud_storage/google_cloud_storage.dart, integrations/serverpod_cloud_storage_s3/lib/src/cloud_storage.dart/s3_cloud_storage.dart, packages/serverpod/lib/src/server/serverpod.dart, packages/serverpod_shared/lib/src/password_manager.dart, packages/serverpod_shared/test/password_manager_test.dart
- Ability to register custom environment variable to be loaded into the passwords map managed by serverpod.
- Add custom envs for gcp buckets
- Add custom envs for s3 buckets
Motivation, we need to be able to load our bucket secrets from env and we want to keep these variables outside of the serverpod core. With this solution we can still centralize the logic in Serverpod without adding an implicit dependency to other packages. This also makes it possible for our users to add their own custom envs for passwords. 
Closes: #2691 
Review notes: 
Review commit by commit.
Naming on the public method `loadCustomPasswords` is important to discuss. 
none
=> feat: Ability to register custom environment variables to be loaded as a password.

packages/serverpod/test/database/columns/column_uuid_test.dart, tests/serverpod_test_client/test/copy_with_mutable_test.dart, tests/serverpod_test_server/test/generated_methods/copy_with_mutable_test.dart, tests/serverpod_test_server/test/generated_methods/to_json_for_protocol.dart, tests/serverpod_test_server/test/generated_methods/to_json_test.dart, tests/serverpod_test_server/test/serialization_test.dart
The UUID package added a deprecation warning to the `Uuid.NAMESPACE_NIL` and `UuidValue.nil` variables.
It is now recommended to use the `Namespace.nil` value from the `Enums.dart` file in the same package.
But since the downgrade version of serverpod doesn't have these values added we ignore this warning for now.
None.
=> refactor(tests): Change from deprecated member to Namespace.nil for UUID.

integrations/serverpod_cloud_storage_gcp/lib/src/aws_s3_upload/aws_s3_upload.dart, integrations/serverpod_cloud_storage_gcp/lib/src/cloud_storage/google_cloud_storage.dart, integrations/serverpod_cloud_storage_s3/lib/src/aws_s3_upload/aws_s3_upload.dart, integrations/serverpod_cloud_storage_s3/lib/src/cloud_storage.dart/s3_cloud_storage.dart, packages/serverpod/lib/src/cloud_storage/cloud_storage.dart, packages/serverpod/lib/src/cloud_storage/database_cloud_storage.dart
Use the expiration time input in the bucket and use it when creating the upload URL for s3 and gcp buckets.
Expose the maxFileSize variable for end users, this was previously hard coded at 10mb with no ability to modify this value.
=> feat: Add ability to modify maxFileSize and expiration time for gcp and aws buckets.

packages/serverpod/lib/src/server/serverpod.dart
Now allows the cloud storage endpoint to be registered even if the database storage is used in a none "private" or "public" id.
none
=> fix: Register cloud storage endpoint for any storageId with db storage.

integrations/serverpod_cloud_storage_gcp/lib/src/aws_s3_upload/aws_s3_upload.dart, integrations/serverpod_cloud_storage_s3/lib/src/aws_s3_upload/aws_s3_upload.dart
Prints a log when the status code is 4xx when uploading files to a bucket.
none
=> fix: Add log for when uploads to buckets fails.

packages/serverpod/lib/src/server/server.dart, packages/serverpod_client/lib/src/serverpod_client_exception.dart, packages/serverpod_client/lib/src/serverpod_client_shared_private.dart, packages/serverpod_client/test/exception_from_test.dart, tests/serverpod_test_server/test_integration/auth_core/auth_header_test.dart
When sending HTTP 400 Bad Request error message to the client, an error message may now be included in the client side exception.
n/a
=> fix: When sending HTTP 400 Bad Request error message to the client, an error message may now be included in the client side exception.

packages/serverpod/lib/src/server/session.dart, tests/serverpod_test_server/test_integration/session/revoked_authentication_test.dart
Closes: https://github.com/serverpod/serverpod/issues/2730
Fixes an issue where authentication revoked messages caused would throw if Redis was disabled.
These messages are now communicated locally if they can not be posted globally.
None - simple fix.
=> fix: Post revoked authentication events locally if redis is disabled.

modules/serverpod_auth/serverpod_auth_client/lib/src/protocol/client.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/business/users.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/user_endpoint.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/generated/endpoints.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/test_e2e/auth_module_test.dart
`UserInfo` has the `fullName` instance property, but there is no method of change it in the current version of `serverpod_auth`. This PR adds this functionality.
- [#2723](https://github.com/serverpod/serverpod/issues/2723)
=> feat: endpoint and methods for letting a user change its full name.

packages/serverpod/lib/src/server/message_central.dart, tests/serverpod_test_server/test_integration/websockets/method_websockets/method_streams/revoked_authentication_stream_test.dart
Fixes #2754. The revoked authentication handler removed itself inside its event handler, causing an exception to be thrown:
```log
Concurrent modification during iteration: _Set len:0.
#0      _CompactIterator.moveNext (dart:collection-patch/compact_hash.dart:714:7)
#1      MessageCentral.postMessage (package:serverpod/src/server/message_central.dart:61:28)
```
This stopped the iteration and prevented all handlers to be called. 
💡 Note that this exception was silently failing because the server will not shutdown on exceptions, but it was visible in the server log
- Simply adds `.toList` to the callback list to create a copy. This allows the event handler to remove itself (or indeed add new handlers).
- Adds test cases which were failing before the fix (by timeout, since the second stream …
=> fix: Allow event listeners to remove themselves inside their handler

examples/auth_example/auth_example_server/aws/scripts/run_serverpod, examples/chat/chat_server/aws/scripts/run_serverpod, templates/serverpod_templates/projectname_server_upgrade/deploy/aws/scripts/run_serverpod, templates/serverpod_templates/projectname_server_upgrade/deploy/gcp/console_gcr/cloud-run-deploy.sh, tests/docker/tests_e2e/run-tests.sh, tests/docker/tests_e2e/start-server.sh, tests/docker/tests_e2e_migrations/run-tests.sh, tests/docker/tests_e2e_migrations/start-server.sh, tests/docker/tests_integration/run_tests.sh, util/generate_all, util/pub_get_all, util/publish_all, util/recreate_all_migrations, util/run_tests, util/run_tests_analyze, util/run_tests_bootstrap, util/run_tests_e2e, util/run_tests_integration, util/run_tests_migrations_e2e, util/run_tests_serverpod_generate, util/run_tests_unit, util/run_tests_update_pubspecs, util/update_pubspecs
As described in [2743](https://github.com/serverpod/serverpod/issues/2743), the use of array declarations in some scripts breaks when using some `bash` versions.
[2743](https://github.com/serverpod/serverpod/issues/2743)
Since this is internal tooling, the scripts needs to be tested in the corresponding CI/CD pipes to make sure that everything works as expected.
=> fix: updated script shebangs to `/bin/bash` from `/bin/sh`.

packages/serverpod/lib/src/server/serverpod.dart, packages/serverpod_test/lib/src/test_serverpod.dart, packages/serverpod_test/lib/src/with_serverpod.dart, tests/serverpod_test_server/test_integration/test_tools/serverpod_test_tools.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/server_test_tools_generator.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/test_tools_test.dart
As a prerequisite to enabling the new `test` run mode, the `withServerpod` test tool helper needs to be able to try to `--apply-migrations` when starting `Serverpod`. This can fail, and if that happens the test should simply fail as well. Currently the process is instead exited and the test runner is closed. 
Closes #2725. 
- Adds an optional `runInGuardedZone` flag to `start` that can be set to false. Defaults to `true` to keep behavior.
- When running without the guarded zone, errors will surface to the caller of `start` instead of being kept within the guarded zone
- Adds a demonstrative test that is skipped, since it's not possible to create a test for this case.
=> fix: Enable starting `Serverpod` without exiting process

modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/user_endpoint.dart, tests/serverpod_test_server/lib/server.dart
Respect the auth configuration allowing users to change their userName, fullName and userImage.
Closes: https://github.com/serverpod/serverpod/issues/2746
Bugfix that fixes a security issue.
=> fix(authentication): Correctly checks settings before letting a user change name or image.

packages/serverpod/lib/src/server/serverpod.dart, packages/serverpod_shared/lib/src/password_manager.dart, packages/serverpod_shared/test_integration/assets/load_passwords/runner_empty_passwords.dart, packages/serverpod_shared/test_integration/assets/load_passwords/runner_missing_passwords.dart, packages/serverpod_shared/test_integration/load_passwords_test.dart, tools/serverpod_cli/lib/src/config_info/config_info.dart
Ignore the passwords.yaml file if it does not exist but still load the passwords from env if possible.
Closes: https://github.com/serverpod/serverpod/issues/2800
none
=> fix: Load passwords from env even if the passwords file does not exist.

packages/serverpod/lib/src/server/websocket_request_handlers/helpers/method_stream_manager.dart, packages/serverpod_test/lib/src/test_stream_manager.dart, tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_server/lib/src/endpoints/method_streaming.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/test_integration/method_streaming_cancel_test.dart, tests/serverpod_test_server/test_integration/test_tools/serverpod_test_tools.dart
=> fix: Correct type mismatch in onTimeout callback for subscription cancellation in MethodStreamManager closeAllStreams()

packages/serverpod/lib/src/server/endpoint_dispatch.dart, packages/serverpod/lib/src/server/server.dart, tests/serverpod_test_server/test_e2e/cloud_storage_test.dart, tests/serverpod_test_server/test_e2e/http_codes_test.dart
Fixes the issue where Serverpod server responds with HTTP code 500 instead of 400 upon wrong endpoint parameters.
Closes #2826 
Breaks previous error response behavior, but that behavior was wrong and upon discussion in team this was deemed ok.
=> fix: Fixes #2826, HTTP code 500 instead of 400 upon param errors

packages/serverpod_test/lib/src/function_call_wrappers.dart, packages/serverpod_test/lib/src/test_database_proxy.dart, packages/serverpod_test/lib/src/test_serverpod.dart, packages/serverpod_test/lib/src/test_session_builder.dart, packages/serverpod_test/lib/src/transaction_manager.dart, packages/serverpod_test/lib/src/with_serverpod.dart, tests/serverpod_test_server/test_integration/test_tools/serverpod_test_tools.dart, tools/serverpod_cli/lib/src/config/config.dart, tools/serverpod_cli/lib/src/config/experimental_feature.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/server_test_tools_generator.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/expected_files_created_test.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/test_tools_test.dart
Small changes to make the test tools work for Serverpod mini projects.
Closes #2740.  
- Adds `isDatabaseEnabled` argument to `buildWithServerpod`
- Tested and verified that it works with a Serverpod Mini project
- I didn't add an integration test here, only updated the unit test. 
- The plan is to add bootstrap tests that actually runs the example tests to ensure they pass when fixing issue #2734. I think such a test is a pragmatic way to validate this behavior for the moment.
- (The alternative would be to create a `serverpod_test_mini` project in which we can generate the test tools and write a an integration test in an authentic Serverpod mini environment, but that felt overkill right now.)
=> fix: Support test tools for mini projects

tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_client/lib/src/protocol/protocol.dart, tests/serverpod_test_client/lib/src/protocol/scopes/scope_server_only_field.dart, tests/serverpod_test_client/lib/src/protocol/scopes/scope_server_only_field_child.dart, tests/serverpod_test_server/lib/src/endpoints/server_only_scoped_field_model_child.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/protocol.dart, tests/serverpod_test_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/lib/src/generated/scopes/scope_server_only_field.dart, tests/serverpod_test_server/lib/src/generated/scopes/scope_server_only_field_child.dart, tests/serverpod_test_server/lib/src/models/scopes/scope_server_only_field_child.spy.yaml, tests/serverpod_test_server/test_e2e/json_protocol_test.dart, tests/serverpod_test_server/test_integration/test_tools/serverpod_test_tools.dart, tools/serverpod_cli/lib/src/analyzer/models/validation/restrictions.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/model_library_generator.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/inheritance_test.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/inheritance_class_test.dart
This PR tries to adjust the `SerializableModelLibraryGenerator` to handle inherited serverOnly fields correctly. As the parentClass declares them as `Object?` but the child-class parses their real type (`int`, `String` etc.) we now check in the methods building `_buildCopyWithMethod` and `_buildAbstractCopyWithMethod` and pass them to the childs copyWith method as expected
Furthermore a test case was added to `json_protocol_test.dart` making sure `serverOnly` fields are not leaked when inherited. 
Another test was added to `server_code_generator/inheritance_class_test.dart` checking if nullable fields are typed as expected in the `copyWith` method. 
And a `restriction` and `test` was added to only allow extending a `serverOnly` class if the child is marked as `serverOnly` aswell. 
linked …
=> fix: inheritance for serverOnly scoped classes and fields

packages/serverpod_test/lib/serverpod_test.dart, packages/serverpod_test/lib/src/test_encode.dart, tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_server/lib/src/endpoints/test_tools.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/test_integration/test_tools/return_and_input_types_test.dart, tests/serverpod_test_server/test_integration/test_tools/serverpod_test_tools.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/server_test_tools_generator.dart
- Fixes #2845 
- Adds a test serializer helper `testObjectToJson` that uses the same code paths as production code
- It's inefficient to go to String and then to JSON, but unless I missed something we didn't have any helpers that takes an object and returns JSON? I thought this performance hit was okay because a) it's a test and b) it's  great to know that we're taking the same code path as prod.
=> fix: Correctly encode parameters passed to test tools.

tools/serverpod_cli/lib/src/analyzer/models/validation/restrictions.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/inheritance_test.dart
This PR adds a restriction to `validateFieldName` making sure that field names are not duplicated across the hierarchy.
Furthermore a test was added to `inheritance_test.dart` testing the above mentioned restriction.
Lastly I did a little cleanup, by extracting the logic traversing up the hierarchy into a separate method `_findInParentHierarchy` that is used in the individual methods to search the hierarchy
- `_findTableClassInParentClasses`
- `_findServerOnlyClassInParentClasses`
- `_findAncestorWithDuplicatedFieldName`
-  `_findFieldWithDuplicatedName`
linked to: #1873  and #1618 
no breaking changes
=> fix: Guard against duplicated fieldNames within hierarchy

packages/serverpod/lib/src/server/endpoint_dispatch.dart, packages/serverpod/lib/src/server/websocket_request_handlers/endpoint_websocket_request_handler.dart, packages/serverpod/lib/src/server/websocket_request_handlers/helpers/method_stream_manager.dart, packages/serverpod/lib/src/server/websocket_request_handlers/method_websocket_request_handler.dart, tests/serverpod_test_module/serverpod_test_module_client/lib/src/protocol/client.dart, tests/serverpod_test_module/serverpod_test_module_server/lib/src/endpoints/streaming.dart, tests/serverpod_test_module/serverpod_test_module_server/lib/src/generated/endpoints.dart, tests/serverpod_test_module/serverpod_test_module_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/test_e2e/module_test.dart
Closes #2856.
This PR fixes two bugs 👇 
- Endpoint methods (as reported in the issue): Introduced in `2.1.1`, a typo slipped into [this refactor](https://github.com/serverpod/serverpod/commit/dd1258ca2bd91b534295f92e09de09b68b5800c7#diff-f2dab80fac9835e43d45b78a8fe2a5289e765c1f592ad611304d34ef27742f04L262) and module were not correctly scanned to do the `streamOpened` call
- Streaming methods: Introduced in `2.1.1` by [this PR](https://github.com/serverpod/serverpod/pull/2763/files#diff-f2dab80fac9835e43d45b78a8fe2a5289e765c1f592ad611304d34ef27742f04) that refactored the stream method manager. Only the endpoint name was stored in the server's stream lookup map, but the client was correctly sending the full endpoint paths (including module name) in its messages which caused the the …
=> fix: Handle method and endpoint streams for modules

templates/pubspecs/tests/serverpod_test_module/serverpod_test_module_server/pubspec.yaml, tests/docker/tests_integration/Dockerfile, tests/docker/tests_integration/run_tests.sh, tests/serverpod_test_module/serverpod_test_module_server/config/generator.yaml, tests/serverpod_test_module/serverpod_test_module_server/config/passwords.yaml, tests/serverpod_test_module/serverpod_test_module_server/config/test.yaml, tests/serverpod_test_module/serverpod_test_module_server/pubspec.yaml, tests/serverpod_test_module/serverpod_test_module_server/test/integration/module_endpoint_test.dart, tests/serverpod_test_module/serverpod_test_module_server/test/integration/test_tools/serverpod_test_tools.dart, tests/serverpod_test_server/test_integration/test_tools/serverpod_test_tools.dart, util/generate_all
This started out as a PR to support testing imported modules from a main Serverpod project. This turned out to be a bit tricky and is tracked in this issue: https://github.com/serverpod/serverpod/issues/2848
Testing modules in isolation is supported out of the box, so I simply added a test to our test module that verifies that this works.
- Adds integration test to `serverpod_test_module/serverpod_test_module_server`
- Modifies the integration test scripts to run the module tests as well
=> fix: Add integration test to module

packages/serverpod_test/lib/src/transaction_manager.dart, tests/serverpod_test_server/config/passwords.yaml, tests/serverpod_test_server/config/test.yaml, tests/serverpod_test_server/test_integration/method_streaming_cancel_test.dart, tests/serverpod_test_server/test_integration/test_tools/authentication_validation_test.dart, tests/serverpod_test_server/test_integration/test_tools/database_operations_in_endpoint_test.dart, tests/serverpod_test_server/test_integration/test_tools/protocol_test.dart, tests/serverpod_test_server/test_integration/test_tools/return_and_input_types_test.dart, tests/serverpod_test_server/test_integration/test_tools/rollback_database_test.dart, tests/serverpod_test_server/test_integration/test_tools/session_copy_with_test.dart, tests/serverpod_test_server/test_integration/test_tools/session_correctness_test.dart, tests/serverpod_test_server/test_integration/test_tools/transaction_correctness_test.dart
As explained in detail in this issue: #2850 , database exceptions are re-thrown if a transaction is allowed to complete when a database exception has occurred. This PR ensures those errors are caught when the top level test transaction completes.
We should also create a small caveat in the test docs about this. Currently the following code will throw in production code, but will complete successfully in test code:
```dart
session.db.transaction((tx) async {
var data = UniqueData(number: 1, email: 'test@test.com');
try {
await UniqueData.db.insertRow(session, data);
await UniqueData.db.insertRow(session, data);
} catch (_) {
// Ignore duplicate key exception from DB
}
});
```
While this is a theoretical inconsistency, it should very rarely (if ever) be a problem because this type of code …
=> fix: Catch database exceptions at the end of transactions.

packages/serverpod_client/lib/src/method_stream/method_stream_manager_exceptions.dart
Adds descriptions to client method stream exceptions.
None - this just adds descriptions to the client side error messages.
=> fix: Add description to client method stream exceptions.

packages/serverpod_test/lib/src/io_overrides.dart, packages/serverpod_test/lib/src/test_serverpod.dart, tools/serverpod_cli/lib/src/config/config.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/expected_files_created_test.dart
- Changes the default test tools path for Serverpod mini (out of context of the PR, but its a tiny change)
- Ignores the output of the Serverpod constructor in tests to avoid spamming the logs.
=> fix: Ignore output from Serverpod constructor in tests

packages/serverpod/lib/src/server/websocket_request_handlers/helpers/method_stream_manager.dart, tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_server/lib/src/endpoints/logging.dart, tests/serverpod_test_server/lib/src/endpoints/method_streaming.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/test_e2e/method_streaming/out_stream_test.dart, tests/serverpod_test_server/test_integration/logging/endpoint_method_stream_logging_test.dart, tests/serverpod_test_server/test_integration/test_tools/serverpod_test_tools.dart
Two issue where identified in the method stream interface:
When a streaming endpoint returns a stream instead of being a generator and an exception occurs before the stream is returned our error handling didn't manage to catch the error.
This resulted in the stream not being closed on the client and the exception being propagated up on the server.
During a refactor for how streams are closed to not produce memory leaks, closing the session with any errors that occurred was accidentally removed. PR here: https://github.com/serverpod/serverpod/pull/2573
This PR reintroduces closing sessions with errors if one has occurred.
This is tested through the logging interface since that is the only output that displays if an error has occurred in a session.
If you need help, consider asking for …
=> fix: Correctly handle errors in method streams.

tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_module/serverpod_test_module_client/lib/src/protocol/client.dart, tests/serverpod_test_module/serverpod_test_module_server/lib/src/endpoints/streaming.dart, tests/serverpod_test_module/serverpod_test_module_server/lib/src/generated/endpoints.dart, tests/serverpod_test_module/serverpod_test_module_server/lib/src/generated/protocol.yaml, tests/serverpod_test_module/serverpod_test_module_server/test/integration/test_tools/serverpod_test_tools.dart, tests/serverpod_test_server/lib/src/endpoints/test_tools.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/test_e2e/module_test.dart, tests/serverpod_test_server/test_integration/test_tools/return_and_input_types_test.dart, tests/serverpod_test_server/test_integration/test_tools/serverpod_test_tools.dart
Adds additional tests for streams for modules and test tools.
- The code path for future returning functions with stream input was not covered for modules.
- The case for methods that takes a stream and returns a stream with serializable objects was not covered
=> test: Add additional tests to modules and test tools

packages/serverpod/lib/src/server/features.dart, packages/serverpod/lib/src/server/log_manager/log_writers.dart, packages/serverpod/lib/src/server/session.dart, packages/serverpod_shared/lib/src/config.dart, packages/serverpod_shared/lib/src/environment_variables.dart, packages/serverpod_shared/test/session_logs_config_test.dart, packages/serverpod_shared/test_integration/assets/load_config/config/session_logs_db_development.yaml, packages/serverpod_shared/test_integration/assets/load_config/config/session_logs_no_db_development.yaml, packages/serverpod_shared/test_integration/assets/load_config/session_logs_db_runner.dart, packages/serverpod_shared/test_integration/assets/load_config/session_logs_no_db_runner.dart, packages/serverpod_shared/test_integration/load_session_logs_config_test.dart, tests/serverpod_test_server/config/development.yaml, tests/serverpod_test_server/config/production.yaml, tests/serverpod_test_server/test_integration/logging/endpoint_method_call_logging_test.dart, tests/serverpod_test_server/test_integration/logging/endpoint_method_stream_logging_test.dart, tests/serverpod_test_server/test_integration/logging/endpoint_stream_logging_test.dart, tests/serverpod_test_server/test_integration/logging/internal_session_logging_test.dart, tests/serverpod_test_server/test_integration/logging/override_logging_test.dart, tests/serverpod_test_server/test_integration/logging/session_logging_test.dart
This PR introduces the ability to control `session.log` output through both environment variables and configuration files. Logs can now be written to the database, the console, both, or neither, depending on configuration.
- Added support for two new environment variables:
- `SERVERPOD_SESSION_PERSISTENT_LOG_ENABLED`
- `SERVERPOD_SESSION_CONSOLE_LOG_ENABLED`
- The `sessionLogs` section in the configuration file now supports:
- `persistentEnabled`: Enable logging to the database.
- `consoleEnabled`: Enable logging to the console.
- If `persistentEnabled` is set to `true` but **no database configuration** is provided, a `StateError` will be thrown, as persistent logging requires database support. This ensures that invalid configurations are caught during initialization, preventing silent …
=> Add Configuration for Controlling `session.log` Output to DB and Console

templates/pubspecs/tools/serverpod_cli/pubspec.yaml, tools/serverpod_cli/pubspec.yaml
Bumps the code builder dependency to min version `4.5.0` so that class modifiers are supported.
This is required to support sealed classes.
None - internal change for Serverpod.
=> chore: Bump code builder dependency

tests/serverpod_test_module/serverpod_test_module_server/test/integration/test_tools/serverpod_test_tools.dart, tests/serverpod_test_server/test_integration/test_tools/serverpod_test_tools.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/server_test_tools_generator.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/test_tools_test.dart
- Sets an explicit return type in the generated test tools code to prevent linter warnings in newer dart versions
=> fix: Set explicit return type in test tools code.

packages/serverpod_test/lib/src/test_database_proxy.dart, packages/serverpod_test/lib/src/transaction_manager.dart, packages/serverpod_test/pubspec.yaml, templates/pubspecs/packages/serverpod_test/pubspec.yaml, tests/serverpod_test_server/test_integration/test_tools/database_operations_test.dart, tests/serverpod_test_server/test_integration/test_tools/transaction_correctness_test.dart
Closes #2895 .
This PR fixes another issue related to emulated nested transaction in the test tools. When an error is raised inside a transaction, the transaction is no longer valid. Therefore the test tools needs to rollback before the error happened but still re-throw it out to the code under test.
Additionally, this PR introduces a synchronized lock to enable code like this:
```dart
test(
'when creating multiple SimpleData in parallel '
'then should have inserted all', () async {
await Future.wait([
SimpleData.db.insertRow(
session,
SimpleData(num: 1),
),
SimpleData.db.insertRow(
session,
SimpleData(num: 2),
),
SimpleData.db.insertRow(
session,
SimpleData(num: 3),
),
]);
var simpleDatas = await SimpleData.db.find(session);
expect(simpleDatas, hasLength(3));
expect(simpleDatas.map((s) …
```
=> fix: Support DB exceptions outside transactions and parallel DB calls.

tests/serverpod_test_server/test_integration/test_tools/database_operations_test.dart, tests/serverpod_test_server/test_integration/test_tools/transaction_correctness_test.dart
To ensure that the test transaction are correctly passed on to database calls in `packages/serverpod/lib/src/database/database.dart`, this PR adds a simple test for each available method.
There are already other tests to verify that database calls are performed inside a transaction and are correctly rolled back. So it's enough here to prove that the database calls can observe changes made by another call (e.g. insert/find).
- Adds more database operations tests
=> test: Add database operations tests.

packages/serverpod/lib/src/relic/web_widget.dart
Replaces null assert with error check and proper error message in web_widget.dart.
n/a
=> fix: Replaced null assert with error check in web_widget

modules/serverpod_auth/serverpod_auth_server/test/integration/test_tools/serverpod_test_tools.dart, templates/serverpod_templates/modulename_server/config/test.yaml, templates/serverpod_templates/modulename_server/test/integration/test_tools/serverpod_test_tools.dart, templates/serverpod_templates/projectname_server/test/integration/test_tools/serverpod_test_tools.dart, templates/serverpod_templates/projectname_server_upgrade/config/test.yaml, templates/serverpod_templates/projectname_server_upgrade/test/integration/test_tools/serverpod_test_tools.dart, tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_module/serverpod_test_module_server/test/integration/test_tools/serverpod_test_tools.dart, tests/serverpod_test_server/config/test.yaml, tests/serverpod_test_server/lib/src/endpoints/test_tools.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/test_integration/test_tools/serverpod_test_tools.dart, tests/serverpod_test_server/test_integration/test_tools/session_correctness_test.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/server_test_tools_generator.dart
- Closes #2941 
- Enables logging for run mode `test`. This is not a very nice and sustainable solution, but there are no good solution with a reasonable effort I think. Please let me know if you think there is a better way to solve this.
- Fixes a bug where sessions weren't closed if an exception was thrown in future returning endpoints
- Fixes a bug where sessions weren't closed for any case in stream returning endpoints
NB: All sessions _were_ closed in the test frameworks' `tearDownAll`, but this is too late for the test user to make any assertions.
=> fix: Enable logging for tests and ensure session is always closed 

packages/serverpod/lib/src/server/serverpod.dart, packages/serverpod/lib/src/server/session.dart, packages/serverpod/lib/src/server/websocket_request_handlers/helpers/method_stream_manager.dart, packages/serverpod/lib/src/server/websocket_request_handlers/method_websocket_request_handler.dart
Improved Serverpod initialization log messages, and added verbose logging of method streams lifecycle events.
n/a
=> feat: Improved Serverpod startup and stream lifecycle events logging

modules/serverpod_chat/serverpod_chat_flutter/pubspec.yaml, templates/pubspecs/modules/serverpod_chat/serverpod_chat_flutter/pubspec.yaml, templates/pubspecs/tools/serverpod_cli/pubspec.yaml, tools/serverpod_cli/pubspec.yaml
Bumps the `intl` dependency from `^0.19.0` to `'>=0.19.0 <0.21.0'`
None - range allows old version of the same package.
=> chore: Bump intl dependency.

tools/serverpod_cli/lib/src/generator/code_generation_collector.dart, tools/serverpod_cli/lib/src/generator/generator.dart, tools/serverpod_cli/lib/src/generator/serverpod_code_generator.dart
Removes a the redundant file collection feature from our code generation collector.
The files generated are already returned by the affected methods.
Also scoped down the error gathering to only target the endpoints analyzer since that was the only real user of the collector.
None - changes to internal classes not intended for developers to use.
=> fix: Remove redundant file collection from code generation

tests/serverpod_cli_e2e_test/test/generate_watch_test.dart, tools/serverpod_cli/lib/src/analyzer/dart/endpoints_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/models/stateful_analyzer.dart, tools/serverpod_cli/lib/src/commands/generate.dart, tools/serverpod_cli/lib/src/config/config.dart, tools/serverpod_cli/lib/src/generator/generator.dart, tools/serverpod_cli/lib/src/generator/generator_continuous.dart, tools/serverpod_cli/lib/src/util/model_helper.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/stateful_analyzer_test.dart, tools/serverpod_cli/test/integration/analyzer/dart/endpoint_validation/update_file_context_test.dart
Uses stateful analyzers to analyze both endpoints and model files in the generator.
This PR is a preparation for supporting endpoint and model files located anywhere in the project that is tracked here  https://github.com/serverpod/serverpod/issues/964
This PR also introduces additional filtering on the watched files to only trigger a regeneration when either an endpoint or a model file is updated. This will be a necessary change once we listen to all files in the project directory to prevent unnecessary regenerations for other file changes.
A small delay was added to generate files so that multiple changes are batched together. For example, when a file is moved from one folder to another, this creates an `add` and a `remove` event, which could introduce an invalid state if they are …
=> fix: Use statefull analyzers in generator

tools/serverpod_cli/lib/src/util/model_helper.dart, tools/serverpod_cli/test/integration/util/model_helper_test.dart
Found some false positives in our tests and "completed" the implementation so that a valid response is always returned.
=> fix: Return same uri when extracting path from model outside of allowed directory.

tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/endpoints_test.dart
Same fix as https://github.com/serverpod/serverpod/pull/2993 but targetting the 2.2 stable branch.
None.
=> fix: Use valid dart import paths for endpoints on all platforms.

tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/endpoints_test.dart
Closes: #2990 
Fixes an issue where we would build a platform dependent import path for the import path in the dart files.
None - fixes an issue introduced with the previous release.
=> fix: Use valid dart import paths for endpoints on all platforms. 

tools/serverpod_cli/lib/src/generator/dart/library_generators/server_test_tools_generator.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/test_tools_test.dart
Closes: https://github.com/serverpod/serverpod/issues/2999
Fixes dart-compatible path imports for all platforms in the test tools.
None - fixes an import issue.
=> fix: Use dart compatible paths for test tools imports.

packages/serverpod/lib/src/cloud_storage/public_endpoint.dart, packages/serverpod_shared/lib/annotations.dart, packages/serverpod_shared/lib/serverpod_shared.dart, packages/serverpod_shared/lib/src/annotations.dart, tests/serverpod_cli_e2e_test/test/generate_watch_test.dart, tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/lib/src/my_feature/endpoints/my_feature_endpoint.dart, tests/serverpod_test_server/test_e2e/endpoint_test.dart, tests/serverpod_test_server/test_integration/test_tools/serverpod_test_tools.dart, tools/serverpod_cli/lib/src/analyzer/dart/endpoint_analyzers/endpoint_class_analyzer.dart, tools/serverpod_cli/lib/src/commands/generate.dart, tools/serverpod_cli/lib/src/config/config.dart, tools/serverpod_cli/lib/src/generator/generator_continuous.dart, tools/serverpod_cli/test/integration/analyzer/dart/endpoint_validation/endpoint_ignore_annotation_test.dart
Adds support for placing endpoint files anywhere in the project.
This PR also introduces a new annotation that allows developers to exclude endpoint definitions from being generated by the project.
Part of: #964 
None - This is implemented as a new feature to the framework.
=> feat: Support free endpoint definition placement

tools/serverpod_cli/lib/src/analyzer/models/model_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/models/stateful_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/models/validation/model_relations.dart, tools/serverpod_cli/lib/src/analyzer/models/validation/model_validator.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/file_name_conflicts_test.dart
Improves the error message displayed when a generated file collision is detected.
None - simple improvement to the error message.
=> fix: Improve error description on generated file collision

.github/workflows/dart-tests.yaml, tests/bootstrap_project/lib/src/util.dart, tests/bootstrap_project/test/module_test.dart, tests/bootstrap_project/test/project_mini_test.dart, tests/bootstrap_project/test/project_test.dart, tools/serverpod_cli/lib/src/util/pubspec_helpers.dart
Adds windows as a platform that the bootstrap tests are run on.
Unfortunately Github actions runs docker with windows containers and the postgres does not supply a windows container. Therefore, the tests that start the container are skipped on windows: https://github.com/docker-library/postgres/issues/324
This should still provide us with 90% of the confidence since the only difference between starting the database connection in windows and UNIX is the dart runtime which we are not changing.
We still have a test that validates running the mini project on windows and executing all of the tests.
**Additional fix** 
- Fixes an issue where symlinks would break serverpod version compatibility check. We really only need to do this check one level down so this should not be an issue.
If you need …
=> ci: Add windows to bootstrap test platforms.

tools/serverpod_cli/lib/src/generator/types.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/field/field_datatype_test.dart
Implements a stricter check to ensure that the projectModelDefinition field is only assigned to a model that is part of the project.
If this check is missing, an invalid reference might be generated. This could happened if there was a class name collision with a Serverpod model.
One such example was a project with a `Filter` model, which was used as a field in another model. When the project was loaded, the Serverpod definitions of the `filter`model were loaded first, so it was assigned as the 'projectModelDefinition` value.
This fix should also be applied to the `Stable-2.2` branch.
Created an issue to fix this "potential" issue in the other places as well: https://github.com/serverpod/serverpod/issues/3019 …
=> fix: Only assign project model definitions to project models.

tools/serverpod_cli/lib/src/generator/types.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/field/field_datatype_test.dart
Same fix as https://github.com/serverpod/serverpod/pull/3018 but for the 2.2 stable branch.
Description in the other PR.
None - fixes an issue.
=> fix: Only assign project model definitions to project models. 

examples/auth_example/auth_example_server/aws/scripts/install_dependencies, examples/chat/chat_server/aws/scripts/install_dependencies, templates/serverpod_templates/projectname_server_upgrade/deploy/aws/scripts/install_dependencies
This PR refactors the Dart installation and systemd service setup script with the following improvements:
- Added dynamic variables for `USERNAME` and `WORKDIR` to enhance flexibility.
- Removed redundant `WantedBy=multi-user.target` from the systemd service file.  
**Reason**: `network-online.target` already depends on `multi-user.target`, making the explicit inclusion of `multi-user.target` unnecessary. This simplifies the service file without changing its behavior.
- Ensured all Dart binaries are symlinked to `/usr/local/bin` for easier access.
- Introduced error handling with `set -e` to stop execution on any failure.
- Improved overall code readability and maintainability without changing functionality.
Closes: #2884  …
=> Refactor: Improve Dart Installation and Serverpod Systemd Service Setup Script

packages/serverpod/pubspec.yaml, templates/pubspecs/packages/serverpod/pubspec.yaml
A new major version of vm_service was released so this PR bumps the range to allow the new version from `">=13.0.0 <15.0.0"` to `">=13.0.0 <16.0.0"`
None - simple widening of the dependency range.
=> chore: bump vm_service dependency range

templates/pubspecs/tools/serverpod_cli/pubspec.yaml, tools/serverpod_cli/lib/src/downloads/resource_manager.dart, tools/serverpod_cli/pubspec.yaml
Widens the archive dependency range to allow the newly released `4.0.1` version.
None - simple dependency range bump with no implications.
=> chore: Bump archive dependency

templates/pubspecs/tools/serverpod_cli/pubspec.yaml, tools/serverpod_cli/pubspec.yaml
Bumps the dependency range for pub_api_client from `'^2.4.0'` to `'>=2.4.0 <4.0.0'`
None - new versions should be compatible with the code currently in place.
=> chore: Bump pub_api_client dependency.

packages/serverpod/lib/src/server/serverpod.dart
Adding awareness of the optional environment variable SERVERPOD_DEPLOY_TAGS, which a deployment environment can use to provide metadata to the serverpod process in tags format. 
For example:
```bash
SERVERPOD_DEPLOY_TAGS="buildNumber=42,provider=GCP"
```
Upon start, Serverpod will log the content:
```
SERVERPOD deploy tags: buildNumber=42,provider=GCP
```
n/a
=> feat: Support for SERVERPOD_DEPLOY_TAGS

examples/auth_example/auth_example_server/migrations/20241219152445123/definition.json, examples/auth_example/auth_example_server/migrations/20241219152445123/definition.sql, examples/auth_example/auth_example_server/migrations/20241219152445123/definition_project.json, examples/auth_example/auth_example_server/migrations/20241219152445123/migration.json, examples/auth_example/auth_example_server/migrations/20241219152445123/migration.sql, examples/auth_example/auth_example_server/migrations/migration_registry.txt, examples/chat/chat_server/migrations/20241219152439582/definition.json, examples/chat/chat_server/migrations/20241219152439582/definition.sql, examples/chat/chat_server/migrations/20241219152439582/definition_project.json, examples/chat/chat_server/migrations/20241219152439582/migration.json, examples/chat/chat_server/migrations/20241219152439582/migration.sql, examples/chat/chat_server/migrations/migration_registry.txt, modules/serverpod_chat/serverpod_chat_server/migrations/20241219152420529/definition.json, modules/serverpod_chat/serverpod_chat_server/migrations/20241219152420529/definition.sql, modules/serverpod_chat/serverpod_chat_server/migrations/20241219152420529/definition_project.json, modules/serverpod_chat/serverpod_chat_server/migrations/20241219152420529/migration.json, modules/serverpod_chat/serverpod_chat_server/migrations/20241219152420529/migration.sql, modules/serverpod_chat/serverpod_chat_server/migrations/migration_registry.txt, tests/serverpod_test_module/serverpod_test_module_server/migrations/20241219152628926/definition.json, tests/serverpod_test_module/serverpod_test_module_server/migrations/20241219152628926/definition.sql, tests/serverpod_test_module/serverpod_test_module_server/migrations/20241219152628926/definition_project.json, tests/serverpod_test_module/serverpod_test_module_server/migrations/20241219152628926/migration.json, tests/serverpod_test_module/serverpod_test_module_server/migrations/20241219152628926/migration.sql, tests/serverpod_test_module/serverpod_test_module_server/migrations/migration_registry.txt
Some migrations had not been updated in the project after a column was changed to be nullable in the authentication module.
This creates a non-destructive migration for all concerned projects.
Given this change the chat example can now be started. This should resolve the linked issue bellow.
Closes: https://github.com/serverpod/serverpod/issues/1690
None - this should not result in a new migration for users of any of the modules.
=> chore: Update project migrations.

.github/workflows/dart-tests.yaml, .gitignore, melos.yaml, pubspec.yaml, tests/bootstrap_project/test/module_test.dart, tests/bootstrap_project/test/project_mini_test.dart, tests/bootstrap_project/test/project_test.dart, tests/serverpod_cli_e2e_test/test/generate_watch_test.dart
- Adds melos to the root of the project
- With lint command with the 3 options, normal, strict and loose, normal allows info but not warning, loose allows warnings, strict fails on all.
- With downgrade command to install the oldest dependencies.
- Add lint job with melos across all projects
- Add CI job to run the new melos command on linux and windows machines
Melos also comes with the benefit of the `bootstrap` command e.g. installing dependencies. I think it is a good idea to transition all our commands to melos instead of bash scripts. Much easier to understand and work with and we can make them platform-agnostic which is a huge plus.
But I think we can convert one script at a time rather than bundle them in a big PR.
Related issue: #2990 
If you need help, consider asking for advice …
=> ci: Add melos and melos lint job for project

packages/serverpod/lib/src/database/adapters/postgres/postgres_exceptions.dart, packages/serverpod/lib/src/database/concepts/exceptions.dart
Closes: #3075 
Typed database exceptions were recently introduced, but they did not correctly inherit the `toString` method defined in the base class.
This PR fixes that by using `base` class and extending the class rather than implementing it.
None - the class should not be implemented by users outside of the library.
=> fix: Fix print message for database exceptions.

packages/serverpod_client/lib/src/serverpod_client_shared.dart
- Removes debug prints for failed client calls, as it doesn't make any sense.
- Closes https://github.com/serverpod/serverpod/issues/1557.
=> fix: remove debug print messages for failed client calls

tools/serverpod_cli/lib/src/analyzer/models/entity_dependency_resolver.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/model_name_conflict_test.dart
This PR reviews all the places where class resolution is used. Added `moduleAlias` checks where needed to ensure correct behavior and left unchanged the places where the existing logic was already sufficient. Below is a breakdown of what was updated and what was not.
- **Unchanged**  
The existing code already works correctly by checking only the `className`. Since we dont allow inheritance across modules, no changes were needed.
https://github.com/serverpod/serverpod/blob/0009d80b52417669e80dd0a728fc00dae409bcea/tools/serverpod_cli/lib/src/analyzer/models/entity_dependency_resolver.dart#L47
- **Modified**  
We added `moduleAlias` checks because enums can have the same `className` in different modules. Both `className` and `moduleAlias` are now used to uniquely identify enums. …
=> fix: Add `moduleAlias` checks for accurate class resolution

tests/serverpod_test_client/lib/src/protocol/inheritance/child_with_default.dart, tests/serverpod_test_client/lib/src/protocol/inheritance/parent_with_default.dart, tests/serverpod_test_client/lib/src/protocol/protocol.dart, tests/serverpod_test_server/lib/src/generated/inheritance/child_with_default.dart, tests/serverpod_test_server/lib/src/generated/inheritance/parent_with_default.dart, tests/serverpod_test_server/lib/src/generated/protocol.dart, tests/serverpod_test_server/lib/src/models/inheritance/child_with_default.spy.yaml, tests/serverpod_test_server/lib/src/models/inheritance/parent_with_default.spy.yaml, tools/serverpod_cli/lib/src/generator/dart/library_generators/model_library_generator.dart, tools/serverpod_cli/lib/src/test_util/builders/class_definition_builder.dart, tools/serverpod_cli/test/generator/dart/client_code_generator/inheritance_class_test.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/inheritance_class_test.dart
This PR closes the issue #3082, where the problem is described in detail. As a brief summary, when using the model inheritance experimental feature, there is a bug if any of the base class fields have default values. The generated constructor tries to initialize the default fields as if they belong to the class itself instead of delegating to super.
No breaking changes, only the fix for a case not covered on the tests.
=> fix: [Inheritance] Invalid code generation when base class have parameters with default values

templates/serverpod_templates/projectname_server/Dockerfile
- Adds a missing step to copy `protocol.yaml` from the build stage to the final stage in the Dockerfile, essential for enabling log filtering in the Insights server.  
- Groups related commands in the Dockerfile for better readability and organization.
Closes: #3031
=> fix(dockerfile): Add missing copy step for protocol.yaml

tools/serverpod_cli/test/generator/dart/server_code_generator/sealed_class_test.dart
This PR removes the test I used to reproduce the [separator sdk bug](https://github.com/dart-lang/sdk/issues/59629) we discovered. As it is no longer needed it can be removed
no related issues
No breaking changes as just a test and an unused import are removed
=> Remove obsolete test 

tools/serverpod_vscode_extension/.vscode/launch.json
VSCode no longer seems to inherit the environment that a launch configuration is run from, resulting in the `PATH` and `ENV` being empty.
This PR adds a copy of the `PATH` and the required `SERVERPOD_HOME` env variable to ensure the extension can be debugged.
None.
=> chore: Add PATH and SERVERPOD_HOME to extension debug config.

.github/ISSUE_TEMPLATE/documentation.yml
Adds a template for filing documentation issues.
The new template appears in the list like so:
And looks like this once opened:
None.
=> chore: Add template for documentation issues.

tools/serverpod_cli/lib/src/analyzer/models/checker/analyze_checker.dart, tools/serverpod_cli/lib/src/analyzer/models/validation/restrictions.dart, tools/serverpod_cli/lib/src/analyzer/models/yaml_definitions/class_yaml_definition.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/field/field_relation_scope_test.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/relation/relation_manual_field_test.dart
This PR introduces validation to ensure that relations with the `serverOnly` scope are explicitly marked as optional. Without this validation, the analyzer fails to detect invalid model definitions, leading to runtime exceptions during deserialization.
Previously, if a relation with the `serverOnly` scope was not marked as optional, the generated `fromJson` method would expect the foreign key column to be present, even though it is absent in the client model. This mismatch caused runtime errors when the class was passed as a parameter to an endpoint.
**Invalid Definition:**
```yaml
class: Example
table: example
fields:
name: String
user: User?, relation, scope=serverOnly
```
**Valid Definition:**
```yaml
class: Example
table: example
fields:
name: String
user: User?, relation(optional), …
```
=> feat: Add validation for relations with serverOnly scope to ensure they are optional

tools/serverpod_cli/lib/src/analyzer/models/entity_dependency_resolver.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/relation/relation_keyword_test.dart
Closes #2972
At first I thought to implement it on a lower level, e.g. not even allowing to generate an invalid `TypeDefinition` (e.g. when it's a `List` but does not have any (1!) generics specified). But that just leads to a low-level crash like the one in the linked issue.
So instead we have to stop the processing early in the error case, and then rely on the analyzer to spot that condition (as well) and prevent the code generation.
=> fix: Generator crashes when encountering field with `List, relation` missing the generic type argument

tools/serverpod_cli/lib/src/analyzer/models/definitions.dart, tools/serverpod_cli/lib/src/analyzer/models/entity_dependency_resolver.dart, tools/serverpod_cli/lib/src/analyzer/models/model_parser/model_parser.dart, tools/serverpod_cli/lib/src/analyzer/models/validation/model_relations.dart, tools/serverpod_cli/lib/src/analyzer/models/validation/restrictions.dart, tools/serverpod_cli/lib/src/generator/types.dart, tools/serverpod_cli/lib/src/test_util/builders/class_definition_builder.dart, tools/serverpod_cli/lib/src/test_util/builders/enum_definition_builder.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/field/field_datatype_test.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/model_name_conflict_test.dart
**Description:**  
This refactor standardizes the use of the `moduleAlias` field by consolidating it within the `TypeDefinition` structure. The `moduleAlias` field, which was already present, has been updated with additional checks and logic to improve its functionality across the codebase. The field has been removed from all other definitions to simplify and centralize its usage.  
**Changes include:**  
- Consolidated the `moduleAlias` field into `TypeDefinition`.  
- Updated the `moduleAlias` getter to include new checks:
- Added conditions to handle `_projectRef` and `_packageRef` prefixes.  
- Removed `moduleAlias` from all other related definitions.  
- Updated relevant references and usages to align with the new structure.  
**Why this change?**  
- Ensures a single source of truth …
=> refactor: Use `TypeDefinition.moduleAlias` and remove `moduleAlias` from other definitions

packages/serverpod/lib/src/cache/local_cache.dart, tests/serverpod_test_server/test/local_cache_test.dart
Closes #2953
Additionally ensures only one `cacheMissHandler` for a given key is invoked, and that they won't be called in parallel for a given key. All `get`s will then resolve to the same value (or error).
=> fix: `LocalCache` returning `null` for expired keys instead of invoking `cacheMissHandler`

tools/serverpod_cli/lib/src/generator/dart/library_generators/util/custom_allocators.dart, tools/serverpod_cli/test/generator/dart/client_code_generator/imports_test.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/imports_test.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/sealed_class_test.dart
=> fix: Relative imports sometimes generated with backward slashes on Windows

packages/serverpod/lib/src/relic/routes/static_directory.dart, tests/serverpod_test_server/test_integration/static_files_test.dart
Original PR https://github.com/serverpod/serverpod/pull/2539 by @lukehutch 
> Allow static paths to be excluded from CDN caching, by regexp match.
> 
> Partially addresses #2534, although for that to be fixed, dynamic responses should also include these same cache denial headers. (I didn't make that change in this PR, but it needs to be done...)
> 
> ## Pre-launch Checklist
> * [x]  I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
> * [x]  This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
> * [x]  I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with …
=> feat: Allow static content to not be cached, by path regexp

tests/docker/tests_e2e/Dockerfile-tests
by only copying the local files after the container is set up (apt-get being done)
That way Docker can use a cache for the previous build steps, and just needs to re-run `pub get` on each run as the files might influence that.
=> Speed up local E2E tests in Docker container

templates/serverpod_templates/projectname_server_upgrade/docker-compose.yaml
Using empty strings as defaults for docker profiles is undocumented behaviour and may or may not work on a developers device, as discussed in https://github.com/serverpod/serverpod/issues/3143 and the decision was made to run both testing and development services at the same time to reduce friction and because testing should be an integral part of development.
This closes #3143
=> chore: remove docker-compose profiles and make strings consistent

.github/workflows/dart-tests.yaml
New version of [Flutter](https://medium.com/flutter/f90c380c2317) and [Dart](https://medium.com/dartlang/announcing-dart-3-7-bf864a1b195c) are out.
This PR bumps the latest version of Dart and Flutter used in the CI tests.
None, simple CI change.
=> ci: Bump to latest version of Flutter and Dart

modules/serverpod_auth/serverpod_auth_shared_flutter/pubspec.yaml, modules/serverpod_chat/serverpod_chat_flutter/pubspec.yaml, templates/pubspecs/modules/serverpod_auth/serverpod_auth_shared_flutter/pubspec.yaml, templates/pubspecs/modules/serverpod_chat/serverpod_chat_flutter/pubspec.yaml
Widens the dependency range for `file_picker` to allow the newest release.
This should be fine for us since the breaking change does not directly impact the way we are using the interface.
https://pub.dev/packages/file_picker/changelog
None - Simple version widening.
=> chore: Bump file_picker dependency.

tests/serverpod_test_server/test_integration/test_tools/start_timeout_test/start_timeout_test.dart
If timeout exceeded, process should exit 1, and stdout indicate the reason, but don't mandate how long it took.
Mandating how long it took is flaky, and can cause false positives.
fix: #3258 
None
=> fix: Validate timeout, but don't bound how long.

modules/serverpod_auth/serverpod_auth_shared_flutter/pubspec.yaml, templates/pubspecs/modules/serverpod_auth/serverpod_auth_shared_flutter/pubspec.yaml
Bumps the image cropper dependency.
Changelog here: https://pub.dev/packages/image_cropper/changelog
Breaking changes are contained in the android configuration so should not influence our use of the package.
Closes: https://github.com/serverpod/serverpod/pull/3250
None.
=> chore: Bump image_cropper

packages/serverpod/lib/src/server/health_check_manager.dart, packages/serverpod/lib/src/server/serverpod.dart, tests/serverpod_test_server/test_integration/shutdown_test.dart
Orderly shutdown of Serverpod when SIGTERM or SIGINT (ctrl-c in the terminal) are received.
If ctrl-c is pressed a second time before shutdown is complete then the process exits immediately.
(On Windows SIGTERM is not supported.)
Closes #2147 
n/a
=> feat: Handle SIGTERM and shutdown gracefully

.github/workflows/title-validation.yaml
Adds a PR title validator inspired by the configuration for the flame open source repository: https://github.com/flame-engine/flame/blob/main/.github/ISSUE_TEMPLATE/feature_request.yml?plain=1
Since PR titles are by default used as the commit message to `main`, this linter will help us ensure we follow conventional commits for the squashes in main.
None - Simple ci fix.
=> ci: Add PR title validator

packages/serverpod/lib/src/server/server.dart, tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_server/lib/src/endpoints/upload_too_large.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/test_e2e/upload_too_large_test.dart, tests/serverpod_test_server/test_integration/test_tools/serverpod_test_tools.dart
This is a workaround to https://github.com/dart-lang/sdk/issues/60271
fix: #3213
=> fix: Ensure we drain the request data stream completely, even if we realize it is too large

modules/serverpod_auth/serverpod_auth_email_flutter/lib/serverpod_auth_email_flutter.dart, modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/signin_button.dart, modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/signin_dialog.dart, modules/serverpod_auth/serverpod_auth_email_flutter/lib/src/signin_labels.dart
This PR adds the functionality to localize/internationalize the labels in the `SignInWithEmailDialog`.
The `SignInWithEmailButton` now accepts a (nullable) parameter `localization` of type `SignInWithEmailLabels` consisting of nullable `Strings` or `String Function(int length)?`.
When passed with valid strings this shows in the UI: 
If a individual String is `null`, the english fallback is used.
closes #2291 
no breaking changes
=> feat: SignInWithEmailDialog allow label localization/customization

tools/serverpod_cli/lib/src/analyzer/code_analysis_collector.dart, tools/serverpod_cli/lib/src/analyzer/models/stateful_analyzer.dart, tools/serverpod_cli/lib/src/analyzer/models/validation/model_validator.dart, tools/serverpod_cli/lib/src/analyzer/models/validation/restrictions.dart, tools/serverpod_cli/lib/src/generator/generator.dart, tools/serverpod_cli/lib/src/migrations/generator.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/class_conflicts_test.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/file_name_conflicts_test.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/model_types_test.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/stateful_analyzer_test.dart, tools/serverpod_cli/test/util/string_manipulation_test.dart
Some file and class names are not useful when defining models as they will conflict with other files and classes we generate.
In particular the file names:
- _client.dart_
- _endpoints.dart_
- _protocol.dart_
and the matching class names:
- **Client**
- **Endpoints**
- **Protocol**
We need to check for both as there are no guarantees that class and file names are aligned for models.
This PR adds extra validation so that `serverpod generate` will catch this, instead of generating invalid code.
We can get rid of these restrictions, but it will be a breaking change as it will impact the import paths used in client code.
fix: #3149
None. Trying to use these names would already leave your project in a broken state. This fix merely adds validation.
=> fix: Fail early on invalid class and file names

packages/serverpod/lib/src/database/adapters/postgres/database_connection.dart, packages/serverpod/lib/src/server/log_manager/log_manager.dart
Preserves the stack trace from our database library.
Will be used to provide further debug information to: https://github.com/serverpod/serverpod/issues/3307
- Cleaned up the logging for when logging to the database fails.
None - Should be fine to modify log message output.
=> fix: Preserve trace for database query exceptions.

modules/serverpod_auth/serverpod_auth_server/pubspec.yaml, templates/pubspecs/modules/serverpod_auth/serverpod_auth_server/pubspec.yaml
Widens the `googleapis` dependency from `'>=11.0.0 <14.0.0'` to `'>=11.0.0 <15.0.0'` to allow the latest released version.
None of the deprecated apis are used by Serverpod.
None - Widening is allowed since we don't use any of the deprecated apis.
=> chore: Bump googleapis.

packages/serverpod_client/lib/src/serverpod_client_shared.dart
Wasm build is broken because serverpod client assumes `dart.library.js` is available in wasm builds but it's not. We should use `dart.library.js_interop` instead which doesn't break the old web users but is now also passing for wasm.
This PR fixes the issue #3333
=> fix: Wasm support in serverpod client

packages/serverpod/lib/src/server/diagnostic_events/operation_context_helpers.dart
This fixes the bug when the web server was submitting exception events, the URI path was not included.
n/a
=> fix: Include URI path in web server diagnostic events

tests/serverpod_test_client/lib/src/protocol/defaults/enum/enums/default_value_enum.dart, tests/serverpod_test_client/lib/src/protocol/protocol.dart, tests/serverpod_test_server/lib/src/generated/defaults/enum/enums/default_value_enum.dart, tests/serverpod_test_server/lib/src/generated/protocol.dart, tests/serverpod_test_server/lib/src/models/defaults/enum/enums/default_value_enum.spy.yaml, tests/serverpod_test_server/test_integration/database_operations/default/enum/enum_default_test.dart, tools/serverpod_cli/lib/src/analyzer/models/definitions.dart, tools/serverpod_cli/lib/src/analyzer/models/model_parser/model_parser.dart, tools/serverpod_cli/lib/src/analyzer/models/validation/restrictions.dart, tools/serverpod_cli/lib/src/analyzer/models/yaml_definitions/enum_yaml_definition.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/model_library_generator.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/class_type_test.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/enum_default_value_test.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/extra_properties_test.dart, tools/serverpod_cli/test/analyzer/models/stateful_analyzer/model_validation/field/field_validation_test.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/enum_field_test.dart, tools/serverpod_cli/test/test_util/builders/enum_definition_builder.dart
Implements https://github.com/serverpod/serverpod/issues/3338 
By adding a new property in the enum fields
Just use the value name
```
enum: Example
serialized: byName
default: unknown
values:
- unknown
- customValue1
- customValue2
```
With byIndex you still use the value name
```
enum: Example
serialized: byIndex
default: unknown
values:
- unknown
- customValue1
- customValue2
```
Everything is backwards compatible
=> feat: Global default enum value to prevent breaking the client

packages/serverpod/lib/src/server/diagnostic_events/event_handler.dart, tests/serverpod_test_server/lib/src/endpoints/diagnostic_event_test_endpoint.dart, tests/serverpod_test_server/test_integration/diagnostics/diagnostic_events_api_test.dart
This adds the ability to include custom data when submitting diagnostic events.
It is intended to be used by application (user) code, not framework code. The content to include and how to handle it in the event handlers is up to the user.
Closes #3332 
The solution differs slightly from the suggestion in the issue: Rather than extending the context, this is included as a key/value map in the event itself. This makes sense since the context types are framework-managed and this is an entirely user-owned data payload for individual events.
No, does not change any existing API. Adds an optional initialization field to the diagnostic event constructor.
=> feat: Enable adding custom data to diagnostic events

modules/serverpod_auth/serverpod_auth_server/pubspec.yaml, templates/pubspecs/modules/serverpod_auth/serverpod_auth_server/pubspec.yaml
Adds a span for `googleapis_auth` to allow then new `2.0.0` release.
The deprecated `auth.dart` and `RefreshFailedException` are not used by Serverpod internally so the version range should be OK.
None - simple dependency widening.
=> chore: Bump googleapis_auth to allow 2.0.0 release.

packages/serverpod/lib/src/server/health_check_manager.dart, packages/serverpod/lib/src/server/serverpod.dart, tests/serverpod_test_server/test_integration/diagnostics/diagnostic_events_test.dart
Report exception events during database startup and health-check operations via the diagnostics handler. These areas were not covered before as reported in issue #3294.
Closes #3294 
n/a
=> fix: Report exceptions during database start and healthcheck operations

tests/serverpod_test_client/lib/src/protocol/protocol.dart, tests/serverpod_test_client/lib/src/protocol/types_set_required.dart, tests/serverpod_test_server/lib/src/generated/protocol.dart, tests/serverpod_test_server/lib/src/generated/types_set_required.dart, tests/serverpod_test_server/lib/src/models/types_set_required.spy.yaml, tests/serverpod_test_server/test/generated_methods/from_json_test.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/util/class_generators_util.dart
Before the de-serialization code for a `Set<T>` was not generated correctly, because the helper was typed to return `Set<T>?` even though it would always return a value for non-`null` inputs.
We missed this until now because for the new types we did not add the cases to the legacy types test based on `tests/serverpod_test_server/lib/src/models/nullability.spy.yaml` and in all other cases the fields were always nullable. 
Presumably that test was phased out because it's painfully noisy to add all those required cases when you don't want to look at them in any individual test.
To test the current issue I thus opted to create a new focused model that only has one required / non-nullable field to test in isolation.
Follow up fix for #3211
Relates to …
=> fix: Support non-nullable `Set` in models

modules/serverpod_auth/serverpod_auth_apple_flutter/pubspec.yaml, templates/pubspecs/modules/serverpod_auth/serverpod_auth_apple_flutter/pubspec.yaml
Bumps the minimum version to `6.0.0` since that is the first version that is supported by Dart `3.3` which is Serverpods minimum required version.
Bumps that max version to `<8.0.0` to allow the new `7.x.x` major version.
None of the features mentioned in the changelog are used by the authentication method.
Changelog: https://pub.dev/packages/sign_in_with_apple/changelog
Version and SDK: https://pub.dev/packages/sign_in_with_apple/versions
=> chore: Bump sign_in_with_apple dependency.

tools/serverpod_cli/lib/src/serverpod_packages_version_check/serverpod_packages_version_check.dart, tools/serverpod_cli/test/integration/serverpod_packages_version_check/serverpod_packages_version_check_test.dart
Restrict the packages that must match the version of `serverpod_cli`, when running the generate command.
Now we only check `serverpod_client` and `serverpod` which matches the imports used in the generated code.
Fixes: #3397
None.
=> fix: Restrict version check to serverpod, and serverpod_client packages

packages/serverpod/lib/src/database/database_pool_manager.dart, packages/serverpod/lib/src/database/extensions.dart, packages/serverpod/lib/src/server/command_line_args.dart, packages/serverpod/pubspec.yaml, packages/serverpod/test/database/extensions/table_comparison_test.dart, packages/serverpod_shared/lib/src/config.dart, packages/serverpod_shared/lib/src/environment_variables.dart, packages/serverpod_shared/test/config_test.dart, packages/serverpod_shared/test/database_config_test.dart, templates/pubspecs/packages/serverpod/pubspec.yaml, tools/serverpod_cli/lib/src/database/extensions.dart
This PR introduces the possibility of configuring the database search path as a configurable parameter for all database pool connections.
This enables the possibility to define a different schema to use when applying migrations and running queries towards the database.
In order to support this feature, validation on the schema name has been removed. Since we don't provide any migration step it doesn't really make sense to validate the schema anyway.
Implementing support for full schema configuration will be part of this issue: https://github.com/serverpod/serverpod/issues/3385
This can be configured either through the config file like so:
```yaml
database:
host: localhost
port: 5432
name: testDb
user: test
searchPaths: config_file_path
```
OR through the environment variable: …
=> feat: Support configuring database search path.

packages/serverpod/lib/src/server/health_check_manager.dart
Fixes https://github.com/serverpod/serverpod/issues/3394
Avoid debug console pollution with unnecessary stackstrace because the used package does not support windows. (https://github.com/jonasroussel/system_resources/issues/3).
Fixes https://github.com/serverpod/serverpod/issues/3394
- [x ] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [ x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x ] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x ] I listed at least one issue that this PR …
=> fix: Avoid unnecessary stacktrace in windows when performing health checks

tests/serverpod_test_client/lib/src/protocol/client.dart, tests/serverpod_test_server/lib/src/endpoints/record_parameters.dart, tests/serverpod_test_server/lib/src/generated/endpoints.dart, tests/serverpod_test_server/lib/src/generated/protocol.yaml, tests/serverpod_test_server/test_e2e/record_types_test.dart, tests/serverpod_test_server/test_integration/test_tools/serverpod_test_tools.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart
So we support all names and not just literally "record".
=> fix: Support record parameters named something other than "record"

templates/pubspecs/tools/serverpod_cli/pubspec.yaml, tools/serverpod_cli/lib/src/config/config.dart, tools/serverpod_cli/lib/src/util/locate_modules.dart, tools/serverpod_cli/pubspec.yaml, tools/serverpod_cli/test/integration/util/locate_modules_test.dart, tools/serverpod_cli/test/test_util/builders/generator_config_file_builder.dart, tools/serverpod_cli/test/test_util/builders/package_config_builder.dart, tools/serverpod_cli/test/test_util/builders/project_dependency_factory.dart, tools/serverpod_cli/test/test_util/builders/pubspec_builder.dart
Closes: #3377 
The `package_config.json` is created when a developer runs `dart pub get` and contains paths to the cached dart packages.
This file was previously inspected to find all Serverpod modules that the project depended on in order to analyze their migrations, models and endpoints.
With the introduction of workspaces in Dart, the `package_config.json` is now shared between all workspace projects. This invalidates this file as a source of truth for what is strictly a dependency on the Serverpod project.
This PR fixes this issue by adding a pre-step to loading the configs where only module configs that are strict or direct transitive dependencies of the Serverpod project are collected for investigation.
This PR also reintroduces the `ServerpodModulesNotFoundException` throw if a …
=> fix: Make serverpod generate compatible with workspaces.

packages/serverpod/lib/src/server/websocket_request_handlers/endpoint_websocket_request_handler.dart
When implementing Exception events hooks in this [PR](https://github.com/serverpod/serverpod/pull/3187), we accidentally started reporting authorization rejections as server exceptions for streaming endpoints.
This PR reverts that change.
Closes #3414 
None - simply silences invalid exception reporting.
=> fix: Prevent reporting auth rejections as an exception for streaming endpoints.

.github/workflows/dart-tests.yaml, packages/serverpod_flutter/lib/serverpod_flutter.dart, packages/serverpod_flutter/lib/src/localhost.dart, packages/serverpod_flutter/lib/src/localhost_io.dart, packages/serverpod_flutter/lib/src/localhost_web.dart, packages/serverpod_flutter/test/localhost_test.dart
_Avoid using conditional import in the `serverpod_flutter` package and adding simple unit tests to cover `localhost` getter_
- *Fix #3438*
=> refactor(serverpod_flutter): Avoid using conditional import for localhost

tools/serverpod_cli/lib/src/database/extensions.dart, tools/serverpod_cli/test/database/migration/default_value_test.dart
After #3437 merge, one question remained to be solved: what happens when changing the type of an id in a migration? The answer is that the migration was allowing to only drop/create the column instead of the whole table. This PR fixes it by forcing to drop/create the table instead.
N/A.
=> fix: Fix changing the id type of a table only dropping/creating the column

pubspec.yaml
`pub.dev` reported these issues with the root `pubspec.yaml` file:
```
0/10 points: Provide a valid pubspec.yaml
Failed to verify repository URL.
Please provide a valid [repository](https://dart.dev/tools/pub/pubspec#repository) URL in pubspec.yaml, such that:
- repository can be cloned,
- a clone of the repository contains a pubspec.yaml, which:,
- contains name: serverpod,
- contains a version property, and,
- does not contain a publish_to property.
Repository has multiple matching pubspec.yaml with name: serverpod.
```
This PR attempts to fix these by renaming the package name in the root pubspec to `serverpod_workspace`. (Although this repo is not technically a Dart workspace at this time, it might be made into one later on.)
If you need help, consider asking for advice on the …
=> chore: Pubspec in repo root adhering to best practices

.github/workflows/dart-tests.yaml, tests/docker/tests_integration/run_tests.sh, tests/serverpod_test_module/serverpod_test_module_server/config/passwords.yaml, tests/serverpod_test_module/serverpod_test_module_server/config/test.yaml, tests/serverpod_test_module/serverpod_test_module_server/docker-compose.yaml
To run each module's `withServerpod` integration tests.
Adds the (now default) `docker-compose.yaml` file to `serverpod_test_module_server` to showcase the new behavior.
=> feat: Add module integration test step to CI pipeline

tests/serverpod_test_server/test_e2e_migrations/migrations_roundtrip_test.dart, tools/serverpod_cli/lib/src/database/extensions.dart, tools/serverpod_cli/test/database/extentions/migration_pgsql_code_generation_test.dart, tools/serverpod_cli/test/database/extentions/migration_with_many_to_many_relation_pgsql_code_generation_test.dart, tools/serverpod_cli/test/test_util/database_definition_helpers.dart
Fixes: #3503 
When foreign keys where created as part of altering migrations in the migration system these where placed together with the other alterations to the table and not last in the file.
This caused an issue when a new table was referenced from an old table, but the creation of the new table was placed after the alterations to the old table in the migration file.
More concrete examples of the issue are included in the tests.
**Additional question**
The helper introduced in `migration_pgsql_code_generation_test.dart` could be extracted and used in `migration_with_many_to_many_relation_pgsql_code_generation_test.dart`. This would significantly reduce the footprint of that file while abstracting away non-essential boilerplate.
Should I migrate the old file?
If you need help, consider …
=> fix: Ensure foreign key relations are always defined after table creation.

.github/workflows/dart-tests.yaml
Because the DB setup/migrations across `withServerpod` calls in multiple test files are not synchronized, so they can create conflicts when using 2 or more such calls.
As these are modules, there is no `--apply-migrations` to be done outside the tests (as far as I can see).
Further this removes the test volumes from Docker after a test completed. (This was not an issue in practice, but seems cleaner.)
This change fixes the previously broken module test in https://github.com/serverpod/serverpod/actions/runs/14883049192?pr=3441, which was using 2 `withServerpod` calls.
=> feat: Set module integration test concurrency to 1

.github/workflows/dart-tests.yaml, packages/serverpod/lib/src/database/migrations/migration_manager.dart, packages/serverpod/lib/src/database/migrations/migrations.dart, packages/serverpod/lib/src/endpoints/insights.dart, packages/serverpod/lib/src/server/serverpod.dart, templates/pubspecs/tests/serverpod_test_server/pubspec.yaml, tests/serverpod_test_server/pubspec.yaml, tests/serverpod_test_server/test_integration/migration_manager/concurrent_migration_test.dart, tests/serverpod_test_server/test_integration/migration_manager/concurrent_repair_migration_test.dart
Closes: #3504 
This PR introduces an advisory lock that is used whenever migrations towards the database are applied.
This ensures that even in an environment where mutliple servers have the `--apply-migration` flag turned on, only one of them will make modifications to the database at the same time.
This makes the full migration script atomic.
This issue was encountered when running integration tests using the test framework since that would spawn multiple isolates that each would start a Serverpod server, resulting in a race condition when applying the migrations.
- Makes the MigrationManager private on Serverpod. This is technically a breaking change, but it should never be used by external users.
- Removes updating the state of the MigrationManager when fetching the live database …
=> fix: Prevent possibility of multiple migrations being applied at the same time.

packages/serverpod/lib/src/server/log_manager/log_writers.dart, tests/serverpod_test_server/test_integration/logging/endpoint_method_call_logging_test.dart
Closes: #3535 
Fixes an issue where we would not print the duration of request when doing console logging.
This was found when prepping the "pretty print" logging that is part of #3510.
None, simple additional log entry.
=> fix: Always print when closing the log.

tools/serverpod_cli/lib/src/database/extensions.dart, tools/serverpod_cli/test/database/extentions/migration_pgsql_code_generation_test.dart
On #3473, the declaration of the UUIDv7 generation function on the `definitions.sql` happens only when any table uses it, but the `migration.sql` was having it included always. This PR fixes it, making the declaration on the `migration.sql` to also be conditional to the function usage as default on any table.
=> fix: Avoid generating random UUIDv7 function when not used in migrations

packages/serverpod/lib/src/server/server.dart
Previously, the health check responded with status code 200 even when the services was unhealthy. This will be interpreted as healthy by other systems such as when a loadbalancer checks if the server is available. 
To make sure traffic is not routed to unhealthy instances we now give back 503 instead.
None
=> fix: Respons with 503 when server is unhealthy

modules/new_serverpod_auth/serverpod_auth_user/serverpod_auth_user_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_user/serverpod_auth_user_server/pubspec.yaml
Noticed a missed dependency override when creating the 2.7.0 release.
None - simple dev override addition.
=> chore: Add missing dependency override in serverpod_auth_user_server.

.github/workflows/dart-tests.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_session/serverpod_auth_session_server/pubspec.yaml, util/ensure_no_changes, util/generate_all, util/recreate_all_migrations, util/run_tests_serverpod_generate, util/run_tests_unit, util/run_tests_update_pubspecs, util/run_tests_version_change, util/update_pubspecs
Closes: #2871
Adds a CI test for validating that Serverpod version upgrades are ok.
This will help us catch missed dependency overrides in the project.
Commit number 4 introduces an error that was catched here: https://github.com/serverpod/serverpod/actions/runs/15021982175/job/42213207934
Removed in commit number 5.
None - Simple CI test.
=> test: Add ci test for upgrading Serverpod version.

templates/pubspecs/tools/serverpod_cli/pubspec.yaml, tools/serverpod_cli/pubspec.yaml
Uses a minimum version for `cli_tools` instead of a fixed version.
No changes.
=> chore: Don't use fixed version for cli_tools

modules/new_serverpod_auth/serverpod_auth_user/serverpod_auth_user_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_user/serverpod_auth_user_server/pubspec.yaml, tools/serverpod_cli/test/util/pubspec_plus_test.dart, util/pub_get_all
An accidentally invalid merge to main broke the CI suite in main. This PR fixes this by ensuring that all lint packages have the same version.
** Additional fix **
Adds a newly introduced test package to the `pub_get_all` script.
=> chore: Bumps the version to match the rest.

.github/workflows/dart-tests.yaml, modules/serverpod_auth/serverpod_auth_server/config/passwords.yaml, modules/serverpod_auth/serverpod_auth_server/config/test.yaml, modules/serverpod_auth/serverpod_auth_server/docker-compose.yaml, modules/serverpod_auth/serverpod_auth_server/lib/src/business/users.dart, modules/serverpod_auth/serverpod_auth_server/test/blocked_user_test.dart, modules/serverpod_auth/serverpod_auth_server/test/signout_legacy_option_test.dart, modules/serverpod_auth/serverpod_auth_server/test_integration/blocked_user_test.dart
This PR adds `invalidateCacheForUser` to `unblockUser` so a user can be blocked again.
The user can not be blocked after unblocking because `blockUser` gets the cached value and throws an exception that the user is already blocked.
None
=> fix: Add cache invalidation for User in unblockUser

packages/serverpod/lib/src/server/log_manager/log_writers.dart
Small improvement to the text logging output that I wanted to add.
- add a helper to format durations for the TextStdOutLogWriter
- rename the `time` field in text logs to `duration`
- show durations using a readable unit (µs, ms, s)
- fix `_printDuration` to interpret millisecond input
=> fix: Improve duration print for human readable logs.

modules/new_serverpod_auth/serverpod_auth_jwt/serverpod_auth_jwt_server/config/test.yaml, modules/new_serverpod_auth/serverpod_auth_jwt/serverpod_auth_jwt_server/docker-compose.yaml, modules/new_serverpod_auth/serverpod_auth_profile/serverpod_auth_profile_server/config/test.yaml, modules/new_serverpod_auth/serverpod_auth_profile/serverpod_auth_profile_server/docker-compose.yaml, modules/new_serverpod_auth/serverpod_auth_session/serverpod_auth_session_server/config/test.yaml, modules/new_serverpod_auth/serverpod_auth_session/serverpod_auth_session_server/docker-compose.yaml, modules/new_serverpod_auth/serverpod_auth_user/serverpod_auth_user_server/config/test.yaml, modules/new_serverpod_auth/serverpod_auth_user/serverpod_auth_user_server/docker-compose.yaml, modules/serverpod_auth/serverpod_auth_server/config/test.yaml, modules/serverpod_auth/serverpod_auth_server/docker-compose.yaml, templates/serverpod_templates/modulename_server/config/test.yaml, templates/serverpod_templates/modulename_server/docker-compose.yaml, tests/bootstrap_project/test/module_test.dart, tests/serverpod_test_module/serverpod_test_module_server/config/test.yaml, tests/serverpod_test_module/serverpod_test_module_server/docker-compose.yaml
Closes: #3611 
The config templates for modules incorrectly used `projectname_test` instead of `modulename_test` which is what our search and replace algorithm looks for when copying over the template files.
This made the database and data volume of all modules to resolve to the same name.
I also patched this in all existing modules in the project.
- [x ] Any breaking changes are documented below.
None - This will only influence new modules created.
=> fix: Fix project name replacement when creating modules.

tests/serverpod_test_server/test_integration/shutdown_test.dart
Previous attempt in PR #3652 didn't work. In this PR we are reclassifying this test to run non-concurrently, hopefully that fixes the flakyness.
Closes #3431 
n/a
=> fix: Attempting to fix flaky shutdown test

packages/serverpod/lib/src/generated/protocol.dart, packages/serverpod_service_client/lib/src/protocol/protocol.dart, tests/serverpod_test_client/lib/src/protocol/protocol.dart, tests/serverpod_test_server/lib/src/generated/protocol.dart, tests/serverpod_test_server/test/class_name_for_object_test.dart, tests/serverpod_test_server/test/serialization_test.dart, tools/serverpod_cli/lib/src/generator/dart/library_generators/library_generator.dart, tools/serverpod_cli/test/generator/dart/client_code_generator/protocol/inheritance_protocol_test.dart
Sorts classes in a hierarchy from child to parent, such that the `getClassNameForObject` gets the name of the most specific class, not a parent.
Closes #3730
=> fix(codegen): Fix `getClassNameForObject` for subclasses

.github/workflows/dart-tests.yaml, templates/serverpod_templates/github/workflows/deployment-gcp.yml
In our GitHub actions and the default GCP deployment template.
Closes #3733
=> feat: Upgrade to `actions/checkout` `v4`

modules/new_serverpod_auth/serverpod_auth_apple/serverpod_auth_apple_server/pubspec.yaml, modules/new_serverpod_auth/serverpod_auth_apple_account/serverpod_auth_apple_account_server/pubspec.yaml, modules/new_serverpod_auth/serverpod_auth_backwards_compatibility/serverpod_auth_backwards_compatibility_server/pubspec.yaml, modules/new_serverpod_auth/serverpod_auth_email/serverpod_auth_email_server/pubspec.yaml, modules/new_serverpod_auth/serverpod_auth_email_account/serverpod_auth_email_account_server/pubspec.yaml, modules/new_serverpod_auth/serverpod_auth_google_account/serverpod_auth_google_account_server/pubspec.yaml, modules/new_serverpod_auth/serverpod_auth_jwt/serverpod_auth_jwt_server/pubspec.yaml, modules/new_serverpod_auth/serverpod_auth_migration/serverpod_auth_migration_server/pubspec.yaml, modules/new_serverpod_auth/serverpod_auth_profile/serverpod_auth_profile_server/pubspec.yaml, modules/new_serverpod_auth/serverpod_auth_session/serverpod_auth_session_server/pubspec.yaml, modules/new_serverpod_auth/serverpod_auth_user/serverpod_auth_user_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_apple/serverpod_auth_apple_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_apple_account/serverpod_auth_apple_account_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_backwards_compatibility/serverpod_auth_backwards_compatibility_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_email/serverpod_auth_email_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_email_account/serverpod_auth_email_account_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_google_account/serverpod_auth_google_account_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_jwt/serverpod_auth_jwt_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_migration/serverpod_auth_migration_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_profile/serverpod_auth_profile_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_session/serverpod_auth_session_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_user/serverpod_auth_user_server/pubspec.yaml
As the server's analysis options rely on it. Before it was always implicitly included and the analysis working without error, but now it's properly mentioned.
=> feat(auth2): Add `serverpod_lints` under`dev_dependencies` in every new auth server package

tools/serverpod_cli/lib/src/commands/create.dart, tools/serverpod_cli/lib/src/runner/serverpod_command_runner.dart
Previously we downloaded all templates regardless of which command was run. This caused unecessary time to be wasted if all the user wanted to do is run `serverpod version` for example. This PR moves the template downloading logic to the `create` command specifically.
Fixes #3770
=> fix: Only download templates on `create` command

modules/new_serverpod_auth/serverpod_auth_email_account/serverpod_auth_email_account_server/lib/serverpod_auth_email_account_server.dart, modules/new_serverpod_auth/serverpod_auth_email_account/serverpod_auth_email_account_server/lib/src/business/email_accounts.dart, modules/new_serverpod_auth/serverpod_auth_email_account/serverpod_auth_email_account_server/lib/src/business/email_accounts_admin.dart
While keeping the constructor internal, so the package stays in control of when and how to create it.
=> feat(auth2): Update documentation for `EmailAccountsAdmin` and export its type

integrations/serverpod_cloud_storage_s3/lib/src/cloud_storage.dart/s3_cloud_storage.dart
What this PR does
This PR fixes an issue in the createDirectFileUploadDescription method where the public parameter was not passed to AwsS3Uploader.getDirectUploadDescription. This caused incorrect headers to be generated for private S3 buckets, resulting in failed uploads.
The public parameter is now correctly forwarded, ensuring proper upload behavior for both public and private buckets.
Issues fixed by this PR
Fixes [#2655](https://github.com/serverpod/serverpod/issues/2655)
=> fix: Add missing `public` parameter to file upload description

tools/serverpod_cli/lib/src/runner/serverpod_command_runner.dart
Since we merged in https://github.com/serverpod/serverpod/pull/3781, we don't need to log out that templates don't exist as this would be handled by the create command.
=> fix: Remove "cannot find templates" log on every command

modules/new_serverpod_auth/serverpod_auth_jwt/serverpod_auth_jwt_server/lib/src/business/jwt_util.dart
Ensuring that the string indeed represented a valid UUID
=> feat(auth2): Use `UuidValue.withValidation` instead of `fromString`

.github/workflows/dart-tests.yaml
I noticed that we had a bunch of cancelled runs on the main branch.
On main, it is valuable information to know whether a commit failed.
This PR attempts to disable cancel in progress for the main branch.
None - CI change
=> ci: Allow all commits to be built on main.

tests/serverpod_test_client/lib/src/protocol/object_with_nullable_custom_class.dart, tests/serverpod_test_client/lib/src/protocol/protocol.dart, tests/serverpod_test_server/lib/src/generated/object_with_nullable_custom_class.dart, tests/serverpod_test_server/lib/src/generated/protocol.dart, tests/serverpod_test_server/lib/src/models/object_with_nullable_custom_class.spy.yaml, tools/serverpod_cli/lib/src/generator/dart/library_generators/model_library_generator.dart, tools/serverpod_cli/test/generator/dart/server_code_generator/custom_class_nullable_test.dart
When using custom classes in protocols, an uncessary null-aware operator (`?.`) was added to the generated code in `toJsonForProtocol()`. This PR aims to fix that lint
Fixes https://github.com/serverpod/serverpod/issues/3217
=> fix: Unnessary optional null check on generated class with custom class

modules/new_serverpod_auth/serverpod_auth_bridge/serverpod_auth_bridge_server/lib/src/business/auth_backwards_compatibility.dart
When the bridge package was tested with no password pepper set, it failed on the next step. This revealed that clearing the legacy password was preserved even though the transaction failed.
This PR adds the missing transaction to the missing `clearLegacyPassword` step.
None, simple bugfix.
=> fix: Add missing transaction when importing legacy password in bridge package.

modules/new_serverpod_auth/serverpod_auth_bridge/serverpod_auth_bridge_server/pubspec.yaml, modules/new_serverpod_auth/serverpod_auth_core/serverpod_auth_core_server/pubspec.yaml, modules/new_serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/pubspec.yaml, modules/serverpod_auth/serverpod_auth_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_bridge/serverpod_auth_bridge_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_core/serverpod_auth_core_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server/pubspec.yaml, templates/pubspecs/modules/serverpod_auth/serverpod_auth_server/pubspec.yaml
Widens the version range of pointycastle to allow the 4.0.0 release.
None of the breaking changes touch the code we use.
Didn't go with a strict bump since the 4.0.0 release has failed CI runs in their repo.
Pub.dev: https://pub.dev/packages/pointycastle
Github: https://github.com/bcgit/pc-dart
None - Should provide the same functionality.
=> chore: Bump version range of pointycastle

modules/serverpod_auth/serverpod_auth_firebase_flutter/pubspec.yaml, templates/pubspecs/modules/serverpod_auth/serverpod_auth_firebase_flutter/pubspec.yaml
Bump the `firebase_ui_auth` dependency.
https://pub.dev/packages/firebase_ui_auth/changelog
None - the dependency has breaking changes but these are not reflected in any of the interfaces we use.
=> chore: Bump firebase ui dependency.

packages/serverpod/lib/src/database/concepts/expressions.dart, packages/serverpod/test/database/expressions/expression_test.dart
=> feat: Add a `~` operator on expressions to perform `NOT` expression

modules/new_serverpod_auth/serverpod_auth_bridge/serverpod_auth_bridge_client/lib/src/protocol/protocol.dart, modules/new_serverpod_auth/serverpod_auth_bridge/serverpod_auth_bridge_server/lib/src/generated/endpoints.dart, modules/new_serverpod_auth/serverpod_auth_bridge/serverpod_auth_bridge_server/lib/src/generated/protocol.dart, modules/new_serverpod_auth/serverpod_auth_bridge/serverpod_auth_bridge_server/pubspec.yaml, modules/new_serverpod_auth/serverpod_auth_migration/serverpod_auth_migration_client/lib/src/protocol/protocol.dart, modules/new_serverpod_auth/serverpod_auth_migration/serverpod_auth_migration_server/lib/src/generated/endpoints.dart, modules/new_serverpod_auth/serverpod_auth_migration/serverpod_auth_migration_server/lib/src/generated/protocol.dart, modules/new_serverpod_auth/serverpod_auth_migration/serverpod_auth_migration_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_bridge/serverpod_auth_bridge_server/pubspec.yaml, templates/pubspecs/modules/new_serverpod_auth/serverpod_auth_migration/serverpod_auth_migration_server/pubspec.yaml, templates/pubspecs/tests/serverpod_new_auth_test/serverpod_new_auth_test_server/pubspec.yaml, tests/serverpod_new_auth_test/serverpod_new_auth_test_client/lib/src/protocol/client.dart, tests/serverpod_new_auth_test/serverpod_new_auth_test_client/lib/src/protocol/protocol.dart, tests/serverpod_new_auth_test/serverpod_new_auth_test_flutter/test/session_manager_migration_test.dart, tests/serverpod_new_auth_test/serverpod_new_auth_test_server/lib/src/endpoints/email_account_backwards_compatibility_endpoint.dart, tests/serverpod_new_auth_test/serverpod_new_auth_test_server/lib/src/endpoints/google_account_backwards_compatibility_test_endpoint.dart, tests/serverpod_new_auth_test/serverpod_new_auth_test_server/lib/src/generated/endpoints.dart, tests/serverpod_new_auth_test/serverpod_new_auth_test_server/lib/src/generated/protocol.dart, tests/serverpod_new_auth_test/serverpod_new_auth_test_server/lib/src/generated/protocol.yaml, tests/serverpod_new_auth_test/serverpod_new_auth_test_server/pubspec.yaml, tests/serverpod_new_auth_test/serverpod_new_auth_test_server/test/integration/email_account_endpoint_test.dart, tests/serverpod_new_auth_test/serverpod_new_auth_test_server/test/integration/test_tools/serverpod_test_tools.dart
While working on #3674, I stumbled upon this minor fixes, that are better to be applied here separate from unrelated work.
Fixes a `Indentifer` typo on endpoints of bridge package and the import sort order for two new auth related packages.
N/A
=> fix: Fix minor typos and import order on auth migration package

packages/serverpod/lib/src/web_server/web_server.dart, tests/serverpod_test_server/test_integration/web_server/widget_route_cache_control_test.dart
This PR adds cache control headers to dynamic routes.
Fixes: https://github.com/serverpod/serverpod/issues/2534
=> feat: Add cache control headers to dynamic routes

.github/workflows/copilot-setup-steps.yml
While using copilot for a simple PR I noticed that the setup now fails because the required dart version of the repo is 3.7.0 (because of the analyzer package).
This PR bumps the version to Dart 3.9.0 so that we can also enable the use of the Dart MCP server: https://dart.dev/tools/mcp-server
None - simple Dart version bump for copilot.
=> chore: Bumping copilot to version 3.9.0 of Dart

modules/serverpod_auth/serverpod_auth_client/lib/src/protocol/client.dart, modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/email_endpoint.dart
In two places the docs says the below endpoint is google related, even though it was Email related. I think the docs where duplicated
=> fix: Incorrect documentation for the email auth endpoint

packages/serverpod/lib/src/server/serverpod.dart
The runtime settings update methods where using a feature flag for persistent logging. But this feature flag is toggled from user input, the runtime settings don't need the persistent logging to function. But it does need the database. I believe this worked originally because the persistent logging feature toggle was managed by the database feature in the initial implementation.
The problem was that if a user turned off persistent logging but had a database, we throw the StateError `Persistent logging is disabled, runtime settings are not stored in the database.`, which clearly is invalid.
none
=> fix: Use the database feature flag for runtime settings.

packages/serverpod/lib/src/endpoints/insights.dart, packages/serverpod_client/test/mutex_refresher_client_auth_key_provider_test.dart, tests/serverpod_test_server/test_e2e/method_streaming/open_stream_test.dart
Fixes the flaky test marked to skip on #3966 with the advice from the https://github.com/dart-lang/sdk/issues/61483 issue. Other similar cases were also fixed across the codebase.
N/A.
=> fix: Fix futures left with unhandled across async gaps on the codebase

modules/serverpod_auth/serverpod_auth_server/analysis_options.yaml, packages/serverpod/analysis_options.yaml, packages/serverpod_client/analysis_options.yaml, packages/serverpod_lints/lib/internal.yaml, packages/serverpod_serialization/analysis_options.yaml, packages/serverpod_service_client/analysis_options.yaml, packages/serverpod_shared/analysis_options.yaml, packages/serverpod_test/analysis_options.yaml, tools/serverpod_cli/analysis_options.yaml
Use defaults for Dart analyzer language settings. Instead of enabling strict-casts, strict-inference, and strict-raw-types language rules centrally in serverpod_lints, and then disabling them again in each serverpod package, don't specify them at all and use the Dart defaults.
n/a
=> chore: Use defaults for Dart analyzer language settings

packages/serverpod/lib/src/web_server/web_server.dart
Fixes an issue where file match misses had changed from a nullable type to a specific router type.
=> fix: Gracefully handle file match misses.
